// Code generated by terraform-plugin-framework-generator DO NOT EDIT.

package resource_etl_container

import (
	"context"
	"github.com/hashicorp/terraform-plugin-framework-validators/stringvalidator"
	"github.com/hashicorp/terraform-plugin-framework/schema/validator"
	"github.com/hashicorp/terraform-plugin-framework/types"

	"github.com/hashicorp/terraform-plugin-framework/resource/schema"
)

func EtlContainerResourceSchema(ctx context.Context) schema.Schema {
	return schema.Schema{
		Attributes: map[string]schema.Attribute{
			"created_time": schema.StringAttribute{
				Computed:            true,
				Description:         "When the ETL container was created.",
				MarkdownDescription: "When the ETL container was created.",
			},
			"deployment_id": schema.StringAttribute{
				Optional:            true,
				Computed:            true,
				Description:         "The deployment the container's connection will run through. Pick one from the deployments list. Only a deployment on Monte Carlo's current collection platform is accepted. Required for every type except `airflow`, which takes none.",
				MarkdownDescription: "The deployment the container's connection will run through. Pick one from the deployments list. Only a deployment on Monte Carlo's current collection platform is accepted. Required for every type except `airflow`, which takes none.",
			},
			"deployment_name": schema.StringAttribute{
				Computed:            true,
				Description:         "Display name of the deployment. Null exactly when `deployment_id` is.",
				MarkdownDescription: "Display name of the deployment. Null exactly when `deployment_id` is.",
			},
			"id": schema.StringAttribute{
				Computed:            true,
				Description:         "Unique identifier of the ETL container.",
				MarkdownDescription: "Unique identifier of the ETL container.",
			},
			"is_synthetic": schema.BoolAttribute{
				Computed:            true,
				Description:         "True for a container this API does not create or delete. Most belong to another connection, such as a warehouse or BI connection, and go away with it.",
				MarkdownDescription: "True for a container this API does not create or delete. Most belong to another connection, such as a warehouse or BI connection, and go away with it.",
			},
			"name": schema.StringAttribute{
				Required:            true,
				Description:         "Display name for the ETL container. No two containers of the same type can share a name.",
				MarkdownDescription: "Display name for the ETL container. No two containers of the same type can share a name.",
				Validators: []validator.String{
					stringvalidator.LengthBetween(1, 200),
				},
			},
			"type": schema.StringAttribute{
				Required:            true,
				Description:         "The ETL tool the container represents. Its connection has to be for this tool. Cannot be changed after the container is created.",
				MarkdownDescription: "The ETL tool the container represents. Its connection has to be for this tool. Cannot be changed after the container is created.",
				Validators: []validator.String{
					stringvalidator.OneOf(
						"airflow",
						"azure-data-factory",
						"fivetran",
						"gcp-dataform",
						"informatica-v2",
						"mulesoft",
					),
				},
			},
		},
	}
}

type EtlContainerModel struct {
	CreatedTime    types.String `tfsdk:"created_time"`
	DeploymentId   types.String `tfsdk:"deployment_id"`
	DeploymentName types.String `tfsdk:"deployment_name"`
	Id             types.String `tfsdk:"id"`
	IsSynthetic    types.Bool   `tfsdk:"is_synthetic"`
	Name           types.String `tfsdk:"name"`
	Type           types.String `tfsdk:"type"`
}
