// Code generated by terraform-plugin-framework-generator DO NOT EDIT.

package resource_deployment

import (
	"context"
	"github.com/hashicorp/terraform-plugin-framework-validators/stringvalidator"
	"github.com/hashicorp/terraform-plugin-framework/schema/validator"
	"github.com/hashicorp/terraform-plugin-framework/types"

	"github.com/hashicorp/terraform-plugin-framework/resource/schema"
)

func DeploymentResourceSchema(ctx context.Context) schema.Schema {
	return schema.Schema{
		Attributes: map[string]schema.Attribute{
			"aws_external_id": schema.StringAttribute{
				Computed:            true,
				Description:         "Value to supply when you register an AWS collection agent or data store on this deployment. It goes in the trust policy of the role Monte Carlo assumes. Null until Monte Carlo has generated one, for a deployment on another platform, for a caller who is not permitted to register one, and if the value could not be read just now. Retry the request in that last case.",
				MarkdownDescription: "Value to supply when you register an AWS collection agent or data store on this deployment. It goes in the trust policy of the role Monte Carlo assumes. Null until Monte Carlo has generated one, for a deployment on another platform, for a caller who is not permitted to register one, and if the value could not be read just now. Retry the request in that last case.",
			},
			"created_time": schema.StringAttribute{
				Computed:            true,
				Description:         "When the deployment was assigned to your account. Null when Monte Carlo has no record of that.",
				MarkdownDescription: "When the deployment was assigned to your account. Null when Monte Carlo has no record of that.",
			},
			"enabled": schema.BoolAttribute{
				Computed:            true,
				Description:         "Whether the deployment can serve connections. A deployment still waiting for its collection agent or data store to be registered, or with nothing provisioned on it, is not enabled.",
				MarkdownDescription: "Whether the deployment can serve connections. A deployment still waiting for its collection agent or data store to be registered, or with nothing provisioned on it, is not enabled.",
			},
			"id": schema.StringAttribute{
				Computed:            true,
				Description:         "Unique identifier of the deployment.",
				MarkdownDescription: "Unique identifier of the deployment.",
			},
			"last_updated_time": schema.StringAttribute{
				Computed:            true,
				Description:         "When Monte Carlo last updated the infrastructure behind the deployment. Null when Monte Carlo has no record of an update.",
				MarkdownDescription: "When Monte Carlo last updated the infrastructure behind the deployment. Null when Monte Carlo has no record of an update.",
			},
			"name": schema.StringAttribute{
				Optional:            true,
				Computed:            true,
				Description:         "Display name for the deployment. Monte Carlo generates one if you leave it out.",
				MarkdownDescription: "Display name for the deployment. Monte Carlo generates one if you leave it out.",
				Validators: []validator.String{
					stringvalidator.LengthAtMost(200),
				},
			},
			"runtime_platform": schema.StringAttribute{
				Required:            true,
				Description:         "Where the deployment's collection agent or data store will run. Either can be provisioned on `AWS`, `AZURE` or `GCP`, and a collection agent also on `GENERIC`. Any other combination is rejected.",
				MarkdownDescription: "Where the deployment's collection agent or data store will run. Either can be provisioned on `AWS`, `AZURE` or `GCP`, and a collection agent also on `GENERIC`. Any other combination is rejected.",
				Validators: []validator.String{
					stringvalidator.OneOf(
						"AWS",
						"AWS_PROXIED",
						"AZURE",
						"GCP",
						"GCP_PROXIED",
						"SNOWFLAKE",
						"GENERIC",
					),
				},
			},
			"type": schema.StringAttribute{
				Required:            true,
				Description:         "What the deployment will host. Only `COLLECTION_AGENT` and `COLLECTION_DATA_STORE` can be provisioned today. Any other value is rejected.",
				MarkdownDescription: "What the deployment will host. Only `COLLECTION_AGENT` and `COLLECTION_DATA_STORE` can be provisioned today. Any other value is rejected.",
				Validators: []validator.String{
					stringvalidator.OneOf(
						"COLLECTION_AGENT",
						"COLLECTION_DATA_STORE",
						"CLOUD",
					),
				},
			},
		},
	}
}

type DeploymentModel struct {
	AwsExternalId   types.String `tfsdk:"aws_external_id"`
	CreatedTime     types.String `tfsdk:"created_time"`
	Enabled         types.Bool   `tfsdk:"enabled"`
	Id              types.String `tfsdk:"id"`
	LastUpdatedTime types.String `tfsdk:"last_updated_time"`
	Name            types.String `tfsdk:"name"`
	RuntimePlatform types.String `tfsdk:"runtime_platform"`
	Type            types.String `tfsdk:"type"`
}
