// Code generated by terraform-plugin-framework-generator DO NOT EDIT.

package datasource_generic_collection_agent_oauth_client

import (
	"context"
	"github.com/hashicorp/terraform-plugin-framework/types"

	"github.com/hashicorp/terraform-plugin-framework/datasource/schema"
)

func GenericCollectionAgentOauthClientDataSourceSchema(ctx context.Context) schema.Schema {
	return schema.Schema{
		Attributes: map[string]schema.Attribute{
			"client_id": schema.StringAttribute{
				Computed:            true,
				Description:         "Client id the agent presents, as `client_id` in its configuration. The same value as `id`.",
				MarkdownDescription: "Client id the agent presents, as `client_id` in its configuration. The same value as `id`.",
			},
			"created_time": schema.StringAttribute{
				Computed:            true,
				Description:         "When the credential was created.",
				MarkdownDescription: "When the credential was created.",
			},
			"credential_id": schema.StringAttribute{
				Required:            true,
				Description:         "Id of the token or OAuth client, as returned when it is created or listed.",
				MarkdownDescription: "Id of the token or OAuth client, as returned when it is created or listed.",
			},
			"deployment_id": schema.StringAttribute{
				Computed:            true,
				Description:         "Identifier of the deployment whose agent presents this credential.",
				MarkdownDescription: "Identifier of the deployment whose agent presents this credential.",
			},
			"description": schema.StringAttribute{
				Computed:            true,
				Description:         "What this credential is for.",
				MarkdownDescription: "What this credential is for.",
			},
			"expiration_time": schema.StringAttribute{
				Computed:            true,
				Description:         "When the client stops being accepted. Null for a client that does not expire.",
				MarkdownDescription: "When the client stops being accepted. Null for a client that does not expire.",
			},
			"id": schema.StringAttribute{
				Computed:            true,
				Description:         "Unique identifier of the credential. For a token this is also its key id; for an OAuth client, its client id.",
				MarkdownDescription: "Unique identifier of the credential. For a token this is also its key id; for an OAuth client, its client id.",
			},
			"scopes": schema.ListAttribute{
				ElementType:         types.StringType,
				Computed:            true,
				Description:         "OAuth scopes the client is granted.",
				MarkdownDescription: "OAuth scopes the client is granted.",
			},
			"type": schema.StringAttribute{
				Computed:            true,
				Description:         "Which kind of credential this is.",
				MarkdownDescription: "Which kind of credential this is.",
			},
		},
		Description:         "An OAuth client is an OAuth 2.0 client id and secret a generic collection agent uses to authenticate to Monte Carlo. The secret is returned only when the client is created. A deployment can hold several clients, so create the new one before deleting the old one when rotating.",
		MarkdownDescription: "An OAuth client is an OAuth 2.0 client id and secret a generic collection agent uses to authenticate to Monte Carlo. The secret is returned only when the client is created. A deployment can hold several clients, so create the new one before deleting the old one when rotating.",
	}
}

type GenericCollectionAgentOauthClientModel struct {
	ClientId       types.String `tfsdk:"client_id"`
	CreatedTime    types.String `tfsdk:"created_time"`
	CredentialId   types.String `tfsdk:"credential_id"`
	DeploymentId   types.String `tfsdk:"deployment_id"`
	Description    types.String `tfsdk:"description"`
	ExpirationTime types.String `tfsdk:"expiration_time"`
	Id             types.String `tfsdk:"id"`
	Scopes         types.List   `tfsdk:"scopes"`
	Type           types.String `tfsdk:"type"`
}
