// Code generated by terraform-plugin-framework-generator DO NOT EDIT.

package datasource_self_hosted_env_var_credentials

import (
	"context"
	"github.com/hashicorp/terraform-plugin-framework/types"

	"github.com/hashicorp/terraform-plugin-framework/datasource/schema"
)

func SelfHostedEnvVarCredentialsDataSourceSchema(ctx context.Context) schema.Schema {
	return schema.Schema{
		Attributes: map[string]schema.Attribute{
			"bq_project_id": schema.StringAttribute{
				Computed: true,
			},
			"connection_type": schema.StringAttribute{
				Computed:            true,
				Description:         "The connection type the credentials are for, such as `snowflake`. Fixed once created.",
				MarkdownDescription: "The connection type the credentials are for, such as `snowflake`. Fixed once created.",
			},
			"created_time": schema.StringAttribute{
				Computed:            true,
				Description:         "When the credentials were created.",
				MarkdownDescription: "When the credentials were created.",
			},
			"credentials_id": schema.StringAttribute{
				Required: true,
			},
			"databricks_warehouse_id": schema.StringAttribute{
				Computed: true,
			},
			"env_var_name": schema.StringAttribute{
				Computed:            true,
				Description:         "Name of the environment variable on the deployment that holds the connection's credentials. Must start with `MCD_`.",
				MarkdownDescription: "Name of the environment variable on the deployment that holds the connection's credentials. Must start with `MCD_`.",
			},
			"id": schema.StringAttribute{
				Computed:            true,
				Description:         "Unique identifier of the credentials.",
				MarkdownDescription: "Unique identifier of the credentials.",
			},
			"kms_key_id": schema.StringAttribute{
				Computed: true,
			},
			"storage_type": schema.StringAttribute{
				Computed:            true,
				Description:         "Where the secret lives.\n\n`MC_MANAGED` credentials are stored by Monte Carlo. Every other value names a store you\nrun, which Monte Carlo reads from at connection time using the reference you supply.",
				MarkdownDescription: "Where the secret lives.\n\n`MC_MANAGED` credentials are stored by Monte Carlo. Every other value names a store you\nrun, which Monte Carlo reads from at connection time using the reference you supply.",
			},
		},
	}
}

type SelfHostedEnvVarCredentialsModel struct {
	BqProjectId           types.String `tfsdk:"bq_project_id"`
	ConnectionType        types.String `tfsdk:"connection_type"`
	CreatedTime           types.String `tfsdk:"created_time"`
	CredentialsId         types.String `tfsdk:"credentials_id"`
	DatabricksWarehouseId types.String `tfsdk:"databricks_warehouse_id"`
	EnvVarName            types.String `tfsdk:"env_var_name"`
	Id                    types.String `tfsdk:"id"`
	KmsKeyId              types.String `tfsdk:"kms_key_id"`
	StorageType           types.String `tfsdk:"storage_type"`
}
