// Code generated by terraform-plugin-framework-generator DO NOT EDIT.

package resource_aws_collection_data_store

import (
	"context"
	"github.com/hashicorp/terraform-plugin-framework-validators/stringvalidator"
	"github.com/hashicorp/terraform-plugin-framework/schema/validator"
	"github.com/hashicorp/terraform-plugin-framework/types"
	"regexp"

	"github.com/hashicorp/terraform-plugin-framework/resource/schema"
)

func AwsCollectionDataStoreResourceSchema(ctx context.Context) schema.Schema {
	return schema.Schema{
		Attributes: map[string]schema.Attribute{
			"authentication_type": schema.StringAttribute{
				Computed:            true,
				Description:         "How Monte Carlo authenticates to a collection agent or a data store.\n\nWhich values are possible depends on the platform it runs on.",
				MarkdownDescription: "How Monte Carlo authenticates to a collection agent or a data store.\n\nWhich values are possible depends on the platform it runs on.",
			},
			"bucket_name": schema.StringAttribute{
				Required:            true,
				Description:         "Name of the S3 bucket Monte Carlo should use.",
				MarkdownDescription: "Name of the S3 bucket Monte Carlo should use.",
				Validators: []validator.String{
					stringvalidator.RegexMatches(regexp.MustCompile("^[a-z0-9][a-z0-9.-]{1,61}[a-z0-9]$"), ""),
				},
			},
			"collection_data_store_id": schema.StringAttribute{
				Optional: true,
				Computed: true,
			},
			"created_time": schema.StringAttribute{
				Computed: true,
			},
			"deployment_id": schema.StringAttribute{
				Required:            true,
				Description:         "Deployment to register the data store on. It must already hold an unregistered S3 data store.",
				MarkdownDescription: "Deployment to register the data store on. It must already hold an unregistered S3 data store.",
			},
			"enabled": schema.BoolAttribute{
				Computed:            true,
				Description:         "Whether Monte Carlo is using this data store. One that is unregistered, or whose validation failed, is not enabled.",
				MarkdownDescription: "Whether Monte Carlo is using this data store. One that is unregistered, or whose validation failed, is not enabled.",
			},
			"external_id": schema.StringAttribute{
				Computed: true,
			},
			"id": schema.StringAttribute{
				Computed:            true,
				Description:         "Unique identifier of the data store.",
				MarkdownDescription: "Unique identifier of the data store.",
			},
			"last_updated_time": schema.StringAttribute{
				Computed: true,
			},
			"name": schema.StringAttribute{
				Optional: true,
				Computed: true,
				Validators: []validator.String{
					stringvalidator.LengthAtMost(200),
				},
			},
			"role_arn": schema.StringAttribute{
				Required:            true,
				Description:         "ARN of the role Monte Carlo assumes to access the bucket. Its trust policy must already carry the deployment's external id.",
				MarkdownDescription: "ARN of the role Monte Carlo assumes to access the bucket. Its trust policy must already carry the deployment's external id.",
				Validators: []validator.String{
					stringvalidator.RegexMatches(regexp.MustCompile("^arn:(aws[a-zA-Z-]*)?:iam::\\d{12}:role/.+$"), ""),
				},
			},
			"storage_type": schema.StringAttribute{
				Computed:            true,
				Description:         "Which kind of storage a collection data store keeps its data in.\n\nWhich values are possible depends on the platform the data store runs on.",
				MarkdownDescription: "Which kind of storage a collection data store keeps its data in.\n\nWhich values are possible depends on the platform the data store runs on.",
			},
		},
	}
}

type AwsCollectionDataStoreModel struct {
	AuthenticationType    types.String `tfsdk:"authentication_type"`
	BucketName            types.String `tfsdk:"bucket_name"`
	CollectionDataStoreId types.String `tfsdk:"collection_data_store_id"`
	CreatedTime           types.String `tfsdk:"created_time"`
	DeploymentId          types.String `tfsdk:"deployment_id"`
	Enabled               types.Bool   `tfsdk:"enabled"`
	ExternalId            types.String `tfsdk:"external_id"`
	Id                    types.String `tfsdk:"id"`
	LastUpdatedTime       types.String `tfsdk:"last_updated_time"`
	Name                  types.String `tfsdk:"name"`
	RoleArn               types.String `tfsdk:"role_arn"`
	StorageType           types.String `tfsdk:"storage_type"`
}
