// Code generated by terraform-plugin-framework-generator DO NOT EDIT.

package resource_generic_collection_agent_oauth_client

import (
	"context"
	"github.com/hashicorp/terraform-plugin-framework-validators/int64validator"
	"github.com/hashicorp/terraform-plugin-framework-validators/stringvalidator"
	"github.com/hashicorp/terraform-plugin-framework/schema/validator"
	"github.com/hashicorp/terraform-plugin-framework/types"

	"github.com/hashicorp/terraform-plugin-framework/resource/schema"
)

func GenericCollectionAgentOauthClientResourceSchema(ctx context.Context) schema.Schema {
	return schema.Schema{
		Attributes: map[string]schema.Attribute{
			"client_id": schema.StringAttribute{
				Computed:            true,
				Description:         "Client id the agent presents, as `client_id` in its configuration. The same value as `id`.",
				MarkdownDescription: "Client id the agent presents, as `client_id` in its configuration. The same value as `id`.",
			},
			"client_secret": schema.StringAttribute{
				Computed:            true,
				Sensitive:           true,
				Description:         "Secret the agent presents, as `client_secret` in its configuration. Returned once, by this call. It is not retrievable afterwards, and Terraform holds it in state like any generated credential. To rotate, create a new credential and delete this one.",
				MarkdownDescription: "Secret the agent presents, as `client_secret` in its configuration. Returned once, by this call. It is not retrievable afterwards, and Terraform holds it in state like any generated credential. To rotate, create a new credential and delete this one.",
			},
			"created_time": schema.StringAttribute{
				Computed:            true,
				Description:         "When the credential was created.",
				MarkdownDescription: "When the credential was created.",
			},
			"deployment_id": schema.StringAttribute{
				Required:            true,
				Description:         "Deployment whose generic collection agent will present this credential. It must have been provisioned for a generic collection agent.",
				MarkdownDescription: "Deployment whose generic collection agent will present this credential. It must have been provisioned for a generic collection agent.",
			},
			"description": schema.StringAttribute{
				Optional:            true,
				Computed:            true,
				Description:         "What this credential is for. Monte Carlo generates one naming the agent if you leave it out.",
				MarkdownDescription: "What this credential is for. Monte Carlo generates one naming the agent if you leave it out.",
				Validators: []validator.String{
					stringvalidator.LengthAtMost(200),
				},
			},
			"expiration_days": schema.Int64Attribute{
				Optional:            true,
				Computed:            true,
				Description:         "Days until the client stops being accepted. Leave it out for a client that does not expire.",
				MarkdownDescription: "Days until the client stops being accepted. Leave it out for a client that does not expire.",
				Validators: []validator.Int64{
					int64validator.AtLeast(1),
				},
			},
			"expiration_time": schema.StringAttribute{
				Computed:            true,
				Description:         "When the client stops being accepted. Null for a client that does not expire.",
				MarkdownDescription: "When the client stops being accepted. Null for a client that does not expire.",
			},
			"id": schema.StringAttribute{
				Computed:            true,
				Description:         "Unique identifier of the credential. For a token this is also its key id; for an OAuth client, its client id.",
				MarkdownDescription: "Unique identifier of the credential. For a token this is also its key id; for an OAuth client, its client id.",
			},
			"scopes": schema.ListAttribute{
				ElementType:         types.StringType,
				Computed:            true,
				Description:         "OAuth scopes the client is granted.",
				MarkdownDescription: "OAuth scopes the client is granted.",
			},
			"secret_id": schema.StringAttribute{
				Computed:            true,
				Description:         "Identifier of the secret this call created, as the client's secrets are listed. Keep it with the secret.",
				MarkdownDescription: "Identifier of the secret this call created, as the client's secrets are listed. Keep it with the secret.",
			},
			"type": schema.StringAttribute{
				Computed:            true,
				Description:         "Which kind of credential this is.",
				MarkdownDescription: "Which kind of credential this is.",
			},
		},
	}
}

type GenericCollectionAgentOauthClientModel struct {
	ClientId       types.String `tfsdk:"client_id"`
	ClientSecret   types.String `tfsdk:"client_secret"`
	CreatedTime    types.String `tfsdk:"created_time"`
	DeploymentId   types.String `tfsdk:"deployment_id"`
	Description    types.String `tfsdk:"description"`
	ExpirationDays types.Int64  `tfsdk:"expiration_days"`
	ExpirationTime types.String `tfsdk:"expiration_time"`
	Id             types.String `tfsdk:"id"`
	Scopes         types.List   `tfsdk:"scopes"`
	SecretId       types.String `tfsdk:"secret_id"`
	Type           types.String `tfsdk:"type"`
}
