// Code generated by terraform-plugin-framework-generator DO NOT EDIT.

package datasource_db2_credentials

import (
	"context"
	"github.com/hashicorp/terraform-plugin-framework/types"

	"github.com/hashicorp/terraform-plugin-framework/datasource/schema"
)

func Db2CredentialsDataSourceSchema(ctx context.Context) schema.Schema {
	return schema.Schema{
		Attributes: map[string]schema.Attribute{
			"connection_type": schema.StringAttribute{
				Computed:            true,
				Description:         "The connection type the credentials are for, such as `snowflake`. Fixed once created.",
				MarkdownDescription: "The connection type the credentials are for, such as `snowflake`. Fixed once created.",
			},
			"created_time": schema.StringAttribute{
				Computed:            true,
				Description:         "When the credentials were created.",
				MarkdownDescription: "When the credentials were created.",
			},
			"credentials_id": schema.StringAttribute{
				Required:            true,
				Description:         "Id of the credentials, as returned when they are created or listed.",
				MarkdownDescription: "Id of the credentials, as returned when they are created or listed.",
			},
			"db_name": schema.StringAttribute{
				Computed:            true,
				Description:         "Database to connect to. Null when none is set.",
				MarkdownDescription: "Database to connect to. Null when none is set.",
			},
			"host": schema.StringAttribute{
				Computed:            true,
				Description:         "Hostname of the database endpoint.",
				MarkdownDescription: "Hostname of the database endpoint.",
			},
			"id": schema.StringAttribute{
				Computed:            true,
				Description:         "Unique identifier of the credentials.",
				MarkdownDescription: "Unique identifier of the credentials.",
			},
			"port": schema.Int64Attribute{
				Computed:            true,
				Description:         "Port the database listens on.",
				MarkdownDescription: "Port the database listens on.",
			},
			"ssl_ca_data": schema.StringAttribute{
				Computed:            true,
				Description:         "PEM text of the CA certificate the server's certificate is checked against. Null when none is set.",
				MarkdownDescription: "PEM text of the CA certificate the server's certificate is checked against. Null when none is set.",
			},
			"ssl_disabled": schema.BoolAttribute{
				Computed:            true,
				Description:         "Connect without TLS. Null when unset.",
				MarkdownDescription: "Connect without TLS. Null when unset.",
			},
			"storage_type": schema.StringAttribute{
				Computed:            true,
				Description:         "Where the secret lives. Fixed once created.",
				MarkdownDescription: "Where the secret lives. Fixed once created.",
			},
			"user": schema.StringAttribute{
				Computed:            true,
				Description:         "Database user Monte Carlo logs in as.",
				MarkdownDescription: "Database user Monte Carlo logs in as.",
			},
		},
		Description:         "Db2 credentials are the login Monte Carlo stores for Db2 connections to use. The password is never returned.",
		MarkdownDescription: "Db2 credentials are the login Monte Carlo stores for Db2 connections to use. The password is never returned.",
	}
}

type Db2CredentialsModel struct {
	ConnectionType types.String `tfsdk:"connection_type"`
	CreatedTime    types.String `tfsdk:"created_time"`
	CredentialsId  types.String `tfsdk:"credentials_id"`
	DbName         types.String `tfsdk:"db_name"`
	Host           types.String `tfsdk:"host"`
	Id             types.String `tfsdk:"id"`
	Port           types.Int64  `tfsdk:"port"`
	SslCaData      types.String `tfsdk:"ssl_ca_data"`
	SslDisabled    types.Bool   `tfsdk:"ssl_disabled"`
	StorageType    types.String `tfsdk:"storage_type"`
	User           types.String `tfsdk:"user"`
}
