// Code generated by terraform-plugin-framework-generator DO NOT EDIT.

package resource_power_bi_credentials

import (
	"context"
	"github.com/hashicorp/terraform-plugin-framework-validators/int64validator"
	"github.com/hashicorp/terraform-plugin-framework-validators/stringvalidator"
	"github.com/hashicorp/terraform-plugin-framework/path"
	"github.com/hashicorp/terraform-plugin-framework/schema/validator"
	"github.com/hashicorp/terraform-plugin-framework/types"

	"github.com/hashicorp/terraform-plugin-framework/resource/schema"
)

func PowerBiCredentialsResourceSchema(ctx context.Context) schema.Schema {
	return schema.Schema{
		Attributes: map[string]schema.Attribute{
			"app_client_id": schema.StringAttribute{
				Required:            true,
				Description:         "Client ID of the Entra ID app registration Monte Carlo signs in with.",
				MarkdownDescription: "Client ID of the Entra ID app registration Monte Carlo signs in with.",
				Validators: []validator.String{
					stringvalidator.LengthBetween(1, 200),
				},
			},
			"app_client_secret_wo": schema.StringAttribute{
				Optional:            true,
				Sensitive:           true,
				Description:         "Secret of the app registration, for `service_principal`. Stored by Monte Carlo and never returned.",
				MarkdownDescription: "Secret of the app registration, for `service_principal`. Stored by Monte Carlo and never returned.",
				Validators: []validator.String{
					stringvalidator.LengthBetween(1, 1024),
					stringvalidator.AlsoRequires(path.MatchRelative().AtParent().AtName("app_client_secret_wo_version")),
				},
			},
			"app_client_secret_wo_version": schema.Int64Attribute{
				Optional:            true,
				Description:         "Bump to send `app_client_secret_wo` again. Terraform stores this, never the secret.",
				MarkdownDescription: "Bump to send `app_client_secret_wo` again. Terraform stores this, never the secret.",
				Validators: []validator.Int64{
					int64validator.AlsoRequires(path.MatchRelative().AtParent().AtName("app_client_secret_wo")),
				},
			},
			"auth_mode": schema.StringAttribute{
				Required:            true,
				Description:         "How Monte Carlo signs in. `service_principal` takes `app_client_secret`. `primary_user` takes `username` and `password`.",
				MarkdownDescription: "How Monte Carlo signs in. `service_principal` takes `app_client_secret`. `primary_user` takes `username` and `password`.",
				Validators: []validator.String{
					stringvalidator.OneOf(
						"service_principal",
						"primary_user",
					),
				},
			},
			"connection_type": schema.StringAttribute{
				Computed:            true,
				Description:         "The connection type the credentials are for, such as `snowflake`. Fixed once created.",
				MarkdownDescription: "The connection type the credentials are for, such as `snowflake`. Fixed once created.",
			},
			"created_time": schema.StringAttribute{
				Computed:            true,
				Description:         "When the credentials were created.",
				MarkdownDescription: "When the credentials were created.",
			},
			"id": schema.StringAttribute{
				Computed:            true,
				Description:         "Unique identifier of the credentials.",
				MarkdownDescription: "Unique identifier of the credentials.",
			},
			"password_wo": schema.StringAttribute{
				Optional:            true,
				Sensitive:           true,
				Description:         "Password of `username`, for `primary_user`. Stored by Monte Carlo and never returned.",
				MarkdownDescription: "Password of `username`, for `primary_user`. Stored by Monte Carlo and never returned.",
				Validators: []validator.String{
					stringvalidator.LengthBetween(1, 1024),
					stringvalidator.AlsoRequires(path.MatchRelative().AtParent().AtName("password_wo_version")),
				},
			},
			"password_wo_version": schema.Int64Attribute{
				Optional:            true,
				Description:         "Bump to send `password_wo` again. Terraform stores this, never the secret.",
				MarkdownDescription: "Bump to send `password_wo` again. Terraform stores this, never the secret.",
				Validators: []validator.Int64{
					int64validator.AlsoRequires(path.MatchRelative().AtParent().AtName("password_wo")),
				},
			},
			"storage_type": schema.StringAttribute{
				Computed:            true,
				Description:         "Where the secret lives. Fixed once created.",
				MarkdownDescription: "Where the secret lives. Fixed once created.",
			},
			"tenant_id": schema.StringAttribute{
				Required:            true,
				Description:         "Microsoft Entra ID tenant the Power BI service belongs to.",
				MarkdownDescription: "Microsoft Entra ID tenant the Power BI service belongs to.",
				Validators: []validator.String{
					stringvalidator.LengthBetween(1, 200),
				},
			},
			"username": schema.StringAttribute{
				Optional:            true,
				Computed:            true,
				Description:         "User Monte Carlo signs in as, for `primary_user`.",
				MarkdownDescription: "User Monte Carlo signs in as, for `primary_user`.",
				Validators: []validator.String{
					stringvalidator.LengthBetween(1, 200),
				},
			},
		},
	}
}

type PowerBiCredentialsModel struct {
	AppClientId              types.String `tfsdk:"app_client_id"`
	AppClientSecretWo        types.String `tfsdk:"app_client_secret_wo"`
	AppClientSecretWoVersion types.Int64  `tfsdk:"app_client_secret_wo_version"`
	AuthMode                 types.String `tfsdk:"auth_mode"`
	ConnectionType           types.String `tfsdk:"connection_type"`
	CreatedTime              types.String `tfsdk:"created_time"`
	Id                       types.String `tfsdk:"id"`
	PasswordWo               types.String `tfsdk:"password_wo"`
	PasswordWoVersion        types.Int64  `tfsdk:"password_wo_version"`
	StorageType              types.String `tfsdk:"storage_type"`
	TenantId                 types.String `tfsdk:"tenant_id"`
	Username                 types.String `tfsdk:"username"`
}
