// Code generated by terraform-plugin-framework-generator DO NOT EDIT.

package resource_bigquery_credentials

import (
	"context"
	"github.com/hashicorp/terraform-plugin-framework-validators/stringvalidator"
	"github.com/hashicorp/terraform-plugin-framework/schema/validator"
	"github.com/hashicorp/terraform-plugin-framework/types"

	"github.com/hashicorp/terraform-plugin-framework/resource/schema"
)

func BigqueryCredentialsResourceSchema(ctx context.Context) schema.Schema {
	return schema.Schema{
		Attributes: map[string]schema.Attribute{
			"client_email": schema.StringAttribute{
				Computed:            true,
				Description:         "Email address of the service account.",
				MarkdownDescription: "Email address of the service account.",
			},
			"connection_type": schema.StringAttribute{
				Computed:            true,
				Description:         "The connection type the credentials are for, such as `snowflake`. Fixed once created.",
				MarkdownDescription: "The connection type the credentials are for, such as `snowflake`. Fixed once created.",
			},
			"created_time": schema.StringAttribute{
				Computed:            true,
				Description:         "When the credentials were created.",
				MarkdownDescription: "When the credentials were created.",
			},
			"id": schema.StringAttribute{
				Computed:            true,
				Description:         "Unique identifier of the credentials.",
				MarkdownDescription: "Unique identifier of the credentials.",
			},
			"project_id": schema.StringAttribute{
				Computed:            true,
				Description:         "Google Cloud project the service account belongs to.",
				MarkdownDescription: "Google Cloud project the service account belongs to.",
			},
			"service_account_key_wo": schema.StringAttribute{
				Required:            true,
				Sensitive:           true,
				Description:         "The service account's JSON key file, as its text. Stored by Monte Carlo and never returned.",
				MarkdownDescription: "The service account's JSON key file, as its text. Stored by Monte Carlo and never returned.",
				Validators: []validator.String{
					stringvalidator.LengthAtMost(16384),
				},
			},
			"service_account_key_wo_version": schema.Int64Attribute{
				Required:            true,
				Description:         "Bump to send `service_account_key_wo` again. Terraform stores this, never the secret.",
				MarkdownDescription: "Bump to send `service_account_key_wo` again. Terraform stores this, never the secret.",
			},
			"storage_type": schema.StringAttribute{
				Computed:            true,
				Description:         "Where the secret lives. Fixed once created.",
				MarkdownDescription: "Where the secret lives. Fixed once created.",
			},
		},
		Description:         "BigQuery credentials are a service account key Monte Carlo stores for BigQuery connections to use. The key is never returned.",
		MarkdownDescription: "BigQuery credentials are a service account key Monte Carlo stores for BigQuery connections to use. The key is never returned.",
	}
}

type BigqueryCredentialsModel struct {
	ClientEmail                types.String `tfsdk:"client_email"`
	ConnectionType             types.String `tfsdk:"connection_type"`
	CreatedTime                types.String `tfsdk:"created_time"`
	Id                         types.String `tfsdk:"id"`
	ProjectId                  types.String `tfsdk:"project_id"`
	ServiceAccountKeyWo        types.String `tfsdk:"service_account_key_wo"`
	ServiceAccountKeyWoVersion types.Int64  `tfsdk:"service_account_key_wo_version"`
	StorageType                types.String `tfsdk:"storage_type"`
}
