// Code generated by terraform-plugin-framework-generator DO NOT EDIT.

package resource_aws_collection_agent

import (
	"context"
	"github.com/hashicorp/terraform-plugin-framework-validators/stringvalidator"
	"github.com/hashicorp/terraform-plugin-framework/schema/validator"
	"github.com/hashicorp/terraform-plugin-framework/types"
	"regexp"

	"github.com/hashicorp/terraform-plugin-framework/resource/schema"
)

func AwsCollectionAgentResourceSchema(ctx context.Context) schema.Schema {
	return schema.Schema{
		Attributes: map[string]schema.Attribute{
			"authentication_type": schema.StringAttribute{
				Computed:            true,
				Description:         "How Monte Carlo authenticates to a collection agent or a data store.\n\nWhich values are possible depends on the platform it runs on.",
				MarkdownDescription: "How Monte Carlo authenticates to a collection agent or a data store.\n\nWhich values are possible depends on the platform it runs on.",
			},
			"created_time": schema.StringAttribute{
				Computed: true,
			},
			"deployment_id": schema.StringAttribute{
				Required:            true,
				Description:         "Deployment to register the collection agent on. It must already hold an unregistered AWS collection agent.",
				MarkdownDescription: "Deployment to register the collection agent on. It must already hold an unregistered AWS collection agent.",
			},
			"enabled": schema.BoolAttribute{
				Computed:            true,
				Description:         "Whether Monte Carlo is using this collection agent. An agent Monte Carlo has not validated is not enabled, either because it has not been registered yet or because validation failed.",
				MarkdownDescription: "Whether Monte Carlo is using this collection agent. An agent Monte Carlo has not validated is not enabled, either because it has not been registered yet or because validation failed.",
			},
			"external_id": schema.StringAttribute{
				Computed: true,
			},
			"id": schema.StringAttribute{
				Computed:            true,
				Description:         "Unique identifier of the collection agent.",
				MarkdownDescription: "Unique identifier of the collection agent.",
			},
			"image_build": schema.StringAttribute{
				Computed: true,
			},
			"image_version": schema.StringAttribute{
				Computed: true,
			},
			"is_remote_upgradeable": schema.BoolAttribute{
				Computed:            true,
				Description:         "Whether Monte Carlo can update the collection agent's image for you.",
				MarkdownDescription: "Whether Monte Carlo can update the collection agent's image for you.",
			},
			"lambda_function_arn": schema.StringAttribute{
				Required:            true,
				Description:         "ARN of the Lambda function Monte Carlo should invoke.",
				MarkdownDescription: "ARN of the Lambda function Monte Carlo should invoke.",
			},
			"last_updated_time": schema.StringAttribute{
				Computed: true,
			},
			"name": schema.StringAttribute{
				Optional: true,
				Computed: true,
				Validators: []validator.String{
					stringvalidator.LengthAtMost(200),
				},
			},
			"role_arn": schema.StringAttribute{
				Required:            true,
				Description:         "ARN of the role Monte Carlo assumes to invoke the function. Its trust policy must already carry the deployment's external id.",
				MarkdownDescription: "ARN of the role Monte Carlo assumes to invoke the function. Its trust policy must already carry the deployment's external id.",
				Validators: []validator.String{
					stringvalidator.RegexMatches(regexp.MustCompile("^arn:(aws[a-zA-Z-]*)?:iam::\\d{12}:role/.+$"), ""),
				},
			},
		},
	}
}

type AwsCollectionAgentModel struct {
	AuthenticationType  types.String `tfsdk:"authentication_type"`
	CreatedTime         types.String `tfsdk:"created_time"`
	DeploymentId        types.String `tfsdk:"deployment_id"`
	Enabled             types.Bool   `tfsdk:"enabled"`
	ExternalId          types.String `tfsdk:"external_id"`
	Id                  types.String `tfsdk:"id"`
	ImageBuild          types.String `tfsdk:"image_build"`
	ImageVersion        types.String `tfsdk:"image_version"`
	IsRemoteUpgradeable types.Bool   `tfsdk:"is_remote_upgradeable"`
	LambdaFunctionArn   types.String `tfsdk:"lambda_function_arn"`
	LastUpdatedTime     types.String `tfsdk:"last_updated_time"`
	Name                types.String `tfsdk:"name"`
	RoleArn             types.String `tfsdk:"role_arn"`
}
