// Code generated by terraform-plugin-framework-generator DO NOT EDIT.

package datasource_custom_connector_type

import (
	"context"
	"fmt"
	"github.com/hashicorp/terraform-plugin-framework/attr"
	"github.com/hashicorp/terraform-plugin-framework/diag"
	"github.com/hashicorp/terraform-plugin-framework/types"
	"github.com/hashicorp/terraform-plugin-framework/types/basetypes"
	"github.com/hashicorp/terraform-plugin-go/tftypes"
	"strings"

	"github.com/hashicorp/terraform-plugin-framework/datasource/schema"
)

func CustomConnectorTypeDataSourceSchema(ctx context.Context) schema.Schema {
	return schema.Schema{
		Attributes: map[string]schema.Attribute{
			"asset_class": schema.StringAttribute{
				Computed:            true,
				Description:         "What the connector connects to: a warehouse, an ETL tool or a BI tool.",
				MarkdownDescription: "What the connector connects to: a warehouse, an ETL tool or a BI tool.",
			},
			"capabilities": schema.SingleNestedAttribute{
				Attributes: map[string]schema.Attribute{
					"supports_agent_monitor": schema.BoolAttribute{
						Computed:            true,
						Description:         "Whether the connector supports agent monitors.",
						MarkdownDescription: "Whether the connector supports agent monitors.",
					},
					"supports_agent_trajectory_monitor": schema.BoolAttribute{
						Computed:            true,
						Description:         "Whether the connector supports agent trajectory monitors.",
						MarkdownDescription: "Whether the connector supports agent trajectory monitors.",
					},
					"supports_comparison_monitor": schema.BoolAttribute{
						Computed:            true,
						Description:         "Whether the connector supports comparison monitors.",
						MarkdownDescription: "Whether the connector supports comparison monitors.",
					},
					"supports_custom_sql_monitor": schema.BoolAttribute{
						Computed:            true,
						Description:         "Whether the connector supports custom SQL monitors.",
						MarkdownDescription: "Whether the connector supports custom SQL monitors.",
					},
					"supports_field_lineage": schema.BoolAttribute{
						Computed:            true,
						Description:         "Whether the connector supports field-level lineage.",
						MarkdownDescription: "Whether the connector supports field-level lineage.",
					},
					"supports_freshness": schema.BoolAttribute{
						Computed:            true,
						Description:         "Whether the connector supports freshness monitoring.",
						MarkdownDescription: "Whether the connector supports freshness monitoring.",
					},
					"supports_full_query_language": schema.BoolAttribute{
						Computed:            true,
						Description:         "Whether the connector supports the full query language.",
						MarkdownDescription: "Whether the connector supports the full query language.",
					},
					"supports_json_schema_monitor": schema.BoolAttribute{
						Computed:            true,
						Description:         "Whether the connector supports JSON schema monitors.",
						MarkdownDescription: "Whether the connector supports JSON schema monitors.",
					},
					"supports_lineage": schema.BoolAttribute{
						Computed:            true,
						Description:         "Whether the connector supports lineage extraction.",
						MarkdownDescription: "Whether the connector supports lineage extraction.",
					},
					"supports_metadata": schema.BoolAttribute{
						Computed:            true,
						Description:         "Whether the connector supports metadata collection.",
						MarkdownDescription: "Whether the connector supports metadata collection.",
					},
					"supports_metric_monitors_on_unknown_types": schema.BoolAttribute{
						Computed:            true,
						Description:         "Whether the connector supports metric monitors on unknown field types.",
						MarkdownDescription: "Whether the connector supports metric monitors on unknown field types.",
					},
					"supports_non_metadata_size_collection": schema.BoolAttribute{
						Computed:            true,
						Description:         "Whether the connector supports size collection without metadata.",
						MarkdownDescription: "Whether the connector supports size collection without metadata.",
					},
					"supports_query_logs": schema.BoolAttribute{
						Computed:            true,
						Description:         "Whether the connector supports query log collection.",
						MarkdownDescription: "Whether the connector supports query log collection.",
					},
					"supports_schema": schema.BoolAttribute{
						Computed:            true,
						Description:         "Whether the connector supports schema collection.",
						MarkdownDescription: "Whether the connector supports schema collection.",
					},
					"supports_stats_monitor": schema.BoolAttribute{
						Computed:            true,
						Description:         "Whether the connector supports stats monitors.",
						MarkdownDescription: "Whether the connector supports stats monitors.",
					},
					"supports_transform": schema.BoolAttribute{
						Computed:            true,
						Description:         "Whether the connector supports transforms.",
						MarkdownDescription: "Whether the connector supports transforms.",
					},
					"supports_validation_monitor": schema.BoolAttribute{
						Computed:            true,
						Description:         "Whether the connector supports validation monitors.",
						MarkdownDescription: "Whether the connector supports validation monitors.",
					},
					"supports_volume_bytes": schema.BoolAttribute{
						Computed:            true,
						Description:         "Whether the connector supports byte-size volume monitoring.",
						MarkdownDescription: "Whether the connector supports byte-size volume monitoring.",
					},
					"supports_volume_rows": schema.BoolAttribute{
						Computed:            true,
						Description:         "Whether the connector supports row-count volume monitoring.",
						MarkdownDescription: "Whether the connector supports row-count volume monitoring.",
					},
				},
				CustomType: CapabilitiesType{
					ObjectType: types.ObjectType{
						AttrTypes: CapabilitiesValue{}.AttributeTypes(ctx),
					},
				},
				Computed:            true,
				Description:         "What the connector supports. Set only for a warehouse connector.",
				MarkdownDescription: "What the connector supports. Set only for a warehouse connector.",
			},
			"collection_agent_id": schema.StringAttribute{
				Computed:            true,
				Description:         "The collection agent that registered the connector. It may name an agent the collection agents endpoints no longer list.",
				MarkdownDescription: "The collection agent that registered the connector. It may name an agent the collection agents endpoints no longer list.",
			},
			"created_time": schema.StringAttribute{
				Computed:            true,
				Description:         "When the connector type was first registered.",
				MarkdownDescription: "When the connector type was first registered.",
			},
			"custom_connector_type_id": schema.StringAttribute{
				Required:            true,
				Description:         "Id of the custom connector type, as returned when it is listed.",
				MarkdownDescription: "Id of the custom connector type, as returned when it is listed.",
			},
			"deployment_id": schema.StringAttribute{
				Computed:            true,
				Description:         "The deployment of the collection agent that registered the connector. Its connections run there. The id may name a deployment the deployments endpoints do not list.",
				MarkdownDescription: "The deployment of the collection agent that registered the connector. Its connections run there. The id may name a deployment the deployments endpoints do not list.",
			},
			"icon_url": schema.StringAttribute{
				Computed:            true,
				Description:         "Icon for the connector. Supplied by the collection agent, not validated, and never fetched by Monte Carlo. Null for a warehouse connector, or when none was supplied.",
				MarkdownDescription: "Icon for the connector. Supplied by the collection agent, not validated, and never fetched by Monte Carlo. Null for a warehouse connector, or when none was supplied.",
			},
			"id": schema.StringAttribute{
				Computed:            true,
				Description:         "Unique identifier of the custom connector type, used as a connection type.",
				MarkdownDescription: "Unique identifier of the custom connector type, used as a connection type.",
			},
			"job_types": schema.ListAttribute{
				ElementType:         types.StringType,
				Computed:            true,
				Description:         "The collection jobs the connector runs.",
				MarkdownDescription: "The collection jobs the connector runs.",
			},
			"name": schema.StringAttribute{
				Computed:            true,
				Description:         "Display name of the connector. Supplied by the collection agent that registered it, and not validated.",
				MarkdownDescription: "Display name of the connector. Supplied by the collection agent that registered it, and not validated.",
			},
			"terminology": schema.SingleNestedAttribute{
				Attributes: map[string]schema.Attribute{
					"group": schema.StringAttribute{
						Computed:            true,
						Description:         "Noun for the group tier above jobs. Null if the tool has none.",
						MarkdownDescription: "Noun for the group tier above jobs. Null if the tool has none.",
					},
					"job": schema.StringAttribute{
						Computed:            true,
						Description:         "Noun for the job tier.",
						MarkdownDescription: "Noun for the job tier.",
					},
					"task": schema.StringAttribute{
						Computed:            true,
						Description:         "Noun for the task tier. Null if the tool has none.",
						MarkdownDescription: "Noun for the task tier. Null if the tool has none.",
					},
				},
				CustomType: TerminologyType{
					ObjectType: types.ObjectType{
						AttrTypes: TerminologyValue{}.AttributeTypes(ctx),
					},
				},
				Computed:            true,
				Description:         "The connector's nouns for its tiers. Set only for an ETL connector.",
				MarkdownDescription: "The connector's nouns for its tiers. Set only for an ETL connector.",
			},
			"updated_time": schema.StringAttribute{
				Computed:            true,
				Description:         "When the connector type was last registered.",
				MarkdownDescription: "When the connector type was last registered.",
			},
		},
		Description:         "A custom connector type is an integration one of your collection agents registered for your account. Use its id as the connection type of self-hosted credentials, and create its warehouse, ETL container or BI container on its deployment.",
		MarkdownDescription: "A custom connector type is an integration one of your collection agents registered for your account. Use its id as the connection type of self-hosted credentials, and create its warehouse, ETL container or BI container on its deployment.",
	}
}

type CustomConnectorTypeModel struct {
	AssetClass            types.String      `tfsdk:"asset_class"`
	Capabilities          CapabilitiesValue `tfsdk:"capabilities"`
	CollectionAgentId     types.String      `tfsdk:"collection_agent_id"`
	CreatedTime           types.String      `tfsdk:"created_time"`
	CustomConnectorTypeId types.String      `tfsdk:"custom_connector_type_id"`
	DeploymentId          types.String      `tfsdk:"deployment_id"`
	IconUrl               types.String      `tfsdk:"icon_url"`
	Id                    types.String      `tfsdk:"id"`
	JobTypes              types.List        `tfsdk:"job_types"`
	Name                  types.String      `tfsdk:"name"`
	Terminology           TerminologyValue  `tfsdk:"terminology"`
	UpdatedTime           types.String      `tfsdk:"updated_time"`
}

var _ basetypes.ObjectTypable = CapabilitiesType{}

type CapabilitiesType struct {
	basetypes.ObjectType
}

func (t CapabilitiesType) Equal(o attr.Type) bool {
	other, ok := o.(CapabilitiesType)

	if !ok {
		return false
	}

	return t.ObjectType.Equal(other.ObjectType)
}

func (t CapabilitiesType) String() string {
	return "CapabilitiesType"
}

func (t CapabilitiesType) ValueFromObject(ctx context.Context, in basetypes.ObjectValue) (basetypes.ObjectValuable, diag.Diagnostics) {
	var diags diag.Diagnostics

	attributes := in.Attributes()

	supportsAgentMonitorAttribute, ok := attributes["supports_agent_monitor"]

	if !ok {
		diags.AddError(
			"Attribute Missing",
			`supports_agent_monitor is missing from object`)

		return nil, diags
	}

	supportsAgentMonitorVal, ok := supportsAgentMonitorAttribute.(basetypes.BoolValue)

	if !ok {
		diags.AddError(
			"Attribute Wrong Type",
			fmt.Sprintf(`supports_agent_monitor expected to be basetypes.BoolValue, was: %T`, supportsAgentMonitorAttribute))
	}

	supportsAgentTrajectoryMonitorAttribute, ok := attributes["supports_agent_trajectory_monitor"]

	if !ok {
		diags.AddError(
			"Attribute Missing",
			`supports_agent_trajectory_monitor is missing from object`)

		return nil, diags
	}

	supportsAgentTrajectoryMonitorVal, ok := supportsAgentTrajectoryMonitorAttribute.(basetypes.BoolValue)

	if !ok {
		diags.AddError(
			"Attribute Wrong Type",
			fmt.Sprintf(`supports_agent_trajectory_monitor expected to be basetypes.BoolValue, was: %T`, supportsAgentTrajectoryMonitorAttribute))
	}

	supportsComparisonMonitorAttribute, ok := attributes["supports_comparison_monitor"]

	if !ok {
		diags.AddError(
			"Attribute Missing",
			`supports_comparison_monitor is missing from object`)

		return nil, diags
	}

	supportsComparisonMonitorVal, ok := supportsComparisonMonitorAttribute.(basetypes.BoolValue)

	if !ok {
		diags.AddError(
			"Attribute Wrong Type",
			fmt.Sprintf(`supports_comparison_monitor expected to be basetypes.BoolValue, was: %T`, supportsComparisonMonitorAttribute))
	}

	supportsCustomSqlMonitorAttribute, ok := attributes["supports_custom_sql_monitor"]

	if !ok {
		diags.AddError(
			"Attribute Missing",
			`supports_custom_sql_monitor is missing from object`)

		return nil, diags
	}

	supportsCustomSqlMonitorVal, ok := supportsCustomSqlMonitorAttribute.(basetypes.BoolValue)

	if !ok {
		diags.AddError(
			"Attribute Wrong Type",
			fmt.Sprintf(`supports_custom_sql_monitor expected to be basetypes.BoolValue, was: %T`, supportsCustomSqlMonitorAttribute))
	}

	supportsFieldLineageAttribute, ok := attributes["supports_field_lineage"]

	if !ok {
		diags.AddError(
			"Attribute Missing",
			`supports_field_lineage is missing from object`)

		return nil, diags
	}

	supportsFieldLineageVal, ok := supportsFieldLineageAttribute.(basetypes.BoolValue)

	if !ok {
		diags.AddError(
			"Attribute Wrong Type",
			fmt.Sprintf(`supports_field_lineage expected to be basetypes.BoolValue, was: %T`, supportsFieldLineageAttribute))
	}

	supportsFreshnessAttribute, ok := attributes["supports_freshness"]

	if !ok {
		diags.AddError(
			"Attribute Missing",
			`supports_freshness is missing from object`)

		return nil, diags
	}

	supportsFreshnessVal, ok := supportsFreshnessAttribute.(basetypes.BoolValue)

	if !ok {
		diags.AddError(
			"Attribute Wrong Type",
			fmt.Sprintf(`supports_freshness expected to be basetypes.BoolValue, was: %T`, supportsFreshnessAttribute))
	}

	supportsFullQueryLanguageAttribute, ok := attributes["supports_full_query_language"]

	if !ok {
		diags.AddError(
			"Attribute Missing",
			`supports_full_query_language is missing from object`)

		return nil, diags
	}

	supportsFullQueryLanguageVal, ok := supportsFullQueryLanguageAttribute.(basetypes.BoolValue)

	if !ok {
		diags.AddError(
			"Attribute Wrong Type",
			fmt.Sprintf(`supports_full_query_language expected to be basetypes.BoolValue, was: %T`, supportsFullQueryLanguageAttribute))
	}

	supportsJsonSchemaMonitorAttribute, ok := attributes["supports_json_schema_monitor"]

	if !ok {
		diags.AddError(
			"Attribute Missing",
			`supports_json_schema_monitor is missing from object`)

		return nil, diags
	}

	supportsJsonSchemaMonitorVal, ok := supportsJsonSchemaMonitorAttribute.(basetypes.BoolValue)

	if !ok {
		diags.AddError(
			"Attribute Wrong Type",
			fmt.Sprintf(`supports_json_schema_monitor expected to be basetypes.BoolValue, was: %T`, supportsJsonSchemaMonitorAttribute))
	}

	supportsLineageAttribute, ok := attributes["supports_lineage"]

	if !ok {
		diags.AddError(
			"Attribute Missing",
			`supports_lineage is missing from object`)

		return nil, diags
	}

	supportsLineageVal, ok := supportsLineageAttribute.(basetypes.BoolValue)

	if !ok {
		diags.AddError(
			"Attribute Wrong Type",
			fmt.Sprintf(`supports_lineage expected to be basetypes.BoolValue, was: %T`, supportsLineageAttribute))
	}

	supportsMetadataAttribute, ok := attributes["supports_metadata"]

	if !ok {
		diags.AddError(
			"Attribute Missing",
			`supports_metadata is missing from object`)

		return nil, diags
	}

	supportsMetadataVal, ok := supportsMetadataAttribute.(basetypes.BoolValue)

	if !ok {
		diags.AddError(
			"Attribute Wrong Type",
			fmt.Sprintf(`supports_metadata expected to be basetypes.BoolValue, was: %T`, supportsMetadataAttribute))
	}

	supportsMetricMonitorsOnUnknownTypesAttribute, ok := attributes["supports_metric_monitors_on_unknown_types"]

	if !ok {
		diags.AddError(
			"Attribute Missing",
			`supports_metric_monitors_on_unknown_types is missing from object`)

		return nil, diags
	}

	supportsMetricMonitorsOnUnknownTypesVal, ok := supportsMetricMonitorsOnUnknownTypesAttribute.(basetypes.BoolValue)

	if !ok {
		diags.AddError(
			"Attribute Wrong Type",
			fmt.Sprintf(`supports_metric_monitors_on_unknown_types expected to be basetypes.BoolValue, was: %T`, supportsMetricMonitorsOnUnknownTypesAttribute))
	}

	supportsNonMetadataSizeCollectionAttribute, ok := attributes["supports_non_metadata_size_collection"]

	if !ok {
		diags.AddError(
			"Attribute Missing",
			`supports_non_metadata_size_collection is missing from object`)

		return nil, diags
	}

	supportsNonMetadataSizeCollectionVal, ok := supportsNonMetadataSizeCollectionAttribute.(basetypes.BoolValue)

	if !ok {
		diags.AddError(
			"Attribute Wrong Type",
			fmt.Sprintf(`supports_non_metadata_size_collection expected to be basetypes.BoolValue, was: %T`, supportsNonMetadataSizeCollectionAttribute))
	}

	supportsQueryLogsAttribute, ok := attributes["supports_query_logs"]

	if !ok {
		diags.AddError(
			"Attribute Missing",
			`supports_query_logs is missing from object`)

		return nil, diags
	}

	supportsQueryLogsVal, ok := supportsQueryLogsAttribute.(basetypes.BoolValue)

	if !ok {
		diags.AddError(
			"Attribute Wrong Type",
			fmt.Sprintf(`supports_query_logs expected to be basetypes.BoolValue, was: %T`, supportsQueryLogsAttribute))
	}

	supportsSchemaAttribute, ok := attributes["supports_schema"]

	if !ok {
		diags.AddError(
			"Attribute Missing",
			`supports_schema is missing from object`)

		return nil, diags
	}

	supportsSchemaVal, ok := supportsSchemaAttribute.(basetypes.BoolValue)

	if !ok {
		diags.AddError(
			"Attribute Wrong Type",
			fmt.Sprintf(`supports_schema expected to be basetypes.BoolValue, was: %T`, supportsSchemaAttribute))
	}

	supportsStatsMonitorAttribute, ok := attributes["supports_stats_monitor"]

	if !ok {
		diags.AddError(
			"Attribute Missing",
			`supports_stats_monitor is missing from object`)

		return nil, diags
	}

	supportsStatsMonitorVal, ok := supportsStatsMonitorAttribute.(basetypes.BoolValue)

	if !ok {
		diags.AddError(
			"Attribute Wrong Type",
			fmt.Sprintf(`supports_stats_monitor expected to be basetypes.BoolValue, was: %T`, supportsStatsMonitorAttribute))
	}

	supportsTransformAttribute, ok := attributes["supports_transform"]

	if !ok {
		diags.AddError(
			"Attribute Missing",
			`supports_transform is missing from object`)

		return nil, diags
	}

	supportsTransformVal, ok := supportsTransformAttribute.(basetypes.BoolValue)

	if !ok {
		diags.AddError(
			"Attribute Wrong Type",
			fmt.Sprintf(`supports_transform expected to be basetypes.BoolValue, was: %T`, supportsTransformAttribute))
	}

	supportsValidationMonitorAttribute, ok := attributes["supports_validation_monitor"]

	if !ok {
		diags.AddError(
			"Attribute Missing",
			`supports_validation_monitor is missing from object`)

		return nil, diags
	}

	supportsValidationMonitorVal, ok := supportsValidationMonitorAttribute.(basetypes.BoolValue)

	if !ok {
		diags.AddError(
			"Attribute Wrong Type",
			fmt.Sprintf(`supports_validation_monitor expected to be basetypes.BoolValue, was: %T`, supportsValidationMonitorAttribute))
	}

	supportsVolumeBytesAttribute, ok := attributes["supports_volume_bytes"]

	if !ok {
		diags.AddError(
			"Attribute Missing",
			`supports_volume_bytes is missing from object`)

		return nil, diags
	}

	supportsVolumeBytesVal, ok := supportsVolumeBytesAttribute.(basetypes.BoolValue)

	if !ok {
		diags.AddError(
			"Attribute Wrong Type",
			fmt.Sprintf(`supports_volume_bytes expected to be basetypes.BoolValue, was: %T`, supportsVolumeBytesAttribute))
	}

	supportsVolumeRowsAttribute, ok := attributes["supports_volume_rows"]

	if !ok {
		diags.AddError(
			"Attribute Missing",
			`supports_volume_rows is missing from object`)

		return nil, diags
	}

	supportsVolumeRowsVal, ok := supportsVolumeRowsAttribute.(basetypes.BoolValue)

	if !ok {
		diags.AddError(
			"Attribute Wrong Type",
			fmt.Sprintf(`supports_volume_rows expected to be basetypes.BoolValue, was: %T`, supportsVolumeRowsAttribute))
	}

	if diags.HasError() {
		return nil, diags
	}

	return CapabilitiesValue{
		SupportsAgentMonitor:                 supportsAgentMonitorVal,
		SupportsAgentTrajectoryMonitor:       supportsAgentTrajectoryMonitorVal,
		SupportsComparisonMonitor:            supportsComparisonMonitorVal,
		SupportsCustomSqlMonitor:             supportsCustomSqlMonitorVal,
		SupportsFieldLineage:                 supportsFieldLineageVal,
		SupportsFreshness:                    supportsFreshnessVal,
		SupportsFullQueryLanguage:            supportsFullQueryLanguageVal,
		SupportsJsonSchemaMonitor:            supportsJsonSchemaMonitorVal,
		SupportsLineage:                      supportsLineageVal,
		SupportsMetadata:                     supportsMetadataVal,
		SupportsMetricMonitorsOnUnknownTypes: supportsMetricMonitorsOnUnknownTypesVal,
		SupportsNonMetadataSizeCollection:    supportsNonMetadataSizeCollectionVal,
		SupportsQueryLogs:                    supportsQueryLogsVal,
		SupportsSchema:                       supportsSchemaVal,
		SupportsStatsMonitor:                 supportsStatsMonitorVal,
		SupportsTransform:                    supportsTransformVal,
		SupportsValidationMonitor:            supportsValidationMonitorVal,
		SupportsVolumeBytes:                  supportsVolumeBytesVal,
		SupportsVolumeRows:                   supportsVolumeRowsVal,
		state:                                attr.ValueStateKnown,
	}, diags
}

func NewCapabilitiesValueNull() CapabilitiesValue {
	return CapabilitiesValue{
		state: attr.ValueStateNull,
	}
}

func NewCapabilitiesValueUnknown() CapabilitiesValue {
	return CapabilitiesValue{
		state: attr.ValueStateUnknown,
	}
}

func NewCapabilitiesValue(attributeTypes map[string]attr.Type, attributes map[string]attr.Value) (CapabilitiesValue, diag.Diagnostics) {
	var diags diag.Diagnostics

	// Reference: https://github.com/hashicorp/terraform-plugin-framework/issues/521
	ctx := context.Background()

	for name, attributeType := range attributeTypes {
		attribute, ok := attributes[name]

		if !ok {
			diags.AddError(
				"Missing CapabilitiesValue Attribute Value",
				"While creating a CapabilitiesValue value, a missing attribute value was detected. "+
					"A CapabilitiesValue must contain values for all attributes, even if null or unknown. "+
					"This is always an issue with the provider and should be reported to the provider developers.\n\n"+
					fmt.Sprintf("CapabilitiesValue Attribute Name (%s) Expected Type: %s", name, attributeType.String()),
			)

			continue
		}

		if !attributeType.Equal(attribute.Type(ctx)) {
			diags.AddError(
				"Invalid CapabilitiesValue Attribute Type",
				"While creating a CapabilitiesValue value, an invalid attribute value was detected. "+
					"A CapabilitiesValue must use a matching attribute type for the value. "+
					"This is always an issue with the provider and should be reported to the provider developers.\n\n"+
					fmt.Sprintf("CapabilitiesValue Attribute Name (%s) Expected Type: %s\n", name, attributeType.String())+
					fmt.Sprintf("CapabilitiesValue Attribute Name (%s) Given Type: %s", name, attribute.Type(ctx)),
			)
		}
	}

	for name := range attributes {
		_, ok := attributeTypes[name]

		if !ok {
			diags.AddError(
				"Extra CapabilitiesValue Attribute Value",
				"While creating a CapabilitiesValue value, an extra attribute value was detected. "+
					"A CapabilitiesValue must not contain values beyond the expected attribute types. "+
					"This is always an issue with the provider and should be reported to the provider developers.\n\n"+
					fmt.Sprintf("Extra CapabilitiesValue Attribute Name: %s", name),
			)
		}
	}

	if diags.HasError() {
		return NewCapabilitiesValueUnknown(), diags
	}

	supportsAgentMonitorAttribute, ok := attributes["supports_agent_monitor"]

	if !ok {
		diags.AddError(
			"Attribute Missing",
			`supports_agent_monitor is missing from object`)

		return NewCapabilitiesValueUnknown(), diags
	}

	supportsAgentMonitorVal, ok := supportsAgentMonitorAttribute.(basetypes.BoolValue)

	if !ok {
		diags.AddError(
			"Attribute Wrong Type",
			fmt.Sprintf(`supports_agent_monitor expected to be basetypes.BoolValue, was: %T`, supportsAgentMonitorAttribute))
	}

	supportsAgentTrajectoryMonitorAttribute, ok := attributes["supports_agent_trajectory_monitor"]

	if !ok {
		diags.AddError(
			"Attribute Missing",
			`supports_agent_trajectory_monitor is missing from object`)

		return NewCapabilitiesValueUnknown(), diags
	}

	supportsAgentTrajectoryMonitorVal, ok := supportsAgentTrajectoryMonitorAttribute.(basetypes.BoolValue)

	if !ok {
		diags.AddError(
			"Attribute Wrong Type",
			fmt.Sprintf(`supports_agent_trajectory_monitor expected to be basetypes.BoolValue, was: %T`, supportsAgentTrajectoryMonitorAttribute))
	}

	supportsComparisonMonitorAttribute, ok := attributes["supports_comparison_monitor"]

	if !ok {
		diags.AddError(
			"Attribute Missing",
			`supports_comparison_monitor is missing from object`)

		return NewCapabilitiesValueUnknown(), diags
	}

	supportsComparisonMonitorVal, ok := supportsComparisonMonitorAttribute.(basetypes.BoolValue)

	if !ok {
		diags.AddError(
			"Attribute Wrong Type",
			fmt.Sprintf(`supports_comparison_monitor expected to be basetypes.BoolValue, was: %T`, supportsComparisonMonitorAttribute))
	}

	supportsCustomSqlMonitorAttribute, ok := attributes["supports_custom_sql_monitor"]

	if !ok {
		diags.AddError(
			"Attribute Missing",
			`supports_custom_sql_monitor is missing from object`)

		return NewCapabilitiesValueUnknown(), diags
	}

	supportsCustomSqlMonitorVal, ok := supportsCustomSqlMonitorAttribute.(basetypes.BoolValue)

	if !ok {
		diags.AddError(
			"Attribute Wrong Type",
			fmt.Sprintf(`supports_custom_sql_monitor expected to be basetypes.BoolValue, was: %T`, supportsCustomSqlMonitorAttribute))
	}

	supportsFieldLineageAttribute, ok := attributes["supports_field_lineage"]

	if !ok {
		diags.AddError(
			"Attribute Missing",
			`supports_field_lineage is missing from object`)

		return NewCapabilitiesValueUnknown(), diags
	}

	supportsFieldLineageVal, ok := supportsFieldLineageAttribute.(basetypes.BoolValue)

	if !ok {
		diags.AddError(
			"Attribute Wrong Type",
			fmt.Sprintf(`supports_field_lineage expected to be basetypes.BoolValue, was: %T`, supportsFieldLineageAttribute))
	}

	supportsFreshnessAttribute, ok := attributes["supports_freshness"]

	if !ok {
		diags.AddError(
			"Attribute Missing",
			`supports_freshness is missing from object`)

		return NewCapabilitiesValueUnknown(), diags
	}

	supportsFreshnessVal, ok := supportsFreshnessAttribute.(basetypes.BoolValue)

	if !ok {
		diags.AddError(
			"Attribute Wrong Type",
			fmt.Sprintf(`supports_freshness expected to be basetypes.BoolValue, was: %T`, supportsFreshnessAttribute))
	}

	supportsFullQueryLanguageAttribute, ok := attributes["supports_full_query_language"]

	if !ok {
		diags.AddError(
			"Attribute Missing",
			`supports_full_query_language is missing from object`)

		return NewCapabilitiesValueUnknown(), diags
	}

	supportsFullQueryLanguageVal, ok := supportsFullQueryLanguageAttribute.(basetypes.BoolValue)

	if !ok {
		diags.AddError(
			"Attribute Wrong Type",
			fmt.Sprintf(`supports_full_query_language expected to be basetypes.BoolValue, was: %T`, supportsFullQueryLanguageAttribute))
	}

	supportsJsonSchemaMonitorAttribute, ok := attributes["supports_json_schema_monitor"]

	if !ok {
		diags.AddError(
			"Attribute Missing",
			`supports_json_schema_monitor is missing from object`)

		return NewCapabilitiesValueUnknown(), diags
	}

	supportsJsonSchemaMonitorVal, ok := supportsJsonSchemaMonitorAttribute.(basetypes.BoolValue)

	if !ok {
		diags.AddError(
			"Attribute Wrong Type",
			fmt.Sprintf(`supports_json_schema_monitor expected to be basetypes.BoolValue, was: %T`, supportsJsonSchemaMonitorAttribute))
	}

	supportsLineageAttribute, ok := attributes["supports_lineage"]

	if !ok {
		diags.AddError(
			"Attribute Missing",
			`supports_lineage is missing from object`)

		return NewCapabilitiesValueUnknown(), diags
	}

	supportsLineageVal, ok := supportsLineageAttribute.(basetypes.BoolValue)

	if !ok {
		diags.AddError(
			"Attribute Wrong Type",
			fmt.Sprintf(`supports_lineage expected to be basetypes.BoolValue, was: %T`, supportsLineageAttribute))
	}

	supportsMetadataAttribute, ok := attributes["supports_metadata"]

	if !ok {
		diags.AddError(
			"Attribute Missing",
			`supports_metadata is missing from object`)

		return NewCapabilitiesValueUnknown(), diags
	}

	supportsMetadataVal, ok := supportsMetadataAttribute.(basetypes.BoolValue)

	if !ok {
		diags.AddError(
			"Attribute Wrong Type",
			fmt.Sprintf(`supports_metadata expected to be basetypes.BoolValue, was: %T`, supportsMetadataAttribute))
	}

	supportsMetricMonitorsOnUnknownTypesAttribute, ok := attributes["supports_metric_monitors_on_unknown_types"]

	if !ok {
		diags.AddError(
			"Attribute Missing",
			`supports_metric_monitors_on_unknown_types is missing from object`)

		return NewCapabilitiesValueUnknown(), diags
	}

	supportsMetricMonitorsOnUnknownTypesVal, ok := supportsMetricMonitorsOnUnknownTypesAttribute.(basetypes.BoolValue)

	if !ok {
		diags.AddError(
			"Attribute Wrong Type",
			fmt.Sprintf(`supports_metric_monitors_on_unknown_types expected to be basetypes.BoolValue, was: %T`, supportsMetricMonitorsOnUnknownTypesAttribute))
	}

	supportsNonMetadataSizeCollectionAttribute, ok := attributes["supports_non_metadata_size_collection"]

	if !ok {
		diags.AddError(
			"Attribute Missing",
			`supports_non_metadata_size_collection is missing from object`)

		return NewCapabilitiesValueUnknown(), diags
	}

	supportsNonMetadataSizeCollectionVal, ok := supportsNonMetadataSizeCollectionAttribute.(basetypes.BoolValue)

	if !ok {
		diags.AddError(
			"Attribute Wrong Type",
			fmt.Sprintf(`supports_non_metadata_size_collection expected to be basetypes.BoolValue, was: %T`, supportsNonMetadataSizeCollectionAttribute))
	}

	supportsQueryLogsAttribute, ok := attributes["supports_query_logs"]

	if !ok {
		diags.AddError(
			"Attribute Missing",
			`supports_query_logs is missing from object`)

		return NewCapabilitiesValueUnknown(), diags
	}

	supportsQueryLogsVal, ok := supportsQueryLogsAttribute.(basetypes.BoolValue)

	if !ok {
		diags.AddError(
			"Attribute Wrong Type",
			fmt.Sprintf(`supports_query_logs expected to be basetypes.BoolValue, was: %T`, supportsQueryLogsAttribute))
	}

	supportsSchemaAttribute, ok := attributes["supports_schema"]

	if !ok {
		diags.AddError(
			"Attribute Missing",
			`supports_schema is missing from object`)

		return NewCapabilitiesValueUnknown(), diags
	}

	supportsSchemaVal, ok := supportsSchemaAttribute.(basetypes.BoolValue)

	if !ok {
		diags.AddError(
			"Attribute Wrong Type",
			fmt.Sprintf(`supports_schema expected to be basetypes.BoolValue, was: %T`, supportsSchemaAttribute))
	}

	supportsStatsMonitorAttribute, ok := attributes["supports_stats_monitor"]

	if !ok {
		diags.AddError(
			"Attribute Missing",
			`supports_stats_monitor is missing from object`)

		return NewCapabilitiesValueUnknown(), diags
	}

	supportsStatsMonitorVal, ok := supportsStatsMonitorAttribute.(basetypes.BoolValue)

	if !ok {
		diags.AddError(
			"Attribute Wrong Type",
			fmt.Sprintf(`supports_stats_monitor expected to be basetypes.BoolValue, was: %T`, supportsStatsMonitorAttribute))
	}

	supportsTransformAttribute, ok := attributes["supports_transform"]

	if !ok {
		diags.AddError(
			"Attribute Missing",
			`supports_transform is missing from object`)

		return NewCapabilitiesValueUnknown(), diags
	}

	supportsTransformVal, ok := supportsTransformAttribute.(basetypes.BoolValue)

	if !ok {
		diags.AddError(
			"Attribute Wrong Type",
			fmt.Sprintf(`supports_transform expected to be basetypes.BoolValue, was: %T`, supportsTransformAttribute))
	}

	supportsValidationMonitorAttribute, ok := attributes["supports_validation_monitor"]

	if !ok {
		diags.AddError(
			"Attribute Missing",
			`supports_validation_monitor is missing from object`)

		return NewCapabilitiesValueUnknown(), diags
	}

	supportsValidationMonitorVal, ok := supportsValidationMonitorAttribute.(basetypes.BoolValue)

	if !ok {
		diags.AddError(
			"Attribute Wrong Type",
			fmt.Sprintf(`supports_validation_monitor expected to be basetypes.BoolValue, was: %T`, supportsValidationMonitorAttribute))
	}

	supportsVolumeBytesAttribute, ok := attributes["supports_volume_bytes"]

	if !ok {
		diags.AddError(
			"Attribute Missing",
			`supports_volume_bytes is missing from object`)

		return NewCapabilitiesValueUnknown(), diags
	}

	supportsVolumeBytesVal, ok := supportsVolumeBytesAttribute.(basetypes.BoolValue)

	if !ok {
		diags.AddError(
			"Attribute Wrong Type",
			fmt.Sprintf(`supports_volume_bytes expected to be basetypes.BoolValue, was: %T`, supportsVolumeBytesAttribute))
	}

	supportsVolumeRowsAttribute, ok := attributes["supports_volume_rows"]

	if !ok {
		diags.AddError(
			"Attribute Missing",
			`supports_volume_rows is missing from object`)

		return NewCapabilitiesValueUnknown(), diags
	}

	supportsVolumeRowsVal, ok := supportsVolumeRowsAttribute.(basetypes.BoolValue)

	if !ok {
		diags.AddError(
			"Attribute Wrong Type",
			fmt.Sprintf(`supports_volume_rows expected to be basetypes.BoolValue, was: %T`, supportsVolumeRowsAttribute))
	}

	if diags.HasError() {
		return NewCapabilitiesValueUnknown(), diags
	}

	return CapabilitiesValue{
		SupportsAgentMonitor:                 supportsAgentMonitorVal,
		SupportsAgentTrajectoryMonitor:       supportsAgentTrajectoryMonitorVal,
		SupportsComparisonMonitor:            supportsComparisonMonitorVal,
		SupportsCustomSqlMonitor:             supportsCustomSqlMonitorVal,
		SupportsFieldLineage:                 supportsFieldLineageVal,
		SupportsFreshness:                    supportsFreshnessVal,
		SupportsFullQueryLanguage:            supportsFullQueryLanguageVal,
		SupportsJsonSchemaMonitor:            supportsJsonSchemaMonitorVal,
		SupportsLineage:                      supportsLineageVal,
		SupportsMetadata:                     supportsMetadataVal,
		SupportsMetricMonitorsOnUnknownTypes: supportsMetricMonitorsOnUnknownTypesVal,
		SupportsNonMetadataSizeCollection:    supportsNonMetadataSizeCollectionVal,
		SupportsQueryLogs:                    supportsQueryLogsVal,
		SupportsSchema:                       supportsSchemaVal,
		SupportsStatsMonitor:                 supportsStatsMonitorVal,
		SupportsTransform:                    supportsTransformVal,
		SupportsValidationMonitor:            supportsValidationMonitorVal,
		SupportsVolumeBytes:                  supportsVolumeBytesVal,
		SupportsVolumeRows:                   supportsVolumeRowsVal,
		state:                                attr.ValueStateKnown,
	}, diags
}

func NewCapabilitiesValueMust(attributeTypes map[string]attr.Type, attributes map[string]attr.Value) CapabilitiesValue {
	object, diags := NewCapabilitiesValue(attributeTypes, attributes)

	if diags.HasError() {
		// This could potentially be added to the diag package.
		diagsStrings := make([]string, 0, len(diags))

		for _, diagnostic := range diags {
			diagsStrings = append(diagsStrings, fmt.Sprintf(
				"%s | %s | %s",
				diagnostic.Severity(),
				diagnostic.Summary(),
				diagnostic.Detail()))
		}

		panic("NewCapabilitiesValueMust received error(s): " + strings.Join(diagsStrings, "\n"))
	}

	return object
}

func (t CapabilitiesType) ValueFromTerraform(ctx context.Context, in tftypes.Value) (attr.Value, error) {
	if in.Type() == nil {
		return NewCapabilitiesValueNull(), nil
	}

	if !in.Type().Equal(t.TerraformType(ctx)) {
		return nil, fmt.Errorf("expected %s, got %s", t.TerraformType(ctx), in.Type())
	}

	if !in.IsKnown() {
		return NewCapabilitiesValueUnknown(), nil
	}

	if in.IsNull() {
		return NewCapabilitiesValueNull(), nil
	}

	attributes := map[string]attr.Value{}

	val := map[string]tftypes.Value{}

	err := in.As(&val)

	if err != nil {
		return nil, err
	}

	for k, v := range val {
		a, err := t.AttrTypes[k].ValueFromTerraform(ctx, v)

		if err != nil {
			return nil, err
		}

		attributes[k] = a
	}

	return NewCapabilitiesValueMust(CapabilitiesValue{}.AttributeTypes(ctx), attributes), nil
}

func (t CapabilitiesType) ValueType(ctx context.Context) attr.Value {
	return CapabilitiesValue{}
}

var _ basetypes.ObjectValuable = CapabilitiesValue{}

type CapabilitiesValue struct {
	SupportsAgentMonitor                 basetypes.BoolValue `tfsdk:"supports_agent_monitor"`
	SupportsAgentTrajectoryMonitor       basetypes.BoolValue `tfsdk:"supports_agent_trajectory_monitor"`
	SupportsComparisonMonitor            basetypes.BoolValue `tfsdk:"supports_comparison_monitor"`
	SupportsCustomSqlMonitor             basetypes.BoolValue `tfsdk:"supports_custom_sql_monitor"`
	SupportsFieldLineage                 basetypes.BoolValue `tfsdk:"supports_field_lineage"`
	SupportsFreshness                    basetypes.BoolValue `tfsdk:"supports_freshness"`
	SupportsFullQueryLanguage            basetypes.BoolValue `tfsdk:"supports_full_query_language"`
	SupportsJsonSchemaMonitor            basetypes.BoolValue `tfsdk:"supports_json_schema_monitor"`
	SupportsLineage                      basetypes.BoolValue `tfsdk:"supports_lineage"`
	SupportsMetadata                     basetypes.BoolValue `tfsdk:"supports_metadata"`
	SupportsMetricMonitorsOnUnknownTypes basetypes.BoolValue `tfsdk:"supports_metric_monitors_on_unknown_types"`
	SupportsNonMetadataSizeCollection    basetypes.BoolValue `tfsdk:"supports_non_metadata_size_collection"`
	SupportsQueryLogs                    basetypes.BoolValue `tfsdk:"supports_query_logs"`
	SupportsSchema                       basetypes.BoolValue `tfsdk:"supports_schema"`
	SupportsStatsMonitor                 basetypes.BoolValue `tfsdk:"supports_stats_monitor"`
	SupportsTransform                    basetypes.BoolValue `tfsdk:"supports_transform"`
	SupportsValidationMonitor            basetypes.BoolValue `tfsdk:"supports_validation_monitor"`
	SupportsVolumeBytes                  basetypes.BoolValue `tfsdk:"supports_volume_bytes"`
	SupportsVolumeRows                   basetypes.BoolValue `tfsdk:"supports_volume_rows"`
	state                                attr.ValueState
}

func (v CapabilitiesValue) ToTerraformValue(ctx context.Context) (tftypes.Value, error) {
	attrTypes := make(map[string]tftypes.Type, 19)

	var val tftypes.Value
	var err error

	attrTypes["supports_agent_monitor"] = basetypes.BoolType{}.TerraformType(ctx)
	attrTypes["supports_agent_trajectory_monitor"] = basetypes.BoolType{}.TerraformType(ctx)
	attrTypes["supports_comparison_monitor"] = basetypes.BoolType{}.TerraformType(ctx)
	attrTypes["supports_custom_sql_monitor"] = basetypes.BoolType{}.TerraformType(ctx)
	attrTypes["supports_field_lineage"] = basetypes.BoolType{}.TerraformType(ctx)
	attrTypes["supports_freshness"] = basetypes.BoolType{}.TerraformType(ctx)
	attrTypes["supports_full_query_language"] = basetypes.BoolType{}.TerraformType(ctx)
	attrTypes["supports_json_schema_monitor"] = basetypes.BoolType{}.TerraformType(ctx)
	attrTypes["supports_lineage"] = basetypes.BoolType{}.TerraformType(ctx)
	attrTypes["supports_metadata"] = basetypes.BoolType{}.TerraformType(ctx)
	attrTypes["supports_metric_monitors_on_unknown_types"] = basetypes.BoolType{}.TerraformType(ctx)
	attrTypes["supports_non_metadata_size_collection"] = basetypes.BoolType{}.TerraformType(ctx)
	attrTypes["supports_query_logs"] = basetypes.BoolType{}.TerraformType(ctx)
	attrTypes["supports_schema"] = basetypes.BoolType{}.TerraformType(ctx)
	attrTypes["supports_stats_monitor"] = basetypes.BoolType{}.TerraformType(ctx)
	attrTypes["supports_transform"] = basetypes.BoolType{}.TerraformType(ctx)
	attrTypes["supports_validation_monitor"] = basetypes.BoolType{}.TerraformType(ctx)
	attrTypes["supports_volume_bytes"] = basetypes.BoolType{}.TerraformType(ctx)
	attrTypes["supports_volume_rows"] = basetypes.BoolType{}.TerraformType(ctx)

	objectType := tftypes.Object{AttributeTypes: attrTypes}

	switch v.state {
	case attr.ValueStateKnown:
		vals := make(map[string]tftypes.Value, 19)

		val, err = v.SupportsAgentMonitor.ToTerraformValue(ctx)

		if err != nil {
			return tftypes.NewValue(objectType, tftypes.UnknownValue), err
		}

		vals["supports_agent_monitor"] = val

		val, err = v.SupportsAgentTrajectoryMonitor.ToTerraformValue(ctx)

		if err != nil {
			return tftypes.NewValue(objectType, tftypes.UnknownValue), err
		}

		vals["supports_agent_trajectory_monitor"] = val

		val, err = v.SupportsComparisonMonitor.ToTerraformValue(ctx)

		if err != nil {
			return tftypes.NewValue(objectType, tftypes.UnknownValue), err
		}

		vals["supports_comparison_monitor"] = val

		val, err = v.SupportsCustomSqlMonitor.ToTerraformValue(ctx)

		if err != nil {
			return tftypes.NewValue(objectType, tftypes.UnknownValue), err
		}

		vals["supports_custom_sql_monitor"] = val

		val, err = v.SupportsFieldLineage.ToTerraformValue(ctx)

		if err != nil {
			return tftypes.NewValue(objectType, tftypes.UnknownValue), err
		}

		vals["supports_field_lineage"] = val

		val, err = v.SupportsFreshness.ToTerraformValue(ctx)

		if err != nil {
			return tftypes.NewValue(objectType, tftypes.UnknownValue), err
		}

		vals["supports_freshness"] = val

		val, err = v.SupportsFullQueryLanguage.ToTerraformValue(ctx)

		if err != nil {
			return tftypes.NewValue(objectType, tftypes.UnknownValue), err
		}

		vals["supports_full_query_language"] = val

		val, err = v.SupportsJsonSchemaMonitor.ToTerraformValue(ctx)

		if err != nil {
			return tftypes.NewValue(objectType, tftypes.UnknownValue), err
		}

		vals["supports_json_schema_monitor"] = val

		val, err = v.SupportsLineage.ToTerraformValue(ctx)

		if err != nil {
			return tftypes.NewValue(objectType, tftypes.UnknownValue), err
		}

		vals["supports_lineage"] = val

		val, err = v.SupportsMetadata.ToTerraformValue(ctx)

		if err != nil {
			return tftypes.NewValue(objectType, tftypes.UnknownValue), err
		}

		vals["supports_metadata"] = val

		val, err = v.SupportsMetricMonitorsOnUnknownTypes.ToTerraformValue(ctx)

		if err != nil {
			return tftypes.NewValue(objectType, tftypes.UnknownValue), err
		}

		vals["supports_metric_monitors_on_unknown_types"] = val

		val, err = v.SupportsNonMetadataSizeCollection.ToTerraformValue(ctx)

		if err != nil {
			return tftypes.NewValue(objectType, tftypes.UnknownValue), err
		}

		vals["supports_non_metadata_size_collection"] = val

		val, err = v.SupportsQueryLogs.ToTerraformValue(ctx)

		if err != nil {
			return tftypes.NewValue(objectType, tftypes.UnknownValue), err
		}

		vals["supports_query_logs"] = val

		val, err = v.SupportsSchema.ToTerraformValue(ctx)

		if err != nil {
			return tftypes.NewValue(objectType, tftypes.UnknownValue), err
		}

		vals["supports_schema"] = val

		val, err = v.SupportsStatsMonitor.ToTerraformValue(ctx)

		if err != nil {
			return tftypes.NewValue(objectType, tftypes.UnknownValue), err
		}

		vals["supports_stats_monitor"] = val

		val, err = v.SupportsTransform.ToTerraformValue(ctx)

		if err != nil {
			return tftypes.NewValue(objectType, tftypes.UnknownValue), err
		}

		vals["supports_transform"] = val

		val, err = v.SupportsValidationMonitor.ToTerraformValue(ctx)

		if err != nil {
			return tftypes.NewValue(objectType, tftypes.UnknownValue), err
		}

		vals["supports_validation_monitor"] = val

		val, err = v.SupportsVolumeBytes.ToTerraformValue(ctx)

		if err != nil {
			return tftypes.NewValue(objectType, tftypes.UnknownValue), err
		}

		vals["supports_volume_bytes"] = val

		val, err = v.SupportsVolumeRows.ToTerraformValue(ctx)

		if err != nil {
			return tftypes.NewValue(objectType, tftypes.UnknownValue), err
		}

		vals["supports_volume_rows"] = val

		if err := tftypes.ValidateValue(objectType, vals); err != nil {
			return tftypes.NewValue(objectType, tftypes.UnknownValue), err
		}

		return tftypes.NewValue(objectType, vals), nil
	case attr.ValueStateNull:
		return tftypes.NewValue(objectType, nil), nil
	case attr.ValueStateUnknown:
		return tftypes.NewValue(objectType, tftypes.UnknownValue), nil
	default:
		panic(fmt.Sprintf("unhandled Object state in ToTerraformValue: %s", v.state))
	}
}

func (v CapabilitiesValue) IsNull() bool {
	return v.state == attr.ValueStateNull
}

func (v CapabilitiesValue) IsUnknown() bool {
	return v.state == attr.ValueStateUnknown
}

func (v CapabilitiesValue) String() string {
	return "CapabilitiesValue"
}

func (v CapabilitiesValue) ToObjectValue(ctx context.Context) (basetypes.ObjectValue, diag.Diagnostics) {
	var diags diag.Diagnostics

	attributeTypes := map[string]attr.Type{
		"supports_agent_monitor":                    basetypes.BoolType{},
		"supports_agent_trajectory_monitor":         basetypes.BoolType{},
		"supports_comparison_monitor":               basetypes.BoolType{},
		"supports_custom_sql_monitor":               basetypes.BoolType{},
		"supports_field_lineage":                    basetypes.BoolType{},
		"supports_freshness":                        basetypes.BoolType{},
		"supports_full_query_language":              basetypes.BoolType{},
		"supports_json_schema_monitor":              basetypes.BoolType{},
		"supports_lineage":                          basetypes.BoolType{},
		"supports_metadata":                         basetypes.BoolType{},
		"supports_metric_monitors_on_unknown_types": basetypes.BoolType{},
		"supports_non_metadata_size_collection":     basetypes.BoolType{},
		"supports_query_logs":                       basetypes.BoolType{},
		"supports_schema":                           basetypes.BoolType{},
		"supports_stats_monitor":                    basetypes.BoolType{},
		"supports_transform":                        basetypes.BoolType{},
		"supports_validation_monitor":               basetypes.BoolType{},
		"supports_volume_bytes":                     basetypes.BoolType{},
		"supports_volume_rows":                      basetypes.BoolType{},
	}

	if v.IsNull() {
		return types.ObjectNull(attributeTypes), diags
	}

	if v.IsUnknown() {
		return types.ObjectUnknown(attributeTypes), diags
	}

	objVal, diags := types.ObjectValue(
		attributeTypes,
		map[string]attr.Value{
			"supports_agent_monitor":                    v.SupportsAgentMonitor,
			"supports_agent_trajectory_monitor":         v.SupportsAgentTrajectoryMonitor,
			"supports_comparison_monitor":               v.SupportsComparisonMonitor,
			"supports_custom_sql_monitor":               v.SupportsCustomSqlMonitor,
			"supports_field_lineage":                    v.SupportsFieldLineage,
			"supports_freshness":                        v.SupportsFreshness,
			"supports_full_query_language":              v.SupportsFullQueryLanguage,
			"supports_json_schema_monitor":              v.SupportsJsonSchemaMonitor,
			"supports_lineage":                          v.SupportsLineage,
			"supports_metadata":                         v.SupportsMetadata,
			"supports_metric_monitors_on_unknown_types": v.SupportsMetricMonitorsOnUnknownTypes,
			"supports_non_metadata_size_collection":     v.SupportsNonMetadataSizeCollection,
			"supports_query_logs":                       v.SupportsQueryLogs,
			"supports_schema":                           v.SupportsSchema,
			"supports_stats_monitor":                    v.SupportsStatsMonitor,
			"supports_transform":                        v.SupportsTransform,
			"supports_validation_monitor":               v.SupportsValidationMonitor,
			"supports_volume_bytes":                     v.SupportsVolumeBytes,
			"supports_volume_rows":                      v.SupportsVolumeRows,
		})

	return objVal, diags
}

func (v CapabilitiesValue) Equal(o attr.Value) bool {
	other, ok := o.(CapabilitiesValue)

	if !ok {
		return false
	}

	if v.state != other.state {
		return false
	}

	if v.state != attr.ValueStateKnown {
		return true
	}

	if !v.SupportsAgentMonitor.Equal(other.SupportsAgentMonitor) {
		return false
	}

	if !v.SupportsAgentTrajectoryMonitor.Equal(other.SupportsAgentTrajectoryMonitor) {
		return false
	}

	if !v.SupportsComparisonMonitor.Equal(other.SupportsComparisonMonitor) {
		return false
	}

	if !v.SupportsCustomSqlMonitor.Equal(other.SupportsCustomSqlMonitor) {
		return false
	}

	if !v.SupportsFieldLineage.Equal(other.SupportsFieldLineage) {
		return false
	}

	if !v.SupportsFreshness.Equal(other.SupportsFreshness) {
		return false
	}

	if !v.SupportsFullQueryLanguage.Equal(other.SupportsFullQueryLanguage) {
		return false
	}

	if !v.SupportsJsonSchemaMonitor.Equal(other.SupportsJsonSchemaMonitor) {
		return false
	}

	if !v.SupportsLineage.Equal(other.SupportsLineage) {
		return false
	}

	if !v.SupportsMetadata.Equal(other.SupportsMetadata) {
		return false
	}

	if !v.SupportsMetricMonitorsOnUnknownTypes.Equal(other.SupportsMetricMonitorsOnUnknownTypes) {
		return false
	}

	if !v.SupportsNonMetadataSizeCollection.Equal(other.SupportsNonMetadataSizeCollection) {
		return false
	}

	if !v.SupportsQueryLogs.Equal(other.SupportsQueryLogs) {
		return false
	}

	if !v.SupportsSchema.Equal(other.SupportsSchema) {
		return false
	}

	if !v.SupportsStatsMonitor.Equal(other.SupportsStatsMonitor) {
		return false
	}

	if !v.SupportsTransform.Equal(other.SupportsTransform) {
		return false
	}

	if !v.SupportsValidationMonitor.Equal(other.SupportsValidationMonitor) {
		return false
	}

	if !v.SupportsVolumeBytes.Equal(other.SupportsVolumeBytes) {
		return false
	}

	if !v.SupportsVolumeRows.Equal(other.SupportsVolumeRows) {
		return false
	}

	return true
}

func (v CapabilitiesValue) Type(ctx context.Context) attr.Type {
	return CapabilitiesType{
		basetypes.ObjectType{
			AttrTypes: v.AttributeTypes(ctx),
		},
	}
}

func (v CapabilitiesValue) AttributeTypes(ctx context.Context) map[string]attr.Type {
	return map[string]attr.Type{
		"supports_agent_monitor":                    basetypes.BoolType{},
		"supports_agent_trajectory_monitor":         basetypes.BoolType{},
		"supports_comparison_monitor":               basetypes.BoolType{},
		"supports_custom_sql_monitor":               basetypes.BoolType{},
		"supports_field_lineage":                    basetypes.BoolType{},
		"supports_freshness":                        basetypes.BoolType{},
		"supports_full_query_language":              basetypes.BoolType{},
		"supports_json_schema_monitor":              basetypes.BoolType{},
		"supports_lineage":                          basetypes.BoolType{},
		"supports_metadata":                         basetypes.BoolType{},
		"supports_metric_monitors_on_unknown_types": basetypes.BoolType{},
		"supports_non_metadata_size_collection":     basetypes.BoolType{},
		"supports_query_logs":                       basetypes.BoolType{},
		"supports_schema":                           basetypes.BoolType{},
		"supports_stats_monitor":                    basetypes.BoolType{},
		"supports_transform":                        basetypes.BoolType{},
		"supports_validation_monitor":               basetypes.BoolType{},
		"supports_volume_bytes":                     basetypes.BoolType{},
		"supports_volume_rows":                      basetypes.BoolType{},
	}
}

var _ basetypes.ObjectTypable = TerminologyType{}

type TerminologyType struct {
	basetypes.ObjectType
}

func (t TerminologyType) Equal(o attr.Type) bool {
	other, ok := o.(TerminologyType)

	if !ok {
		return false
	}

	return t.ObjectType.Equal(other.ObjectType)
}

func (t TerminologyType) String() string {
	return "TerminologyType"
}

func (t TerminologyType) ValueFromObject(ctx context.Context, in basetypes.ObjectValue) (basetypes.ObjectValuable, diag.Diagnostics) {
	var diags diag.Diagnostics

	attributes := in.Attributes()

	groupAttribute, ok := attributes["group"]

	if !ok {
		diags.AddError(
			"Attribute Missing",
			`group is missing from object`)

		return nil, diags
	}

	groupVal, ok := groupAttribute.(basetypes.StringValue)

	if !ok {
		diags.AddError(
			"Attribute Wrong Type",
			fmt.Sprintf(`group expected to be basetypes.StringValue, was: %T`, groupAttribute))
	}

	jobAttribute, ok := attributes["job"]

	if !ok {
		diags.AddError(
			"Attribute Missing",
			`job is missing from object`)

		return nil, diags
	}

	jobVal, ok := jobAttribute.(basetypes.StringValue)

	if !ok {
		diags.AddError(
			"Attribute Wrong Type",
			fmt.Sprintf(`job expected to be basetypes.StringValue, was: %T`, jobAttribute))
	}

	taskAttribute, ok := attributes["task"]

	if !ok {
		diags.AddError(
			"Attribute Missing",
			`task is missing from object`)

		return nil, diags
	}

	taskVal, ok := taskAttribute.(basetypes.StringValue)

	if !ok {
		diags.AddError(
			"Attribute Wrong Type",
			fmt.Sprintf(`task expected to be basetypes.StringValue, was: %T`, taskAttribute))
	}

	if diags.HasError() {
		return nil, diags
	}

	return TerminologyValue{
		Group: groupVal,
		Job:   jobVal,
		Task:  taskVal,
		state: attr.ValueStateKnown,
	}, diags
}

func NewTerminologyValueNull() TerminologyValue {
	return TerminologyValue{
		state: attr.ValueStateNull,
	}
}

func NewTerminologyValueUnknown() TerminologyValue {
	return TerminologyValue{
		state: attr.ValueStateUnknown,
	}
}

func NewTerminologyValue(attributeTypes map[string]attr.Type, attributes map[string]attr.Value) (TerminologyValue, diag.Diagnostics) {
	var diags diag.Diagnostics

	// Reference: https://github.com/hashicorp/terraform-plugin-framework/issues/521
	ctx := context.Background()

	for name, attributeType := range attributeTypes {
		attribute, ok := attributes[name]

		if !ok {
			diags.AddError(
				"Missing TerminologyValue Attribute Value",
				"While creating a TerminologyValue value, a missing attribute value was detected. "+
					"A TerminologyValue must contain values for all attributes, even if null or unknown. "+
					"This is always an issue with the provider and should be reported to the provider developers.\n\n"+
					fmt.Sprintf("TerminologyValue Attribute Name (%s) Expected Type: %s", name, attributeType.String()),
			)

			continue
		}

		if !attributeType.Equal(attribute.Type(ctx)) {
			diags.AddError(
				"Invalid TerminologyValue Attribute Type",
				"While creating a TerminologyValue value, an invalid attribute value was detected. "+
					"A TerminologyValue must use a matching attribute type for the value. "+
					"This is always an issue with the provider and should be reported to the provider developers.\n\n"+
					fmt.Sprintf("TerminologyValue Attribute Name (%s) Expected Type: %s\n", name, attributeType.String())+
					fmt.Sprintf("TerminologyValue Attribute Name (%s) Given Type: %s", name, attribute.Type(ctx)),
			)
		}
	}

	for name := range attributes {
		_, ok := attributeTypes[name]

		if !ok {
			diags.AddError(
				"Extra TerminologyValue Attribute Value",
				"While creating a TerminologyValue value, an extra attribute value was detected. "+
					"A TerminologyValue must not contain values beyond the expected attribute types. "+
					"This is always an issue with the provider and should be reported to the provider developers.\n\n"+
					fmt.Sprintf("Extra TerminologyValue Attribute Name: %s", name),
			)
		}
	}

	if diags.HasError() {
		return NewTerminologyValueUnknown(), diags
	}

	groupAttribute, ok := attributes["group"]

	if !ok {
		diags.AddError(
			"Attribute Missing",
			`group is missing from object`)

		return NewTerminologyValueUnknown(), diags
	}

	groupVal, ok := groupAttribute.(basetypes.StringValue)

	if !ok {
		diags.AddError(
			"Attribute Wrong Type",
			fmt.Sprintf(`group expected to be basetypes.StringValue, was: %T`, groupAttribute))
	}

	jobAttribute, ok := attributes["job"]

	if !ok {
		diags.AddError(
			"Attribute Missing",
			`job is missing from object`)

		return NewTerminologyValueUnknown(), diags
	}

	jobVal, ok := jobAttribute.(basetypes.StringValue)

	if !ok {
		diags.AddError(
			"Attribute Wrong Type",
			fmt.Sprintf(`job expected to be basetypes.StringValue, was: %T`, jobAttribute))
	}

	taskAttribute, ok := attributes["task"]

	if !ok {
		diags.AddError(
			"Attribute Missing",
			`task is missing from object`)

		return NewTerminologyValueUnknown(), diags
	}

	taskVal, ok := taskAttribute.(basetypes.StringValue)

	if !ok {
		diags.AddError(
			"Attribute Wrong Type",
			fmt.Sprintf(`task expected to be basetypes.StringValue, was: %T`, taskAttribute))
	}

	if diags.HasError() {
		return NewTerminologyValueUnknown(), diags
	}

	return TerminologyValue{
		Group: groupVal,
		Job:   jobVal,
		Task:  taskVal,
		state: attr.ValueStateKnown,
	}, diags
}

func NewTerminologyValueMust(attributeTypes map[string]attr.Type, attributes map[string]attr.Value) TerminologyValue {
	object, diags := NewTerminologyValue(attributeTypes, attributes)

	if diags.HasError() {
		// This could potentially be added to the diag package.
		diagsStrings := make([]string, 0, len(diags))

		for _, diagnostic := range diags {
			diagsStrings = append(diagsStrings, fmt.Sprintf(
				"%s | %s | %s",
				diagnostic.Severity(),
				diagnostic.Summary(),
				diagnostic.Detail()))
		}

		panic("NewTerminologyValueMust received error(s): " + strings.Join(diagsStrings, "\n"))
	}

	return object
}

func (t TerminologyType) ValueFromTerraform(ctx context.Context, in tftypes.Value) (attr.Value, error) {
	if in.Type() == nil {
		return NewTerminologyValueNull(), nil
	}

	if !in.Type().Equal(t.TerraformType(ctx)) {
		return nil, fmt.Errorf("expected %s, got %s", t.TerraformType(ctx), in.Type())
	}

	if !in.IsKnown() {
		return NewTerminologyValueUnknown(), nil
	}

	if in.IsNull() {
		return NewTerminologyValueNull(), nil
	}

	attributes := map[string]attr.Value{}

	val := map[string]tftypes.Value{}

	err := in.As(&val)

	if err != nil {
		return nil, err
	}

	for k, v := range val {
		a, err := t.AttrTypes[k].ValueFromTerraform(ctx, v)

		if err != nil {
			return nil, err
		}

		attributes[k] = a
	}

	return NewTerminologyValueMust(TerminologyValue{}.AttributeTypes(ctx), attributes), nil
}

func (t TerminologyType) ValueType(ctx context.Context) attr.Value {
	return TerminologyValue{}
}

var _ basetypes.ObjectValuable = TerminologyValue{}

type TerminologyValue struct {
	Group basetypes.StringValue `tfsdk:"group"`
	Job   basetypes.StringValue `tfsdk:"job"`
	Task  basetypes.StringValue `tfsdk:"task"`
	state attr.ValueState
}

func (v TerminologyValue) ToTerraformValue(ctx context.Context) (tftypes.Value, error) {
	attrTypes := make(map[string]tftypes.Type, 3)

	var val tftypes.Value
	var err error

	attrTypes["group"] = basetypes.StringType{}.TerraformType(ctx)
	attrTypes["job"] = basetypes.StringType{}.TerraformType(ctx)
	attrTypes["task"] = basetypes.StringType{}.TerraformType(ctx)

	objectType := tftypes.Object{AttributeTypes: attrTypes}

	switch v.state {
	case attr.ValueStateKnown:
		vals := make(map[string]tftypes.Value, 3)

		val, err = v.Group.ToTerraformValue(ctx)

		if err != nil {
			return tftypes.NewValue(objectType, tftypes.UnknownValue), err
		}

		vals["group"] = val

		val, err = v.Job.ToTerraformValue(ctx)

		if err != nil {
			return tftypes.NewValue(objectType, tftypes.UnknownValue), err
		}

		vals["job"] = val

		val, err = v.Task.ToTerraformValue(ctx)

		if err != nil {
			return tftypes.NewValue(objectType, tftypes.UnknownValue), err
		}

		vals["task"] = val

		if err := tftypes.ValidateValue(objectType, vals); err != nil {
			return tftypes.NewValue(objectType, tftypes.UnknownValue), err
		}

		return tftypes.NewValue(objectType, vals), nil
	case attr.ValueStateNull:
		return tftypes.NewValue(objectType, nil), nil
	case attr.ValueStateUnknown:
		return tftypes.NewValue(objectType, tftypes.UnknownValue), nil
	default:
		panic(fmt.Sprintf("unhandled Object state in ToTerraformValue: %s", v.state))
	}
}

func (v TerminologyValue) IsNull() bool {
	return v.state == attr.ValueStateNull
}

func (v TerminologyValue) IsUnknown() bool {
	return v.state == attr.ValueStateUnknown
}

func (v TerminologyValue) String() string {
	return "TerminologyValue"
}

func (v TerminologyValue) ToObjectValue(ctx context.Context) (basetypes.ObjectValue, diag.Diagnostics) {
	var diags diag.Diagnostics

	attributeTypes := map[string]attr.Type{
		"group": basetypes.StringType{},
		"job":   basetypes.StringType{},
		"task":  basetypes.StringType{},
	}

	if v.IsNull() {
		return types.ObjectNull(attributeTypes), diags
	}

	if v.IsUnknown() {
		return types.ObjectUnknown(attributeTypes), diags
	}

	objVal, diags := types.ObjectValue(
		attributeTypes,
		map[string]attr.Value{
			"group": v.Group,
			"job":   v.Job,
			"task":  v.Task,
		})

	return objVal, diags
}

func (v TerminologyValue) Equal(o attr.Value) bool {
	other, ok := o.(TerminologyValue)

	if !ok {
		return false
	}

	if v.state != other.state {
		return false
	}

	if v.state != attr.ValueStateKnown {
		return true
	}

	if !v.Group.Equal(other.Group) {
		return false
	}

	if !v.Job.Equal(other.Job) {
		return false
	}

	if !v.Task.Equal(other.Task) {
		return false
	}

	return true
}

func (v TerminologyValue) Type(ctx context.Context) attr.Type {
	return TerminologyType{
		basetypes.ObjectType{
			AttrTypes: v.AttributeTypes(ctx),
		},
	}
}

func (v TerminologyValue) AttributeTypes(ctx context.Context) map[string]attr.Type {
	return map[string]attr.Type{
		"group": basetypes.StringType{},
		"job":   basetypes.StringType{},
		"task":  basetypes.StringType{},
	}
}
