// Code generated by terraform-plugin-framework-generator DO NOT EDIT.

package datasource_looker_credentials

import (
	"context"
	"github.com/hashicorp/terraform-plugin-framework/types"

	"github.com/hashicorp/terraform-plugin-framework/datasource/schema"
)

func LookerCredentialsDataSourceSchema(ctx context.Context) schema.Schema {
	return schema.Schema{
		Attributes: map[string]schema.Attribute{
			"api_client_id": schema.StringAttribute{
				Computed:            true,
				Description:         "Client ID of the Looker API key.",
				MarkdownDescription: "Client ID of the Looker API key.",
			},
			"base_url": schema.StringAttribute{
				Computed:            true,
				Description:         "URL of the Looker API, such as https://acme.cloud.looker.com.",
				MarkdownDescription: "URL of the Looker API, such as https://acme.cloud.looker.com.",
			},
			"connection_type": schema.StringAttribute{
				Computed:            true,
				Description:         "The connection type the credentials are for, such as `snowflake`. Fixed once created.",
				MarkdownDescription: "The connection type the credentials are for, such as `snowflake`. Fixed once created.",
			},
			"created_time": schema.StringAttribute{
				Computed:            true,
				Description:         "When the credentials were created.",
				MarkdownDescription: "When the credentials were created.",
			},
			"credentials_id": schema.StringAttribute{
				Required: true,
			},
			"id": schema.StringAttribute{
				Computed:            true,
				Description:         "Unique identifier of the credentials.",
				MarkdownDescription: "Unique identifier of the credentials.",
			},
			"storage_type": schema.StringAttribute{
				Computed:            true,
				Description:         "Where the secret lives. Fixed once created.",
				MarkdownDescription: "Where the secret lives. Fixed once created.",
			},
			"verify_ssl": schema.BoolAttribute{
				Computed:            true,
				Description:         "Whether to verify Looker's TLS certificate. Verified when left out. Null unless set.",
				MarkdownDescription: "Whether to verify Looker's TLS certificate. Verified when left out. Null unless set.",
			},
		},
	}
}

type LookerCredentialsModel struct {
	ApiClientId    types.String `tfsdk:"api_client_id"`
	BaseUrl        types.String `tfsdk:"base_url"`
	ConnectionType types.String `tfsdk:"connection_type"`
	CreatedTime    types.String `tfsdk:"created_time"`
	CredentialsId  types.String `tfsdk:"credentials_id"`
	Id             types.String `tfsdk:"id"`
	StorageType    types.String `tfsdk:"storage_type"`
	VerifySsl      types.Bool   `tfsdk:"verify_ssl"`
}
