// Code generated by terraform-plugin-framework-generator DO NOT EDIT.

package datasource_tableau_credentials

import (
	"context"
	"github.com/hashicorp/terraform-plugin-framework/types"

	"github.com/hashicorp/terraform-plugin-framework/datasource/schema"
)

func TableauCredentialsDataSourceSchema(ctx context.Context) schema.Schema {
	return schema.Schema{
		Attributes: map[string]schema.Attribute{
			"connected_app_client_id": schema.StringAttribute{
				Computed:            true,
				Description:         "Client ID of the connected app. Null unless the credentials use one.",
				MarkdownDescription: "Client ID of the connected app. Null unless the credentials use one.",
			},
			"connected_app_secret_id": schema.StringAttribute{
				Computed:            true,
				Description:         "ID of the connected app's secret. Null unless the credentials use one.",
				MarkdownDescription: "ID of the connected app's secret. Null unless the credentials use one.",
			},
			"connection_type": schema.StringAttribute{
				Computed:            true,
				Description:         "The connection type the credentials are for, such as `snowflake`. Fixed once created.",
				MarkdownDescription: "The connection type the credentials are for, such as `snowflake`. Fixed once created.",
			},
			"created_time": schema.StringAttribute{
				Computed:            true,
				Description:         "When the credentials were created.",
				MarkdownDescription: "When the credentials were created.",
			},
			"credentials_id": schema.StringAttribute{
				Required: true,
			},
			"id": schema.StringAttribute{
				Computed:            true,
				Description:         "Unique identifier of the credentials.",
				MarkdownDescription: "Unique identifier of the credentials.",
			},
			"server_name": schema.StringAttribute{
				Computed:            true,
				Description:         "URL of the Tableau server, starting with https:// or http://.",
				MarkdownDescription: "URL of the Tableau server, starting with https:// or http://.",
			},
			"site_name": schema.StringAttribute{
				Computed:            true,
				Description:         "Tableau site. Null for the default site.",
				MarkdownDescription: "Tableau site. Null for the default site.",
			},
			"storage_type": schema.StringAttribute{
				Computed:            true,
				Description:         "Where the secret lives. Fixed once created.",
				MarkdownDescription: "Where the secret lives. Fixed once created.",
			},
			"token_name": schema.StringAttribute{
				Computed:            true,
				Description:         "Name of the personal access token. Null unless the credentials use one.",
				MarkdownDescription: "Name of the personal access token. Null unless the credentials use one.",
			},
			"username": schema.StringAttribute{
				Computed:            true,
				Description:         "Tableau user. Null for a personal access token.",
				MarkdownDescription: "Tableau user. Null for a personal access token.",
			},
			"verify_ssl": schema.BoolAttribute{
				Computed:            true,
				Description:         "Whether to verify the server's TLS certificate. Verified when left out. Null unless set.",
				MarkdownDescription: "Whether to verify the server's TLS certificate. Verified when left out. Null unless set.",
			},
		},
	}
}

type TableauCredentialsModel struct {
	ConnectedAppClientId types.String `tfsdk:"connected_app_client_id"`
	ConnectedAppSecretId types.String `tfsdk:"connected_app_secret_id"`
	ConnectionType       types.String `tfsdk:"connection_type"`
	CreatedTime          types.String `tfsdk:"created_time"`
	CredentialsId        types.String `tfsdk:"credentials_id"`
	Id                   types.String `tfsdk:"id"`
	ServerName           types.String `tfsdk:"server_name"`
	SiteName             types.String `tfsdk:"site_name"`
	StorageType          types.String `tfsdk:"storage_type"`
	TokenName            types.String `tfsdk:"token_name"`
	Username             types.String `tfsdk:"username"`
	VerifySsl            types.Bool   `tfsdk:"verify_ssl"`
}
