// Code generated by terraform-plugin-framework-generator DO NOT EDIT.

package datasource_warehouse

import (
	"context"
	"github.com/hashicorp/terraform-plugin-framework/types"

	"github.com/hashicorp/terraform-plugin-framework/datasource/schema"
)

func WarehouseDataSourceSchema(ctx context.Context) schema.Schema {
	return schema.Schema{
		Attributes: map[string]schema.Attribute{
			"created_time": schema.StringAttribute{
				Computed:            true,
				Description:         "When the warehouse was created.",
				MarkdownDescription: "When the warehouse was created.",
			},
			"deployment_id": schema.StringAttribute{
				Computed: true,
			},
			"id": schema.StringAttribute{
				Computed:            true,
				Description:         "Unique identifier of the warehouse.",
				MarkdownDescription: "Unique identifier of the warehouse.",
			},
			"name": schema.StringAttribute{
				Computed: true,
			},
			"type": schema.StringAttribute{
				Computed:            true,
				Description:         "The kind of data platform a warehouse represents.\n\nEvery connection on a warehouse has to fit its type. A `DATA_LAKE` warehouse holds the\nconnections of a lake made of several systems, such as a metastore and a query engine. A\n`CUSTOM_INTEGRATION` warehouse holds connections you implement yourself.",
				MarkdownDescription: "The kind of data platform a warehouse represents.\n\nEvery connection on a warehouse has to fit its type. A `DATA_LAKE` warehouse holds the\nconnections of a lake made of several systems, such as a metastore and a query engine. A\n`CUSTOM_INTEGRATION` warehouse holds connections you implement yourself.",
			},
			"warehouse_id": schema.StringAttribute{
				Required: true,
			},
		},
	}
}

type WarehouseModel struct {
	CreatedTime  types.String `tfsdk:"created_time"`
	DeploymentId types.String `tfsdk:"deployment_id"`
	Id           types.String `tfsdk:"id"`
	Name         types.String `tfsdk:"name"`
	Type         types.String `tfsdk:"type"`
	WarehouseId  types.String `tfsdk:"warehouse_id"`
}
