// Code generated by terraform-plugin-framework-generator DO NOT EDIT.

package datasource_self_hosted_aws_credentials

import (
	"context"
	"github.com/hashicorp/terraform-plugin-framework/types"

	"github.com/hashicorp/terraform-plugin-framework/datasource/schema"
)

func SelfHostedAwsCredentialsDataSourceSchema(ctx context.Context) schema.Schema {
	return schema.Schema{
		Attributes: map[string]schema.Attribute{
			"assumable_role": schema.StringAttribute{
				Computed:            true,
				Description:         "ARN of the role the deployment assumes to read the secret. Null when unset.",
				MarkdownDescription: "ARN of the role the deployment assumes to read the secret. Null when unset.",
			},
			"aws_region": schema.StringAttribute{
				Computed:            true,
				Description:         "AWS region of the secret. Null when unset.",
				MarkdownDescription: "AWS region of the secret. Null when unset.",
			},
			"aws_secret": schema.StringAttribute{
				Computed:            true,
				Description:         "Name or ARN of the AWS Secrets Manager secret holding the connection's credentials.",
				MarkdownDescription: "Name or ARN of the AWS Secrets Manager secret holding the connection's credentials.",
			},
			"bq_project_id": schema.StringAttribute{
				Computed:            true,
				Description:         "BigQuery project the connection reads from. Null unless set.",
				MarkdownDescription: "BigQuery project the connection reads from. Null unless set.",
			},
			"connection_type": schema.StringAttribute{
				Computed:            true,
				Description:         "The connection type the credentials are for, such as `snowflake`. Fixed once created.",
				MarkdownDescription: "The connection type the credentials are for, such as `snowflake`. Fixed once created.",
			},
			"created_time": schema.StringAttribute{
				Computed:            true,
				Description:         "When the credentials were created.",
				MarkdownDescription: "When the credentials were created.",
			},
			"credentials_id": schema.StringAttribute{
				Required:            true,
				Description:         "Id of the credentials, as returned when they are created or listed.",
				MarkdownDescription: "Id of the credentials, as returned when they are created or listed.",
			},
			"external_id": schema.StringAttribute{
				Computed:            true,
				Description:         "External id presented when assuming the role. Null when unset.",
				MarkdownDescription: "External id presented when assuming the role. Null when unset.",
			},
			"id": schema.StringAttribute{
				Computed:            true,
				Description:         "Unique identifier of the credentials.",
				MarkdownDescription: "Unique identifier of the credentials.",
			},
			"sql_warehouse_id": schema.StringAttribute{
				Computed:            true,
				Description:         "Databricks SQL warehouse the connection runs queries on. Null unless set.",
				MarkdownDescription: "Databricks SQL warehouse the connection runs queries on. Null unless set.",
			},
			"storage_type": schema.StringAttribute{
				Computed:            true,
				Description:         "Where the secret lives. Fixed once created.",
				MarkdownDescription: "Where the secret lives. Fixed once created.",
			},
		},
		Description:         "AWS Secrets Manager credentials point a connection at a secret in your AWS Secrets Manager. Monte Carlo stores the reference, not the secret, and reads the secret each time the connection is used.",
		MarkdownDescription: "AWS Secrets Manager credentials point a connection at a secret in your AWS Secrets Manager. Monte Carlo stores the reference, not the secret, and reads the secret each time the connection is used.",
	}
}

type SelfHostedAwsCredentialsModel struct {
	AssumableRole  types.String `tfsdk:"assumable_role"`
	AwsRegion      types.String `tfsdk:"aws_region"`
	AwsSecret      types.String `tfsdk:"aws_secret"`
	BqProjectId    types.String `tfsdk:"bq_project_id"`
	ConnectionType types.String `tfsdk:"connection_type"`
	CreatedTime    types.String `tfsdk:"created_time"`
	CredentialsId  types.String `tfsdk:"credentials_id"`
	ExternalId     types.String `tfsdk:"external_id"`
	Id             types.String `tfsdk:"id"`
	SqlWarehouseId types.String `tfsdk:"sql_warehouse_id"`
	StorageType    types.String `tfsdk:"storage_type"`
}
