// Code generated by terraform-plugin-framework-generator DO NOT EDIT.

package datasource_mulesoft_credentials

import (
	"context"
	"github.com/hashicorp/terraform-plugin-framework/types"

	"github.com/hashicorp/terraform-plugin-framework/datasource/schema"
)

func MulesoftCredentialsDataSourceSchema(ctx context.Context) schema.Schema {
	return schema.Schema{
		Attributes: map[string]schema.Attribute{
			"app_client_id": schema.StringAttribute{
				Computed:            true,
				Description:         "Client ID of the Anypoint connected app. The app needs the View Environment, Read Deployments and Exchange Viewer scopes.",
				MarkdownDescription: "Client ID of the Anypoint connected app. The app needs the View Environment, Read Deployments and Exchange Viewer scopes.",
			},
			"connection_type": schema.StringAttribute{
				Computed:            true,
				Description:         "The connection type the credentials are for, such as `snowflake`. Fixed once created.",
				MarkdownDescription: "The connection type the credentials are for, such as `snowflake`. Fixed once created.",
			},
			"created_time": schema.StringAttribute{
				Computed:            true,
				Description:         "When the credentials were created.",
				MarkdownDescription: "When the credentials were created.",
			},
			"credentials_id": schema.StringAttribute{
				Required: true,
			},
			"id": schema.StringAttribute{
				Computed:            true,
				Description:         "Unique identifier of the credentials.",
				MarkdownDescription: "Unique identifier of the credentials.",
			},
			"org_id": schema.StringAttribute{
				Computed:            true,
				Description:         "Anypoint organization or business group to collect from. Set it when your Mule applications are deployed in a business group. Leave it out to collect the organization that owns the connected app. Null unless set.",
				MarkdownDescription: "Anypoint organization or business group to collect from. Set it when your Mule applications are deployed in a business group. Leave it out to collect the organization that owns the connected app. Null unless set.",
			},
			"region": schema.StringAttribute{
				Computed:            true,
				Description:         "Anypoint Platform instance the organization lives on.",
				MarkdownDescription: "Anypoint Platform instance the organization lives on.",
			},
			"storage_type": schema.StringAttribute{
				Computed:            true,
				Description:         "Where the secret lives. Fixed once created.",
				MarkdownDescription: "Where the secret lives. Fixed once created.",
			},
		},
	}
}

type MulesoftCredentialsModel struct {
	AppClientId    types.String `tfsdk:"app_client_id"`
	ConnectionType types.String `tfsdk:"connection_type"`
	CreatedTime    types.String `tfsdk:"created_time"`
	CredentialsId  types.String `tfsdk:"credentials_id"`
	Id             types.String `tfsdk:"id"`
	OrgId          types.String `tfsdk:"org_id"`
	Region         types.String `tfsdk:"region"`
	StorageType    types.String `tfsdk:"storage_type"`
}
