// Code generated by terraform-plugin-framework-generator DO NOT EDIT.

package resource_azure_collection_data_store

import (
	"context"
	"fmt"
	"github.com/hashicorp/terraform-plugin-framework-validators/stringvalidator"
	"github.com/hashicorp/terraform-plugin-framework/attr"
	"github.com/hashicorp/terraform-plugin-framework/diag"
	"github.com/hashicorp/terraform-plugin-framework/schema/validator"
	"github.com/hashicorp/terraform-plugin-framework/types"
	"github.com/hashicorp/terraform-plugin-framework/types/basetypes"
	"github.com/hashicorp/terraform-plugin-go/tftypes"
	"regexp"
	"strings"

	"github.com/hashicorp/terraform-plugin-framework/resource/schema"
)

func AzureCollectionDataStoreResourceSchema(ctx context.Context) schema.Schema {
	return schema.Schema{
		Attributes: map[string]schema.Attribute{
			"authentication_type": schema.StringAttribute{
				Required:            true,
				Description:         "How Monte Carlo authenticates to the storage account. Send it together with the matching credentials object.",
				MarkdownDescription: "How Monte Carlo authenticates to the storage account. Send it together with the matching credentials object.",
				Validators: []validator.String{
					stringvalidator.OneOf(
						"AZURE_STORAGE_ACCOUNT_KEYS",
						"AZURE_STORAGE_SERVICE_PRINCIPAL",
					),
				},
			},
			"container_name": schema.StringAttribute{
				Required:            true,
				Description:         "Name of the blob container Monte Carlo should use.",
				MarkdownDescription: "Name of the blob container Monte Carlo should use.",
				Validators: []validator.String{
					stringvalidator.RegexMatches(regexp.MustCompile("^[a-z0-9][a-z0-9-]{1,61}[a-z0-9]$"), ""),
				},
			},
			"created_time": schema.StringAttribute{
				Computed:            true,
				Description:         "When the data store was created, which is when its deployment was provisioned.",
				MarkdownDescription: "When the data store was created, which is when its deployment was provisioned.",
			},
			"deployment_id": schema.StringAttribute{
				Required:            true,
				Description:         "Deployment to register the data store on. It must already hold an unregistered Azure data store.",
				MarkdownDescription: "Deployment to register the data store on. It must already hold an unregistered Azure data store.",
			},
			"enabled": schema.BoolAttribute{
				Computed:            true,
				Description:         "Whether Monte Carlo is using this data store. One that is unregistered, or whose validation failed, is not enabled.",
				MarkdownDescription: "Whether Monte Carlo is using this data store. One that is unregistered, or whose validation failed, is not enabled.",
			},
			"id": schema.StringAttribute{
				Computed:            true,
				Description:         "Unique identifier of the data store.",
				MarkdownDescription: "Unique identifier of the data store.",
			},
			"last_updated_time": schema.StringAttribute{
				Computed:            true,
				Description:         "When the data store was last registered, renamed, or given different storage or credentials. Null until one of those has happened.",
				MarkdownDescription: "When the data store was last registered, renamed, or given different storage or credentials. Null until one of those has happened.",
			},
			"name": schema.StringAttribute{
				Optional:            true,
				Computed:            true,
				Description:         "Display name for the data store. Replaces the name its deployment gave it.",
				MarkdownDescription: "Display name for the data store. Replaces the name its deployment gave it.",
				Validators: []validator.String{
					stringvalidator.LengthAtMost(200),
				},
			},
			"service_principal": schema.SingleNestedAttribute{
				Attributes: map[string]schema.Attribute{
					"account_name": schema.StringAttribute{
						Optional:            true,
						Computed:            true,
						Description:         "Name of the storage account, needed only when `account_url` does not start with it. Monte Carlo takes the first label of the host otherwise, which is right for a standard or private-link URL but not for a custom ingress host.",
						MarkdownDescription: "Name of the storage account, needed only when `account_url` does not start with it. Monte Carlo takes the first label of the host otherwise, which is right for a standard or private-link URL but not for a custom ingress host.",
					},
					"account_url": schema.StringAttribute{
						Required:            true,
						Description:         "URL of the storage account Monte Carlo sends requests to. A private endpoint or a custom host works, so this is not required to be under `blob.core.windows.net`.",
						MarkdownDescription: "URL of the storage account Monte Carlo sends requests to. A private endpoint or a custom host works, so this is not required to be under `blob.core.windows.net`.",
						Validators: []validator.String{
							stringvalidator.RegexMatches(regexp.MustCompile("^https://[^\\s/?#]+\\S*$"), ""),
						},
					},
					"client_id": schema.StringAttribute{
						Required:            true,
						Description:         "Application (client) id of the service principal.",
						MarkdownDescription: "Application (client) id of the service principal.",
					},
					"client_secret_wo": schema.StringAttribute{
						Required:            true,
						Sensitive:           true,
						Description:         "Client secret of the service principal.",
						MarkdownDescription: "Client secret of the service principal.",
					},
					"client_secret_wo_version": schema.Int64Attribute{
						Required:            true,
						Description:         "Bump to send `client_secret_wo` again. Terraform stores this, never the secret.",
						MarkdownDescription: "Bump to send `client_secret_wo` again. Terraform stores this, never the secret.",
					},
					"tenant_id": schema.StringAttribute{
						Required:            true,
						Description:         "Directory (tenant) id the service principal lives in.",
						MarkdownDescription: "Directory (tenant) id the service principal lives in.",
					},
				},
				CustomType: ServicePrincipalType{
					ObjectType: types.ObjectType{
						AttrTypes: ServicePrincipalValue{}.AttributeTypes(ctx),
					},
				},
				Optional:            true,
				Description:         "Credentials for `AZURE_STORAGE_SERVICE_PRINCIPAL`. Send this or `storage_account_keys`, never both.",
				MarkdownDescription: "Credentials for `AZURE_STORAGE_SERVICE_PRINCIPAL`. Send this or `storage_account_keys`, never both.",
			},
			"storage_account_keys": schema.SingleNestedAttribute{
				Attributes: map[string]schema.Attribute{
					"connection_string_wo": schema.StringAttribute{
						Required:            true,
						Sensitive:           true,
						Description:         "Connection string for the storage account holding the container. It carries the account key, so treat it as a secret.",
						MarkdownDescription: "Connection string for the storage account holding the container. It carries the account key, so treat it as a secret.",
					},
					"connection_string_wo_version": schema.Int64Attribute{
						Required:            true,
						Description:         "Bump to send `connection_string_wo` again. Terraform stores this, never the secret.",
						MarkdownDescription: "Bump to send `connection_string_wo` again. Terraform stores this, never the secret.",
					},
				},
				CustomType: StorageAccountKeysType{
					ObjectType: types.ObjectType{
						AttrTypes: StorageAccountKeysValue{}.AttributeTypes(ctx),
					},
				},
				Optional:            true,
				Description:         "Credentials for `AZURE_STORAGE_ACCOUNT_KEYS`. Send this or `service_principal`, never both.",
				MarkdownDescription: "Credentials for `AZURE_STORAGE_ACCOUNT_KEYS`. Send this or `service_principal`, never both.",
			},
			"storage_type": schema.StringAttribute{
				Computed:            true,
				Description:         "Which kind of storage the data store keeps its data in.",
				MarkdownDescription: "Which kind of storage the data store keeps its data in.",
			},
		},
	}
}

type AzureCollectionDataStoreModel struct {
	AuthenticationType types.String            `tfsdk:"authentication_type"`
	ContainerName      types.String            `tfsdk:"container_name"`
	CreatedTime        types.String            `tfsdk:"created_time"`
	DeploymentId       types.String            `tfsdk:"deployment_id"`
	Enabled            types.Bool              `tfsdk:"enabled"`
	Id                 types.String            `tfsdk:"id"`
	LastUpdatedTime    types.String            `tfsdk:"last_updated_time"`
	Name               types.String            `tfsdk:"name"`
	ServicePrincipal   ServicePrincipalValue   `tfsdk:"service_principal"`
	StorageAccountKeys StorageAccountKeysValue `tfsdk:"storage_account_keys"`
	StorageType        types.String            `tfsdk:"storage_type"`
}

var _ basetypes.ObjectTypable = ServicePrincipalType{}

type ServicePrincipalType struct {
	basetypes.ObjectType
}

func (t ServicePrincipalType) Equal(o attr.Type) bool {
	other, ok := o.(ServicePrincipalType)

	if !ok {
		return false
	}

	return t.ObjectType.Equal(other.ObjectType)
}

func (t ServicePrincipalType) String() string {
	return "ServicePrincipalType"
}

func (t ServicePrincipalType) ValueFromObject(ctx context.Context, in basetypes.ObjectValue) (basetypes.ObjectValuable, diag.Diagnostics) {
	var diags diag.Diagnostics

	attributes := in.Attributes()

	accountNameAttribute, ok := attributes["account_name"]

	if !ok {
		diags.AddError(
			"Attribute Missing",
			`account_name is missing from object`)

		return nil, diags
	}

	accountNameVal, ok := accountNameAttribute.(basetypes.StringValue)

	if !ok {
		diags.AddError(
			"Attribute Wrong Type",
			fmt.Sprintf(`account_name expected to be basetypes.StringValue, was: %T`, accountNameAttribute))
	}

	accountUrlAttribute, ok := attributes["account_url"]

	if !ok {
		diags.AddError(
			"Attribute Missing",
			`account_url is missing from object`)

		return nil, diags
	}

	accountUrlVal, ok := accountUrlAttribute.(basetypes.StringValue)

	if !ok {
		diags.AddError(
			"Attribute Wrong Type",
			fmt.Sprintf(`account_url expected to be basetypes.StringValue, was: %T`, accountUrlAttribute))
	}

	clientIdAttribute, ok := attributes["client_id"]

	if !ok {
		diags.AddError(
			"Attribute Missing",
			`client_id is missing from object`)

		return nil, diags
	}

	clientIdVal, ok := clientIdAttribute.(basetypes.StringValue)

	if !ok {
		diags.AddError(
			"Attribute Wrong Type",
			fmt.Sprintf(`client_id expected to be basetypes.StringValue, was: %T`, clientIdAttribute))
	}

	clientSecretWoAttribute, ok := attributes["client_secret_wo"]

	if !ok {
		diags.AddError(
			"Attribute Missing",
			`client_secret_wo is missing from object`)

		return nil, diags
	}

	clientSecretWoVal, ok := clientSecretWoAttribute.(basetypes.StringValue)

	if !ok {
		diags.AddError(
			"Attribute Wrong Type",
			fmt.Sprintf(`client_secret_wo expected to be basetypes.StringValue, was: %T`, clientSecretWoAttribute))
	}

	clientSecretWoVersionAttribute, ok := attributes["client_secret_wo_version"]

	if !ok {
		diags.AddError(
			"Attribute Missing",
			`client_secret_wo_version is missing from object`)

		return nil, diags
	}

	clientSecretWoVersionVal, ok := clientSecretWoVersionAttribute.(basetypes.Int64Value)

	if !ok {
		diags.AddError(
			"Attribute Wrong Type",
			fmt.Sprintf(`client_secret_wo_version expected to be basetypes.Int64Value, was: %T`, clientSecretWoVersionAttribute))
	}

	tenantIdAttribute, ok := attributes["tenant_id"]

	if !ok {
		diags.AddError(
			"Attribute Missing",
			`tenant_id is missing from object`)

		return nil, diags
	}

	tenantIdVal, ok := tenantIdAttribute.(basetypes.StringValue)

	if !ok {
		diags.AddError(
			"Attribute Wrong Type",
			fmt.Sprintf(`tenant_id expected to be basetypes.StringValue, was: %T`, tenantIdAttribute))
	}

	if diags.HasError() {
		return nil, diags
	}

	return ServicePrincipalValue{
		AccountName:           accountNameVal,
		AccountUrl:            accountUrlVal,
		ClientId:              clientIdVal,
		ClientSecretWo:        clientSecretWoVal,
		ClientSecretWoVersion: clientSecretWoVersionVal,
		TenantId:              tenantIdVal,
		state:                 attr.ValueStateKnown,
	}, diags
}

func NewServicePrincipalValueNull() ServicePrincipalValue {
	return ServicePrincipalValue{
		state: attr.ValueStateNull,
	}
}

func NewServicePrincipalValueUnknown() ServicePrincipalValue {
	return ServicePrincipalValue{
		state: attr.ValueStateUnknown,
	}
}

func NewServicePrincipalValue(attributeTypes map[string]attr.Type, attributes map[string]attr.Value) (ServicePrincipalValue, diag.Diagnostics) {
	var diags diag.Diagnostics

	// Reference: https://github.com/hashicorp/terraform-plugin-framework/issues/521
	ctx := context.Background()

	for name, attributeType := range attributeTypes {
		attribute, ok := attributes[name]

		if !ok {
			diags.AddError(
				"Missing ServicePrincipalValue Attribute Value",
				"While creating a ServicePrincipalValue value, a missing attribute value was detected. "+
					"A ServicePrincipalValue must contain values for all attributes, even if null or unknown. "+
					"This is always an issue with the provider and should be reported to the provider developers.\n\n"+
					fmt.Sprintf("ServicePrincipalValue Attribute Name (%s) Expected Type: %s", name, attributeType.String()),
			)

			continue
		}

		if !attributeType.Equal(attribute.Type(ctx)) {
			diags.AddError(
				"Invalid ServicePrincipalValue Attribute Type",
				"While creating a ServicePrincipalValue value, an invalid attribute value was detected. "+
					"A ServicePrincipalValue must use a matching attribute type for the value. "+
					"This is always an issue with the provider and should be reported to the provider developers.\n\n"+
					fmt.Sprintf("ServicePrincipalValue Attribute Name (%s) Expected Type: %s\n", name, attributeType.String())+
					fmt.Sprintf("ServicePrincipalValue Attribute Name (%s) Given Type: %s", name, attribute.Type(ctx)),
			)
		}
	}

	for name := range attributes {
		_, ok := attributeTypes[name]

		if !ok {
			diags.AddError(
				"Extra ServicePrincipalValue Attribute Value",
				"While creating a ServicePrincipalValue value, an extra attribute value was detected. "+
					"A ServicePrincipalValue must not contain values beyond the expected attribute types. "+
					"This is always an issue with the provider and should be reported to the provider developers.\n\n"+
					fmt.Sprintf("Extra ServicePrincipalValue Attribute Name: %s", name),
			)
		}
	}

	if diags.HasError() {
		return NewServicePrincipalValueUnknown(), diags
	}

	accountNameAttribute, ok := attributes["account_name"]

	if !ok {
		diags.AddError(
			"Attribute Missing",
			`account_name is missing from object`)

		return NewServicePrincipalValueUnknown(), diags
	}

	accountNameVal, ok := accountNameAttribute.(basetypes.StringValue)

	if !ok {
		diags.AddError(
			"Attribute Wrong Type",
			fmt.Sprintf(`account_name expected to be basetypes.StringValue, was: %T`, accountNameAttribute))
	}

	accountUrlAttribute, ok := attributes["account_url"]

	if !ok {
		diags.AddError(
			"Attribute Missing",
			`account_url is missing from object`)

		return NewServicePrincipalValueUnknown(), diags
	}

	accountUrlVal, ok := accountUrlAttribute.(basetypes.StringValue)

	if !ok {
		diags.AddError(
			"Attribute Wrong Type",
			fmt.Sprintf(`account_url expected to be basetypes.StringValue, was: %T`, accountUrlAttribute))
	}

	clientIdAttribute, ok := attributes["client_id"]

	if !ok {
		diags.AddError(
			"Attribute Missing",
			`client_id is missing from object`)

		return NewServicePrincipalValueUnknown(), diags
	}

	clientIdVal, ok := clientIdAttribute.(basetypes.StringValue)

	if !ok {
		diags.AddError(
			"Attribute Wrong Type",
			fmt.Sprintf(`client_id expected to be basetypes.StringValue, was: %T`, clientIdAttribute))
	}

	clientSecretWoAttribute, ok := attributes["client_secret_wo"]

	if !ok {
		diags.AddError(
			"Attribute Missing",
			`client_secret_wo is missing from object`)

		return NewServicePrincipalValueUnknown(), diags
	}

	clientSecretWoVal, ok := clientSecretWoAttribute.(basetypes.StringValue)

	if !ok {
		diags.AddError(
			"Attribute Wrong Type",
			fmt.Sprintf(`client_secret_wo expected to be basetypes.StringValue, was: %T`, clientSecretWoAttribute))
	}

	clientSecretWoVersionAttribute, ok := attributes["client_secret_wo_version"]

	if !ok {
		diags.AddError(
			"Attribute Missing",
			`client_secret_wo_version is missing from object`)

		return NewServicePrincipalValueUnknown(), diags
	}

	clientSecretWoVersionVal, ok := clientSecretWoVersionAttribute.(basetypes.Int64Value)

	if !ok {
		diags.AddError(
			"Attribute Wrong Type",
			fmt.Sprintf(`client_secret_wo_version expected to be basetypes.Int64Value, was: %T`, clientSecretWoVersionAttribute))
	}

	tenantIdAttribute, ok := attributes["tenant_id"]

	if !ok {
		diags.AddError(
			"Attribute Missing",
			`tenant_id is missing from object`)

		return NewServicePrincipalValueUnknown(), diags
	}

	tenantIdVal, ok := tenantIdAttribute.(basetypes.StringValue)

	if !ok {
		diags.AddError(
			"Attribute Wrong Type",
			fmt.Sprintf(`tenant_id expected to be basetypes.StringValue, was: %T`, tenantIdAttribute))
	}

	if diags.HasError() {
		return NewServicePrincipalValueUnknown(), diags
	}

	return ServicePrincipalValue{
		AccountName:           accountNameVal,
		AccountUrl:            accountUrlVal,
		ClientId:              clientIdVal,
		ClientSecretWo:        clientSecretWoVal,
		ClientSecretWoVersion: clientSecretWoVersionVal,
		TenantId:              tenantIdVal,
		state:                 attr.ValueStateKnown,
	}, diags
}

func NewServicePrincipalValueMust(attributeTypes map[string]attr.Type, attributes map[string]attr.Value) ServicePrincipalValue {
	object, diags := NewServicePrincipalValue(attributeTypes, attributes)

	if diags.HasError() {
		// This could potentially be added to the diag package.
		diagsStrings := make([]string, 0, len(diags))

		for _, diagnostic := range diags {
			diagsStrings = append(diagsStrings, fmt.Sprintf(
				"%s | %s | %s",
				diagnostic.Severity(),
				diagnostic.Summary(),
				diagnostic.Detail()))
		}

		panic("NewServicePrincipalValueMust received error(s): " + strings.Join(diagsStrings, "\n"))
	}

	return object
}

func (t ServicePrincipalType) ValueFromTerraform(ctx context.Context, in tftypes.Value) (attr.Value, error) {
	if in.Type() == nil {
		return NewServicePrincipalValueNull(), nil
	}

	if !in.Type().Equal(t.TerraformType(ctx)) {
		return nil, fmt.Errorf("expected %s, got %s", t.TerraformType(ctx), in.Type())
	}

	if !in.IsKnown() {
		return NewServicePrincipalValueUnknown(), nil
	}

	if in.IsNull() {
		return NewServicePrincipalValueNull(), nil
	}

	attributes := map[string]attr.Value{}

	val := map[string]tftypes.Value{}

	err := in.As(&val)

	if err != nil {
		return nil, err
	}

	for k, v := range val {
		a, err := t.AttrTypes[k].ValueFromTerraform(ctx, v)

		if err != nil {
			return nil, err
		}

		attributes[k] = a
	}

	return NewServicePrincipalValueMust(ServicePrincipalValue{}.AttributeTypes(ctx), attributes), nil
}

func (t ServicePrincipalType) ValueType(ctx context.Context) attr.Value {
	return ServicePrincipalValue{}
}

var _ basetypes.ObjectValuable = ServicePrincipalValue{}

type ServicePrincipalValue struct {
	AccountName           basetypes.StringValue `tfsdk:"account_name"`
	AccountUrl            basetypes.StringValue `tfsdk:"account_url"`
	ClientId              basetypes.StringValue `tfsdk:"client_id"`
	ClientSecretWo        basetypes.StringValue `tfsdk:"client_secret_wo"`
	ClientSecretWoVersion basetypes.Int64Value  `tfsdk:"client_secret_wo_version"`
	TenantId              basetypes.StringValue `tfsdk:"tenant_id"`
	state                 attr.ValueState
}

func (v ServicePrincipalValue) ToTerraformValue(ctx context.Context) (tftypes.Value, error) {
	attrTypes := make(map[string]tftypes.Type, 6)

	var val tftypes.Value
	var err error

	attrTypes["account_name"] = basetypes.StringType{}.TerraformType(ctx)
	attrTypes["account_url"] = basetypes.StringType{}.TerraformType(ctx)
	attrTypes["client_id"] = basetypes.StringType{}.TerraformType(ctx)
	attrTypes["client_secret_wo"] = basetypes.StringType{}.TerraformType(ctx)
	attrTypes["client_secret_wo_version"] = basetypes.Int64Type{}.TerraformType(ctx)
	attrTypes["tenant_id"] = basetypes.StringType{}.TerraformType(ctx)

	objectType := tftypes.Object{AttributeTypes: attrTypes}

	switch v.state {
	case attr.ValueStateKnown:
		vals := make(map[string]tftypes.Value, 6)

		val, err = v.AccountName.ToTerraformValue(ctx)

		if err != nil {
			return tftypes.NewValue(objectType, tftypes.UnknownValue), err
		}

		vals["account_name"] = val

		val, err = v.AccountUrl.ToTerraformValue(ctx)

		if err != nil {
			return tftypes.NewValue(objectType, tftypes.UnknownValue), err
		}

		vals["account_url"] = val

		val, err = v.ClientId.ToTerraformValue(ctx)

		if err != nil {
			return tftypes.NewValue(objectType, tftypes.UnknownValue), err
		}

		vals["client_id"] = val

		val, err = v.ClientSecretWo.ToTerraformValue(ctx)

		if err != nil {
			return tftypes.NewValue(objectType, tftypes.UnknownValue), err
		}

		vals["client_secret_wo"] = val

		val, err = v.ClientSecretWoVersion.ToTerraformValue(ctx)

		if err != nil {
			return tftypes.NewValue(objectType, tftypes.UnknownValue), err
		}

		vals["client_secret_wo_version"] = val

		val, err = v.TenantId.ToTerraformValue(ctx)

		if err != nil {
			return tftypes.NewValue(objectType, tftypes.UnknownValue), err
		}

		vals["tenant_id"] = val

		if err := tftypes.ValidateValue(objectType, vals); err != nil {
			return tftypes.NewValue(objectType, tftypes.UnknownValue), err
		}

		return tftypes.NewValue(objectType, vals), nil
	case attr.ValueStateNull:
		return tftypes.NewValue(objectType, nil), nil
	case attr.ValueStateUnknown:
		return tftypes.NewValue(objectType, tftypes.UnknownValue), nil
	default:
		panic(fmt.Sprintf("unhandled Object state in ToTerraformValue: %s", v.state))
	}
}

func (v ServicePrincipalValue) IsNull() bool {
	return v.state == attr.ValueStateNull
}

func (v ServicePrincipalValue) IsUnknown() bool {
	return v.state == attr.ValueStateUnknown
}

func (v ServicePrincipalValue) String() string {
	return "ServicePrincipalValue"
}

func (v ServicePrincipalValue) ToObjectValue(ctx context.Context) (basetypes.ObjectValue, diag.Diagnostics) {
	var diags diag.Diagnostics

	attributeTypes := map[string]attr.Type{
		"account_name":             basetypes.StringType{},
		"account_url":              basetypes.StringType{},
		"client_id":                basetypes.StringType{},
		"client_secret_wo":         basetypes.StringType{},
		"client_secret_wo_version": basetypes.Int64Type{},
		"tenant_id":                basetypes.StringType{},
	}

	if v.IsNull() {
		return types.ObjectNull(attributeTypes), diags
	}

	if v.IsUnknown() {
		return types.ObjectUnknown(attributeTypes), diags
	}

	objVal, diags := types.ObjectValue(
		attributeTypes,
		map[string]attr.Value{
			"account_name":             v.AccountName,
			"account_url":              v.AccountUrl,
			"client_id":                v.ClientId,
			"client_secret_wo":         v.ClientSecretWo,
			"client_secret_wo_version": v.ClientSecretWoVersion,
			"tenant_id":                v.TenantId,
		})

	return objVal, diags
}

func (v ServicePrincipalValue) Equal(o attr.Value) bool {
	other, ok := o.(ServicePrincipalValue)

	if !ok {
		return false
	}

	if v.state != other.state {
		return false
	}

	if v.state != attr.ValueStateKnown {
		return true
	}

	if !v.AccountName.Equal(other.AccountName) {
		return false
	}

	if !v.AccountUrl.Equal(other.AccountUrl) {
		return false
	}

	if !v.ClientId.Equal(other.ClientId) {
		return false
	}

	if !v.ClientSecretWo.Equal(other.ClientSecretWo) {
		return false
	}

	if !v.ClientSecretWoVersion.Equal(other.ClientSecretWoVersion) {
		return false
	}

	if !v.TenantId.Equal(other.TenantId) {
		return false
	}

	return true
}

func (v ServicePrincipalValue) Type(ctx context.Context) attr.Type {
	return ServicePrincipalType{
		basetypes.ObjectType{
			AttrTypes: v.AttributeTypes(ctx),
		},
	}
}

func (v ServicePrincipalValue) AttributeTypes(ctx context.Context) map[string]attr.Type {
	return map[string]attr.Type{
		"account_name":             basetypes.StringType{},
		"account_url":              basetypes.StringType{},
		"client_id":                basetypes.StringType{},
		"client_secret_wo":         basetypes.StringType{},
		"client_secret_wo_version": basetypes.Int64Type{},
		"tenant_id":                basetypes.StringType{},
	}
}

var _ basetypes.ObjectTypable = StorageAccountKeysType{}

type StorageAccountKeysType struct {
	basetypes.ObjectType
}

func (t StorageAccountKeysType) Equal(o attr.Type) bool {
	other, ok := o.(StorageAccountKeysType)

	if !ok {
		return false
	}

	return t.ObjectType.Equal(other.ObjectType)
}

func (t StorageAccountKeysType) String() string {
	return "StorageAccountKeysType"
}

func (t StorageAccountKeysType) ValueFromObject(ctx context.Context, in basetypes.ObjectValue) (basetypes.ObjectValuable, diag.Diagnostics) {
	var diags diag.Diagnostics

	attributes := in.Attributes()

	connectionStringWoAttribute, ok := attributes["connection_string_wo"]

	if !ok {
		diags.AddError(
			"Attribute Missing",
			`connection_string_wo is missing from object`)

		return nil, diags
	}

	connectionStringWoVal, ok := connectionStringWoAttribute.(basetypes.StringValue)

	if !ok {
		diags.AddError(
			"Attribute Wrong Type",
			fmt.Sprintf(`connection_string_wo expected to be basetypes.StringValue, was: %T`, connectionStringWoAttribute))
	}

	connectionStringWoVersionAttribute, ok := attributes["connection_string_wo_version"]

	if !ok {
		diags.AddError(
			"Attribute Missing",
			`connection_string_wo_version is missing from object`)

		return nil, diags
	}

	connectionStringWoVersionVal, ok := connectionStringWoVersionAttribute.(basetypes.Int64Value)

	if !ok {
		diags.AddError(
			"Attribute Wrong Type",
			fmt.Sprintf(`connection_string_wo_version expected to be basetypes.Int64Value, was: %T`, connectionStringWoVersionAttribute))
	}

	if diags.HasError() {
		return nil, diags
	}

	return StorageAccountKeysValue{
		ConnectionStringWo:        connectionStringWoVal,
		ConnectionStringWoVersion: connectionStringWoVersionVal,
		state:                     attr.ValueStateKnown,
	}, diags
}

func NewStorageAccountKeysValueNull() StorageAccountKeysValue {
	return StorageAccountKeysValue{
		state: attr.ValueStateNull,
	}
}

func NewStorageAccountKeysValueUnknown() StorageAccountKeysValue {
	return StorageAccountKeysValue{
		state: attr.ValueStateUnknown,
	}
}

func NewStorageAccountKeysValue(attributeTypes map[string]attr.Type, attributes map[string]attr.Value) (StorageAccountKeysValue, diag.Diagnostics) {
	var diags diag.Diagnostics

	// Reference: https://github.com/hashicorp/terraform-plugin-framework/issues/521
	ctx := context.Background()

	for name, attributeType := range attributeTypes {
		attribute, ok := attributes[name]

		if !ok {
			diags.AddError(
				"Missing StorageAccountKeysValue Attribute Value",
				"While creating a StorageAccountKeysValue value, a missing attribute value was detected. "+
					"A StorageAccountKeysValue must contain values for all attributes, even if null or unknown. "+
					"This is always an issue with the provider and should be reported to the provider developers.\n\n"+
					fmt.Sprintf("StorageAccountKeysValue Attribute Name (%s) Expected Type: %s", name, attributeType.String()),
			)

			continue
		}

		if !attributeType.Equal(attribute.Type(ctx)) {
			diags.AddError(
				"Invalid StorageAccountKeysValue Attribute Type",
				"While creating a StorageAccountKeysValue value, an invalid attribute value was detected. "+
					"A StorageAccountKeysValue must use a matching attribute type for the value. "+
					"This is always an issue with the provider and should be reported to the provider developers.\n\n"+
					fmt.Sprintf("StorageAccountKeysValue Attribute Name (%s) Expected Type: %s\n", name, attributeType.String())+
					fmt.Sprintf("StorageAccountKeysValue Attribute Name (%s) Given Type: %s", name, attribute.Type(ctx)),
			)
		}
	}

	for name := range attributes {
		_, ok := attributeTypes[name]

		if !ok {
			diags.AddError(
				"Extra StorageAccountKeysValue Attribute Value",
				"While creating a StorageAccountKeysValue value, an extra attribute value was detected. "+
					"A StorageAccountKeysValue must not contain values beyond the expected attribute types. "+
					"This is always an issue with the provider and should be reported to the provider developers.\n\n"+
					fmt.Sprintf("Extra StorageAccountKeysValue Attribute Name: %s", name),
			)
		}
	}

	if diags.HasError() {
		return NewStorageAccountKeysValueUnknown(), diags
	}

	connectionStringWoAttribute, ok := attributes["connection_string_wo"]

	if !ok {
		diags.AddError(
			"Attribute Missing",
			`connection_string_wo is missing from object`)

		return NewStorageAccountKeysValueUnknown(), diags
	}

	connectionStringWoVal, ok := connectionStringWoAttribute.(basetypes.StringValue)

	if !ok {
		diags.AddError(
			"Attribute Wrong Type",
			fmt.Sprintf(`connection_string_wo expected to be basetypes.StringValue, was: %T`, connectionStringWoAttribute))
	}

	connectionStringWoVersionAttribute, ok := attributes["connection_string_wo_version"]

	if !ok {
		diags.AddError(
			"Attribute Missing",
			`connection_string_wo_version is missing from object`)

		return NewStorageAccountKeysValueUnknown(), diags
	}

	connectionStringWoVersionVal, ok := connectionStringWoVersionAttribute.(basetypes.Int64Value)

	if !ok {
		diags.AddError(
			"Attribute Wrong Type",
			fmt.Sprintf(`connection_string_wo_version expected to be basetypes.Int64Value, was: %T`, connectionStringWoVersionAttribute))
	}

	if diags.HasError() {
		return NewStorageAccountKeysValueUnknown(), diags
	}

	return StorageAccountKeysValue{
		ConnectionStringWo:        connectionStringWoVal,
		ConnectionStringWoVersion: connectionStringWoVersionVal,
		state:                     attr.ValueStateKnown,
	}, diags
}

func NewStorageAccountKeysValueMust(attributeTypes map[string]attr.Type, attributes map[string]attr.Value) StorageAccountKeysValue {
	object, diags := NewStorageAccountKeysValue(attributeTypes, attributes)

	if diags.HasError() {
		// This could potentially be added to the diag package.
		diagsStrings := make([]string, 0, len(diags))

		for _, diagnostic := range diags {
			diagsStrings = append(diagsStrings, fmt.Sprintf(
				"%s | %s | %s",
				diagnostic.Severity(),
				diagnostic.Summary(),
				diagnostic.Detail()))
		}

		panic("NewStorageAccountKeysValueMust received error(s): " + strings.Join(diagsStrings, "\n"))
	}

	return object
}

func (t StorageAccountKeysType) ValueFromTerraform(ctx context.Context, in tftypes.Value) (attr.Value, error) {
	if in.Type() == nil {
		return NewStorageAccountKeysValueNull(), nil
	}

	if !in.Type().Equal(t.TerraformType(ctx)) {
		return nil, fmt.Errorf("expected %s, got %s", t.TerraformType(ctx), in.Type())
	}

	if !in.IsKnown() {
		return NewStorageAccountKeysValueUnknown(), nil
	}

	if in.IsNull() {
		return NewStorageAccountKeysValueNull(), nil
	}

	attributes := map[string]attr.Value{}

	val := map[string]tftypes.Value{}

	err := in.As(&val)

	if err != nil {
		return nil, err
	}

	for k, v := range val {
		a, err := t.AttrTypes[k].ValueFromTerraform(ctx, v)

		if err != nil {
			return nil, err
		}

		attributes[k] = a
	}

	return NewStorageAccountKeysValueMust(StorageAccountKeysValue{}.AttributeTypes(ctx), attributes), nil
}

func (t StorageAccountKeysType) ValueType(ctx context.Context) attr.Value {
	return StorageAccountKeysValue{}
}

var _ basetypes.ObjectValuable = StorageAccountKeysValue{}

type StorageAccountKeysValue struct {
	ConnectionStringWo        basetypes.StringValue `tfsdk:"connection_string_wo"`
	ConnectionStringWoVersion basetypes.Int64Value  `tfsdk:"connection_string_wo_version"`
	state                     attr.ValueState
}

func (v StorageAccountKeysValue) ToTerraformValue(ctx context.Context) (tftypes.Value, error) {
	attrTypes := make(map[string]tftypes.Type, 2)

	var val tftypes.Value
	var err error

	attrTypes["connection_string_wo"] = basetypes.StringType{}.TerraformType(ctx)
	attrTypes["connection_string_wo_version"] = basetypes.Int64Type{}.TerraformType(ctx)

	objectType := tftypes.Object{AttributeTypes: attrTypes}

	switch v.state {
	case attr.ValueStateKnown:
		vals := make(map[string]tftypes.Value, 2)

		val, err = v.ConnectionStringWo.ToTerraformValue(ctx)

		if err != nil {
			return tftypes.NewValue(objectType, tftypes.UnknownValue), err
		}

		vals["connection_string_wo"] = val

		val, err = v.ConnectionStringWoVersion.ToTerraformValue(ctx)

		if err != nil {
			return tftypes.NewValue(objectType, tftypes.UnknownValue), err
		}

		vals["connection_string_wo_version"] = val

		if err := tftypes.ValidateValue(objectType, vals); err != nil {
			return tftypes.NewValue(objectType, tftypes.UnknownValue), err
		}

		return tftypes.NewValue(objectType, vals), nil
	case attr.ValueStateNull:
		return tftypes.NewValue(objectType, nil), nil
	case attr.ValueStateUnknown:
		return tftypes.NewValue(objectType, tftypes.UnknownValue), nil
	default:
		panic(fmt.Sprintf("unhandled Object state in ToTerraformValue: %s", v.state))
	}
}

func (v StorageAccountKeysValue) IsNull() bool {
	return v.state == attr.ValueStateNull
}

func (v StorageAccountKeysValue) IsUnknown() bool {
	return v.state == attr.ValueStateUnknown
}

func (v StorageAccountKeysValue) String() string {
	return "StorageAccountKeysValue"
}

func (v StorageAccountKeysValue) ToObjectValue(ctx context.Context) (basetypes.ObjectValue, diag.Diagnostics) {
	var diags diag.Diagnostics

	attributeTypes := map[string]attr.Type{
		"connection_string_wo":         basetypes.StringType{},
		"connection_string_wo_version": basetypes.Int64Type{},
	}

	if v.IsNull() {
		return types.ObjectNull(attributeTypes), diags
	}

	if v.IsUnknown() {
		return types.ObjectUnknown(attributeTypes), diags
	}

	objVal, diags := types.ObjectValue(
		attributeTypes,
		map[string]attr.Value{
			"connection_string_wo":         v.ConnectionStringWo,
			"connection_string_wo_version": v.ConnectionStringWoVersion,
		})

	return objVal, diags
}

func (v StorageAccountKeysValue) Equal(o attr.Value) bool {
	other, ok := o.(StorageAccountKeysValue)

	if !ok {
		return false
	}

	if v.state != other.state {
		return false
	}

	if v.state != attr.ValueStateKnown {
		return true
	}

	if !v.ConnectionStringWo.Equal(other.ConnectionStringWo) {
		return false
	}

	if !v.ConnectionStringWoVersion.Equal(other.ConnectionStringWoVersion) {
		return false
	}

	return true
}

func (v StorageAccountKeysValue) Type(ctx context.Context) attr.Type {
	return StorageAccountKeysType{
		basetypes.ObjectType{
			AttrTypes: v.AttributeTypes(ctx),
		},
	}
}

func (v StorageAccountKeysValue) AttributeTypes(ctx context.Context) map[string]attr.Type {
	return map[string]attr.Type{
		"connection_string_wo":         basetypes.StringType{},
		"connection_string_wo_version": basetypes.Int64Type{},
	}
}
