// Code generated by terraform-plugin-framework-generator DO NOT EDIT.

package resource_connection

import (
	"context"
	"github.com/hashicorp/terraform-plugin-framework-validators/listvalidator"
	"github.com/hashicorp/terraform-plugin-framework-validators/stringvalidator"
	"github.com/hashicorp/terraform-plugin-framework/schema/validator"
	"github.com/hashicorp/terraform-plugin-framework/types"

	"github.com/hashicorp/terraform-plugin-framework/resource/schema"
)

func ConnectionResourceSchema(ctx context.Context) schema.Schema {
	return schema.Schema{
		Attributes: map[string]schema.Attribute{
			"bi_container_id": schema.StringAttribute{
				Optional:            true,
				Computed:            true,
				Description:         "The BI container to add the connection to, for Tableau, Looker or Power BI credentials. Its type has to match what the credentials are for: a `looker` container takes both `looker` and `looker-git-clone` credentials. Send this or `warehouse_id`, not both.",
				MarkdownDescription: "The BI container to add the connection to, for Tableau, Looker or Power BI credentials. Its type has to match what the credentials are for: a `looker` container takes both `looker` and `looker-git-clone` credentials. Send this or `warehouse_id`, not both.",
			},
			"bi_container_name": schema.StringAttribute{
				Computed:            true,
				Description:         "Display name of that BI container. Null for a container that was never named, and for a connection on a warehouse.",
				MarkdownDescription: "Display name of that BI container. Null for a container that was never named, and for a connection on a warehouse.",
			},
			"connection_type": schema.StringAttribute{
				Computed:            true,
				Description:         "What the connection reaches, such as `snowflake`. Taken from the credentials the connection was created with, and fixed once created.",
				MarkdownDescription: "What the connection reaches, such as `snowflake`. Taken from the credentials the connection was created with, and fixed once created.",
			},
			"created_time": schema.StringAttribute{
				Computed:            true,
				Description:         "When the connection was created.",
				MarkdownDescription: "When the connection was created.",
			},
			"credentials_id": schema.StringAttribute{
				Required:            true,
				Description:         "The credentials the connection reads with. They also decide the connection's type. Create them first, through one of the credentials endpoints.",
				MarkdownDescription: "The credentials the connection reads with. They also decide the connection's type. Create them first, through one of the credentials endpoints.",
			},
			"credentials_storage_type": schema.StringAttribute{
				Computed:            true,
				Description:         "Where that secret lives. Null when there are no credentials to describe.",
				MarkdownDescription: "Where that secret lives. Null when there are no credentials to describe.",
			},
			"deployment_id": schema.StringAttribute{
				Computed:            true,
				Description:         "The deployment the connection runs through, taken from its warehouse or BI container. Null when that has no deployment. The id may name a deployment on Monte Carlo's older collection platform, which the deployments endpoints do not list.",
				MarkdownDescription: "The deployment the connection runs through, taken from its warehouse or BI container. Null when that has no deployment. The id may name a deployment on Monte Carlo's older collection platform, which the deployments endpoints do not list.",
			},
			"deployment_name": schema.StringAttribute{
				Computed:            true,
				Description:         "Display name of that deployment. Null when there is no deployment to name.",
				MarkdownDescription: "Display name of that deployment. Null when there is no deployment to name.",
			},
			"id": schema.StringAttribute{
				Computed:            true,
				Description:         "Unique identifier of the connection.",
				MarkdownDescription: "Unique identifier of the connection.",
			},
			"job_types": schema.ListAttribute{
				ElementType:         types.StringType,
				Optional:            true,
				Computed:            true,
				Description:         "The jobs to run on this connection. Omit it to run what the connection type runs by default, which is what the app does. Which values are accepted depends on the connection type. An empty list is not accepted; omit the field to take the defaults.",
				MarkdownDescription: "The jobs to run on this connection. Omit it to run what the connection type runs by default, which is what the app does. Which values are accepted depends on the connection type. An empty list is not accepted; omit the field to take the defaults.",
				Validators: []validator.List{
					listvalidator.SizeAtLeast(1),
				},
			},
			"name": schema.StringAttribute{
				Required:            true,
				Description:         "Display name for the connection. Unique among the connections of its warehouse or BI container.",
				MarkdownDescription: "Display name for the connection. Unique among the connections of its warehouse or BI container.",
				Validators: []validator.String{
					stringvalidator.LengthBetween(1, 200),
				},
			},
			"warehouse_id": schema.StringAttribute{
				Optional:            true,
				Computed:            true,
				Description:         "The warehouse to add the connection to. Its type has to match what the credentials are for. Send this or `bi_container_id`, not both.",
				MarkdownDescription: "The warehouse to add the connection to. Its type has to match what the credentials are for. Send this or `bi_container_id`, not both.",
			},
			"warehouse_name": schema.StringAttribute{
				Computed:            true,
				Description:         "Display name of that warehouse. Null for a warehouse that was never named, and for a connection on a BI container.",
				MarkdownDescription: "Display name of that warehouse. Null for a warehouse that was never named, and for a connection on a BI container.",
			},
		},
		Description:         "A connection lets Monte Carlo reach a warehouse's data platform or a BI container's BI tool with one set of credentials. It belongs to a warehouse or a BI container and takes its type from the credentials it references.",
		MarkdownDescription: "A connection lets Monte Carlo reach a warehouse's data platform or a BI container's BI tool with one set of credentials. It belongs to a warehouse or a BI container and takes its type from the credentials it references.",
	}
}

type ConnectionModel struct {
	BiContainerId          types.String `tfsdk:"bi_container_id"`
	BiContainerName        types.String `tfsdk:"bi_container_name"`
	ConnectionType         types.String `tfsdk:"connection_type"`
	CreatedTime            types.String `tfsdk:"created_time"`
	CredentialsId          types.String `tfsdk:"credentials_id"`
	CredentialsStorageType types.String `tfsdk:"credentials_storage_type"`
	DeploymentId           types.String `tfsdk:"deployment_id"`
	DeploymentName         types.String `tfsdk:"deployment_name"`
	Id                     types.String `tfsdk:"id"`
	JobTypes               types.List   `tfsdk:"job_types"`
	Name                   types.String `tfsdk:"name"`
	WarehouseId            types.String `tfsdk:"warehouse_id"`
	WarehouseName          types.String `tfsdk:"warehouse_name"`
}
