// Code generated by terraform-plugin-framework-generator DO NOT EDIT.

package datasource_gcp_dataform_credentials

import (
	"context"
	"github.com/hashicorp/terraform-plugin-framework/types"

	"github.com/hashicorp/terraform-plugin-framework/datasource/schema"
)

func GcpDataformCredentialsDataSourceSchema(ctx context.Context) schema.Schema {
	return schema.Schema{
		Attributes: map[string]schema.Attribute{
			"client_email": schema.StringAttribute{
				Computed:            true,
				Description:         "Email address of the service account.",
				MarkdownDescription: "Email address of the service account.",
			},
			"connection_type": schema.StringAttribute{
				Computed:            true,
				Description:         "The connection type the credentials are for, such as `snowflake`. Fixed once created.",
				MarkdownDescription: "The connection type the credentials are for, such as `snowflake`. Fixed once created.",
			},
			"created_time": schema.StringAttribute{
				Computed:            true,
				Description:         "When the credentials were created.",
				MarkdownDescription: "When the credentials were created.",
			},
			"credentials_id": schema.StringAttribute{
				Required: true,
			},
			"id": schema.StringAttribute{
				Computed:            true,
				Description:         "Unique identifier of the credentials.",
				MarkdownDescription: "Unique identifier of the credentials.",
			},
			"locations": schema.ListAttribute{
				ElementType:         types.StringType,
				Computed:            true,
				Description:         "Google Cloud regions to read Dataform repositories in, such as us-central1.",
				MarkdownDescription: "Google Cloud regions to read Dataform repositories in, such as us-central1.",
			},
			"project_id": schema.StringAttribute{
				Computed:            true,
				Description:         "Google Cloud project that holds the Dataform repositories.",
				MarkdownDescription: "Google Cloud project that holds the Dataform repositories.",
			},
			"storage_type": schema.StringAttribute{
				Computed:            true,
				Description:         "Where the secret lives. Fixed once created.",
				MarkdownDescription: "Where the secret lives. Fixed once created.",
			},
		},
	}
}

type GcpDataformCredentialsModel struct {
	ClientEmail    types.String `tfsdk:"client_email"`
	ConnectionType types.String `tfsdk:"connection_type"`
	CreatedTime    types.String `tfsdk:"created_time"`
	CredentialsId  types.String `tfsdk:"credentials_id"`
	Id             types.String `tfsdk:"id"`
	Locations      types.List   `tfsdk:"locations"`
	ProjectId      types.String `tfsdk:"project_id"`
	StorageType    types.String `tfsdk:"storage_type"`
}
