// Code generated by terraform-plugin-framework-generator DO NOT EDIT.

package datasource_snowflake_credentials

import (
	"context"
	"github.com/hashicorp/terraform-plugin-framework/types"

	"github.com/hashicorp/terraform-plugin-framework/datasource/schema"
)

func SnowflakeCredentialsDataSourceSchema(ctx context.Context) schema.Schema {
	return schema.Schema{
		Attributes: map[string]schema.Attribute{
			"account": schema.StringAttribute{
				Computed:            true,
				Description:         "Snowflake account identifier, without the host suffix.",
				MarkdownDescription: "Snowflake account identifier, without the host suffix.",
			},
			"connection_type": schema.StringAttribute{
				Computed:            true,
				Description:         "The connection type the credentials are for, such as `snowflake`. Fixed once created.",
				MarkdownDescription: "The connection type the credentials are for, such as `snowflake`. Fixed once created.",
			},
			"created_time": schema.StringAttribute{
				Computed:            true,
				Description:         "When the credentials were created.",
				MarkdownDescription: "When the credentials were created.",
			},
			"credentials_id": schema.StringAttribute{
				Required:            true,
				Description:         "Id of the credentials, as returned when they are created or listed.",
				MarkdownDescription: "Id of the credentials, as returned when they are created or listed.",
			},
			"id": schema.StringAttribute{
				Computed:            true,
				Description:         "Unique identifier of the credentials.",
				MarkdownDescription: "Unique identifier of the credentials.",
			},
			"storage_type": schema.StringAttribute{
				Computed:            true,
				Description:         "Where the secret lives. Fixed once created.",
				MarkdownDescription: "Where the secret lives. Fixed once created.",
			},
			"user": schema.StringAttribute{
				Computed:            true,
				Description:         "Snowflake user the key pair belongs to.",
				MarkdownDescription: "Snowflake user the key pair belongs to.",
			},
			"warehouse": schema.StringAttribute{
				Computed:            true,
				Description:         "Snowflake virtual warehouse queries run in. Null when none is set.",
				MarkdownDescription: "Snowflake virtual warehouse queries run in. Null when none is set.",
			},
		},
		Description:         "Snowflake credentials are a key pair Monte Carlo stores for Snowflake connections to use. The private key is never returned.",
		MarkdownDescription: "Snowflake credentials are a key pair Monte Carlo stores for Snowflake connections to use. The private key is never returned.",
	}
}

type SnowflakeCredentialsModel struct {
	Account        types.String `tfsdk:"account"`
	ConnectionType types.String `tfsdk:"connection_type"`
	CreatedTime    types.String `tfsdk:"created_time"`
	CredentialsId  types.String `tfsdk:"credentials_id"`
	Id             types.String `tfsdk:"id"`
	StorageType    types.String `tfsdk:"storage_type"`
	User           types.String `tfsdk:"user"`
	Warehouse      types.String `tfsdk:"warehouse"`
}
