// Code generated by terraform-plugin-framework-generator DO NOT EDIT.

package resource_generic_collection_agent_token

import (
	"context"
	"github.com/hashicorp/terraform-plugin-framework-validators/stringvalidator"
	"github.com/hashicorp/terraform-plugin-framework/schema/validator"
	"github.com/hashicorp/terraform-plugin-framework/types"

	"github.com/hashicorp/terraform-plugin-framework/resource/schema"
)

func GenericCollectionAgentTokenResourceSchema(ctx context.Context) schema.Schema {
	return schema.Schema{
		Attributes: map[string]schema.Attribute{
			"created_time": schema.StringAttribute{
				Computed:            true,
				Description:         "When the credential was created.",
				MarkdownDescription: "When the credential was created.",
			},
			"deployment_id": schema.StringAttribute{
				Required:            true,
				Description:         "Deployment whose generic collection agent will present this credential. It must have been provisioned for a generic collection agent.",
				MarkdownDescription: "Deployment whose generic collection agent will present this credential. It must have been provisioned for a generic collection agent.",
			},
			"description": schema.StringAttribute{
				Optional:            true,
				Computed:            true,
				Description:         "What this credential is for.",
				MarkdownDescription: "What this credential is for.",
				Validators: []validator.String{
					stringvalidator.LengthAtMost(200),
				},
			},
			"id": schema.StringAttribute{
				Computed:            true,
				Description:         "Unique identifier of the credential. For a token this is also its key id; for an OAuth client, its client id.",
				MarkdownDescription: "Unique identifier of the credential. For a token this is also its key id; for an OAuth client, its client id.",
			},
			"mcd_id": schema.StringAttribute{
				Computed:            true,
				Description:         "Key id the agent presents, as `mcd_id` in its configuration. The same value as `id`.",
				MarkdownDescription: "Key id the agent presents, as `mcd_id` in its configuration. The same value as `id`.",
			},
			"mcd_token": schema.StringAttribute{
				Computed:            true,
				Sensitive:           true,
				Description:         "Secret the agent presents, as `mcd_token` in its configuration. Returned once, by this call. It is not retrievable afterwards, and Terraform holds it in state like any generated credential. To rotate, create a new credential and delete this one.",
				MarkdownDescription: "Secret the agent presents, as `mcd_token` in its configuration. Returned once, by this call. It is not retrievable afterwards, and Terraform holds it in state like any generated credential. To rotate, create a new credential and delete this one.",
			},
			"type": schema.StringAttribute{
				Computed:            true,
				Description:         "The kind of credential a generic collection agent presents to Monte Carlo.\n\n`TOKEN` is a key id and secret the agent sends as headers. `OAUTH_CLIENT` is an OAuth 2.0\nclient the agent exchanges for short-lived access tokens.",
				MarkdownDescription: "The kind of credential a generic collection agent presents to Monte Carlo.\n\n`TOKEN` is a key id and secret the agent sends as headers. `OAUTH_CLIENT` is an OAuth 2.0\nclient the agent exchanges for short-lived access tokens.",
			},
		},
	}
}

type GenericCollectionAgentTokenModel struct {
	CreatedTime  types.String `tfsdk:"created_time"`
	DeploymentId types.String `tfsdk:"deployment_id"`
	Description  types.String `tfsdk:"description"`
	Id           types.String `tfsdk:"id"`
	McdId        types.String `tfsdk:"mcd_id"`
	McdToken     types.String `tfsdk:"mcd_token"`
	Type         types.String `tfsdk:"type"`
}
