// Code generated by api-codegen; DO NOT EDIT.
package provider

import (
	"context"
	"fmt"
	"net/http"

	"github.com/hashicorp/terraform-plugin-framework/path"
	"github.com/hashicorp/terraform-plugin-framework/resource"
	"github.com/hashicorp/terraform-plugin-framework/types"
	"time"

	sdk "github.com/monte-carlo-data/mc-sdk-go/montecarlo"
	"github.com/monte-carlo-data/terraform-provider-montecarlo/internal/schema_gen/resource_airflow_credentials"
)

var (
	_ resource.Resource                = (*airflowCredentialsResource)(nil)
	_ resource.ResourceWithConfigure   = (*airflowCredentialsResource)(nil)
	_ resource.ResourceWithImportState = (*airflowCredentialsResource)(nil)
)

type airflowCredentialsResource struct{ clients *clients }

func NewAirflowCredentialsResource() resource.Resource { return &airflowCredentialsResource{} }

func (r *airflowCredentialsResource) Metadata(_ context.Context, req resource.MetadataRequest, resp *resource.MetadataResponse) {
	resp.TypeName = req.ProviderTypeName + "_airflow_credentials"
}

func (r *airflowCredentialsResource) Schema(ctx context.Context, _ resource.SchemaRequest, resp *resource.SchemaResponse) {
	s := resource_airflow_credentials.AirflowCredentialsResourceSchema(ctx)
	// Updating the resource never changes these, and a null in state is final. Only the plain modifier copies a null.
	useStateForUnknown(s.Attributes, "airflow_credentials.connection_type", &resp.Diagnostics)
	useStateForUnknown(s.Attributes, "airflow_credentials.created_time", &resp.Diagnostics)
	useStateForUnknown(s.Attributes, "airflow_credentials.id", &resp.Diagnostics)
	useStateForUnknown(s.Attributes, "airflow_credentials.storage_type", &resp.Diagnostics)
	resp.Schema = s
}

func (r *airflowCredentialsResource) Configure(_ context.Context, req resource.ConfigureRequest, resp *resource.ConfigureResponse) {
	if req.ProviderData == nil {
		return
	}
	c, ok := req.ProviderData.(*clients)
	if !ok {
		resp.Diagnostics.AddError("unexpected provider data", fmt.Sprintf("got %T", req.ProviderData))
		return
	}
	r.clients = c
}

func (r *airflowCredentialsResource) Create(ctx context.Context, req resource.CreateRequest, resp *resource.CreateResponse) {
	ctx = sdk.WithTelemetryCommand(ctx, "montecarlo_airflow_credentials create")
	var plan resource_airflow_credentials.AirflowCredentialsModel
	resp.Diagnostics.Append(req.Plan.Get(ctx, &plan)...)
	if resp.Diagnostics.HasError() {
		return
	}
	body := sdk.NewAirflowCredentialsIn(plan.HostName.ValueString())
	// Retried: the spec marks this operation x-mc-retry-on-transient.
	out, err := withRetryOnTransient(ctx, func() (*sdk.AirflowCredentialsOut, *http.Response, error) {
		return r.clients.api.CredentialsAPI.CreateAirflowCredentials(ctx).AirflowCredentialsIn(*body).Execute()
	})
	if err != nil {
		resp.Diagnostics.AddError("Create airflow_credentials failed", apiErr(err))
		return
	}
	resp.Diagnostics.Append(resp.State.Set(ctx, airflowCredentialsToModel(out))...)
}

func (r *airflowCredentialsResource) Read(ctx context.Context, req resource.ReadRequest, resp *resource.ReadResponse) {
	ctx = sdk.WithTelemetryCommand(ctx, "montecarlo_airflow_credentials read")
	var state resource_airflow_credentials.AirflowCredentialsModel
	resp.Diagnostics.Append(req.State.Get(ctx, &state)...)
	if resp.Diagnostics.HasError() {
		return
	}
	out, httpResp, err := r.clients.api.CredentialsAPI.GetAirflowCredentials(ctx, state.Id.ValueString()).Execute()
	if err != nil {
		if httpResp != nil && httpResp.StatusCode == 404 {
			resp.State.RemoveResource(ctx)
			return
		}
		resp.Diagnostics.AddError("Read airflow_credentials failed", apiErr(err))
		return
	}
	resp.Diagnostics.Append(resp.State.Set(ctx, airflowCredentialsToModel(out))...)
}

func (r *airflowCredentialsResource) Update(ctx context.Context, req resource.UpdateRequest, resp *resource.UpdateResponse) {
	ctx = sdk.WithTelemetryCommand(ctx, "montecarlo_airflow_credentials update")
	var plan, state resource_airflow_credentials.AirflowCredentialsModel
	resp.Diagnostics.Append(req.Plan.Get(ctx, &plan)...)
	resp.Diagnostics.Append(req.State.Get(ctx, &state)...)
	if resp.Diagnostics.HasError() {
		return
	}
	body := sdk.NewAirflowCredentialsPatch()
	if !plan.HostName.IsNull() && !plan.HostName.IsUnknown() {
		body.SetHostName(plan.HostName.ValueString())
	}
	// Retried: the spec marks this operation x-mc-retry-on-transient.
	out, err := withRetryOnTransient(ctx, func() (*sdk.AirflowCredentialsOut, *http.Response, error) {
		return r.clients.api.CredentialsAPI.UpdateAirflowCredentials(ctx, state.Id.ValueString()).AirflowCredentialsPatch(*body).Execute()
	})
	if err != nil {
		resp.Diagnostics.AddError("Update airflow_credentials failed", apiErr(err))
		return
	}
	resp.Diagnostics.Append(resp.State.Set(ctx, airflowCredentialsToModel(out))...)
}

func (r *airflowCredentialsResource) Delete(ctx context.Context, req resource.DeleteRequest, resp *resource.DeleteResponse) {
	ctx = sdk.WithTelemetryCommand(ctx, "montecarlo_airflow_credentials delete")
	var state resource_airflow_credentials.AirflowCredentialsModel
	resp.Diagnostics.Append(req.State.Get(ctx, &state)...)
	if resp.Diagnostics.HasError() {
		return
	}
	if _, err := r.clients.api.CredentialsAPI.DeleteAirflowCredentials(ctx, state.Id.ValueString()).Execute(); err != nil {
		resp.Diagnostics.AddError("Delete airflow_credentials failed", apiErr(err))
	}
}

func (r *airflowCredentialsResource) ImportState(ctx context.Context, req resource.ImportStateRequest, resp *resource.ImportStateResponse) {
	resource.ImportStatePassthroughID(ctx, path.Root("id"), req, resp)
}

func airflowCredentialsToModel(o *sdk.AirflowCredentialsOut) resource_airflow_credentials.AirflowCredentialsModel {
	m := resource_airflow_credentials.AirflowCredentialsModel{
		ConnectionType: types.StringValue(o.GetConnectionType()),
		CreatedTime:    types.StringValue(o.GetCreatedTime().Format(time.RFC3339)),
		HostName:       types.StringValue(o.GetHostName()),
		Id:             types.StringValue(o.GetId()),
		StorageType:    types.StringValue(string(o.GetStorageType())),
	}
	return m
}
