// Code generated by api-codegen; DO NOT EDIT.
package provider

import (
	"context"
	"fmt"
	"net/http"

	"github.com/hashicorp/terraform-plugin-framework/path"
	"github.com/hashicorp/terraform-plugin-framework/resource"
	"github.com/hashicorp/terraform-plugin-framework/types"
	"time"

	sdk "github.com/monte-carlo-data/mc-sdk-go"
	"github.com/monte-carlo-data/terraform-provider-montecarlo/internal/schema_gen/resource_aws_collection_data_store"
)

var (
	_ resource.Resource                = (*awsCollectionDataStoreResource)(nil)
	_ resource.ResourceWithConfigure   = (*awsCollectionDataStoreResource)(nil)
	_ resource.ResourceWithImportState = (*awsCollectionDataStoreResource)(nil)
)

type awsCollectionDataStoreResource struct{ clients *clients }

func NewAwsCollectionDataStoreResource() resource.Resource { return &awsCollectionDataStoreResource{} }

func (r *awsCollectionDataStoreResource) Metadata(_ context.Context, req resource.MetadataRequest, resp *resource.MetadataResponse) {
	resp.TypeName = req.ProviderTypeName + "_aws_collection_data_store"
}

func (r *awsCollectionDataStoreResource) Schema(ctx context.Context, _ resource.SchemaRequest, resp *resource.SchemaResponse) {
	s := resource_aws_collection_data_store.AwsCollectionDataStoreResourceSchema(ctx)
	// The API accepts these on create and not on update, so changing one replaces the
	// resource. tfplugingen does not know that, so requiresReplace says it here.
	requiresReplace(s.Attributes, "aws_collection_data_store.deployment_id", &resp.Diagnostics)
	resp.Schema = s
}

func (r *awsCollectionDataStoreResource) Configure(_ context.Context, req resource.ConfigureRequest, resp *resource.ConfigureResponse) {
	if req.ProviderData == nil {
		return
	}
	c, ok := req.ProviderData.(*clients)
	if !ok {
		resp.Diagnostics.AddError("unexpected provider data", fmt.Sprintf("got %T", req.ProviderData))
		return
	}
	r.clients = c
}

func (r *awsCollectionDataStoreResource) Create(ctx context.Context, req resource.CreateRequest, resp *resource.CreateResponse) {
	var plan resource_aws_collection_data_store.AwsCollectionDataStoreModel
	resp.Diagnostics.Append(req.Plan.Get(ctx, &plan)...)
	if resp.Diagnostics.HasError() {
		return
	}
	body := sdk.NewAwsCollectionDataStoreIn(plan.BucketName.ValueString(), plan.DeploymentId.ValueString(), plan.RoleArn.ValueString())
	if !plan.Name.IsNull() && !plan.Name.IsUnknown() {
		body.SetName(plan.Name.ValueString())
	}
	// x-mc-terraform-retry-on-transient
	out, err := withRetryOnTransient(ctx, func() (*sdk.AwsCollectionDataStoreOut, *http.Response, error) {
		return r.clients.api.CollectionDataStoresAPI.RegisterAwsCollectionDataStore(ctx).AwsCollectionDataStoreIn(*body).Execute()
	})
	if err != nil {
		resp.Diagnostics.AddError("Create aws_collection_data_store failed", apiErr(err))
		return
	}
	resp.Diagnostics.Append(resp.State.Set(ctx, awsCollectionDataStoreToModel(out, plan.RoleArn))...)
}

func (r *awsCollectionDataStoreResource) Read(ctx context.Context, req resource.ReadRequest, resp *resource.ReadResponse) {
	var state resource_aws_collection_data_store.AwsCollectionDataStoreModel
	resp.Diagnostics.Append(req.State.Get(ctx, &state)...)
	if resp.Diagnostics.HasError() {
		return
	}
	out, httpResp, err := r.clients.api.CollectionDataStoresAPI.GetAwsCollectionDataStore(ctx, state.Id.ValueString()).Execute()
	if err != nil {
		if httpResp != nil && httpResp.StatusCode == 404 {
			resp.State.RemoveResource(ctx)
			return
		}
		resp.Diagnostics.AddError("Read aws_collection_data_store failed", apiErr(err))
		return
	}
	resp.Diagnostics.Append(resp.State.Set(ctx, awsCollectionDataStoreToModel(out, state.RoleArn))...)
}

func (r *awsCollectionDataStoreResource) Update(ctx context.Context, req resource.UpdateRequest, resp *resource.UpdateResponse) {
	var plan, state resource_aws_collection_data_store.AwsCollectionDataStoreModel
	resp.Diagnostics.Append(req.Plan.Get(ctx, &plan)...)
	resp.Diagnostics.Append(req.State.Get(ctx, &state)...)
	if resp.Diagnostics.HasError() {
		return
	}
	body := sdk.NewAwsCollectionDataStorePatch()
	body.SetBucketName(plan.BucketName.ValueString())
	body.SetName(plan.Name.ValueString())
	body.SetRoleArn(plan.RoleArn.ValueString())
	// x-mc-terraform-retry-on-transient
	out, err := withRetryOnTransient(ctx, func() (*sdk.AwsCollectionDataStoreOut, *http.Response, error) {
		return r.clients.api.CollectionDataStoresAPI.UpdateAwsCollectionDataStore(ctx, state.Id.ValueString()).AwsCollectionDataStorePatch(*body).Execute()
	})
	if err != nil {
		resp.Diagnostics.AddError("Update aws_collection_data_store failed", apiErr(err))
		return
	}
	resp.Diagnostics.Append(resp.State.Set(ctx, awsCollectionDataStoreToModel(out, plan.RoleArn))...)
}

func (r *awsCollectionDataStoreResource) Delete(ctx context.Context, req resource.DeleteRequest, resp *resource.DeleteResponse) {
	var state resource_aws_collection_data_store.AwsCollectionDataStoreModel
	resp.Diagnostics.Append(req.State.Get(ctx, &state)...)
	if resp.Diagnostics.HasError() {
		return
	}
	if _, err := r.clients.api.CollectionDataStoresAPI.DeleteAwsCollectionDataStore(ctx, state.Id.ValueString()).Execute(); err != nil {
		resp.Diagnostics.AddError("Delete aws_collection_data_store failed", apiErr(err))
	}
}

func (r *awsCollectionDataStoreResource) ImportState(ctx context.Context, req resource.ImportStateRequest, resp *resource.ImportStateResponse) {
	resource.ImportStatePassthroughID(ctx, path.Root("id"), req, resp)
}

func awsCollectionDataStoreToModel(o *sdk.AwsCollectionDataStoreOut, role_arn types.String) resource_aws_collection_data_store.AwsCollectionDataStoreModel {
	m := resource_aws_collection_data_store.AwsCollectionDataStoreModel{
		AuthenticationType: types.StringValue(string(o.GetAuthenticationType())),
		BucketName:         types.StringValue(o.GetBucketName()),
		DeploymentId:       types.StringValue(o.GetDeploymentId()),
		Enabled:            types.BoolValue(o.GetEnabled()),
		Id:                 types.StringValue(o.GetId()),
		StorageType:        types.StringValue(string(o.GetStorageType())),
		RoleArn:            role_arn,
	}
	if v, ok := o.GetCreatedTimeOk(); ok && v != nil {
		m.CreatedTime = types.StringValue(v.Format(time.RFC3339))
	} else {
		m.CreatedTime = types.StringNull()
	}
	if v, ok := o.GetExternalIdOk(); ok && v != nil {
		m.ExternalId = types.StringValue(*v)
	} else {
		m.ExternalId = types.StringNull()
	}
	if v, ok := o.GetLastUpdatedTimeOk(); ok && v != nil {
		m.LastUpdatedTime = types.StringValue(v.Format(time.RFC3339))
	} else {
		m.LastUpdatedTime = types.StringNull()
	}
	if v, ok := o.GetNameOk(); ok && v != nil {
		m.Name = types.StringValue(*v)
	} else {
		m.Name = types.StringNull()
	}
	// Optional+Computed write-only field omitted from config -> plan value is unknown,
	// and the response never carries it, so resolve it to null (never leave it unknown).
	if role_arn.IsUnknown() {
		m.RoleArn = types.StringNull()
	}
	return m
}
