// Code generated by api-codegen; DO NOT EDIT.
package provider

import (
	"context"
	"fmt"
	"net/http"

	"github.com/hashicorp/terraform-plugin-framework/path"
	"github.com/hashicorp/terraform-plugin-framework/resource"
	"github.com/hashicorp/terraform-plugin-framework/types"
	"time"

	sdk "github.com/monte-carlo-data/mc-sdk-go/montecarlo"
	"github.com/monte-carlo-data/terraform-provider-montecarlo/internal/schema_gen/resource_azure_collection_data_store"
)

var (
	_ resource.Resource                = (*azureCollectionDataStoreResource)(nil)
	_ resource.ResourceWithConfigure   = (*azureCollectionDataStoreResource)(nil)
	_ resource.ResourceWithImportState = (*azureCollectionDataStoreResource)(nil)
)

type azureCollectionDataStoreResource struct{ clients *clients }

func NewAzureCollectionDataStoreResource() resource.Resource {
	return &azureCollectionDataStoreResource{}
}

func (r *azureCollectionDataStoreResource) Metadata(_ context.Context, req resource.MetadataRequest, resp *resource.MetadataResponse) {
	resp.TypeName = req.ProviderTypeName + "_azure_collection_data_store"
}

func (r *azureCollectionDataStoreResource) Schema(ctx context.Context, _ resource.SchemaRequest, resp *resource.SchemaResponse) {
	s := resource_azure_collection_data_store.AzureCollectionDataStoreResourceSchema(ctx)
	// The API accepts these on create and not on update, so changing one replaces the
	// resource. tfplugingen does not know that, so requiresReplace says it here.
	requiresReplace(s.Attributes, "azure_collection_data_store.deployment_id", &resp.Diagnostics)
	// Updating the resource never changes these, so the plan keeps what state holds. Left
	// unknown, a reference to one of them would replace whatever resource reads it.
	useNonNullStateForUnknown(s.Attributes, "azure_collection_data_store.created_time", &resp.Diagnostics)
	useNonNullStateForUnknown(s.Attributes, "azure_collection_data_store.id", &resp.Diagnostics)
	resp.Schema = s
}

func (r *azureCollectionDataStoreResource) Configure(_ context.Context, req resource.ConfigureRequest, resp *resource.ConfigureResponse) {
	if req.ProviderData == nil {
		return
	}
	c, ok := req.ProviderData.(*clients)
	if !ok {
		resp.Diagnostics.AddError("unexpected provider data", fmt.Sprintf("got %T", req.ProviderData))
		return
	}
	r.clients = c
}

func (r *azureCollectionDataStoreResource) Create(ctx context.Context, req resource.CreateRequest, resp *resource.CreateResponse) {
	var plan resource_azure_collection_data_store.AzureCollectionDataStoreModel
	resp.Diagnostics.Append(req.Plan.Get(ctx, &plan)...)
	if resp.Diagnostics.HasError() {
		return
	}
	body := sdk.NewAzureCollectionDataStoreIn(sdk.AzureDataStoreAuthenticationType(plan.AuthenticationType.ValueString()), plan.ContainerName.ValueString(), plan.DeploymentId.ValueString())
	if !plan.Name.IsNull() && !plan.Name.IsUnknown() {
		body.SetName(plan.Name.ValueString())
	}
	if !plan.ServicePrincipal.IsNull() && !plan.ServicePrincipal.IsUnknown() {
		nested := sdk.NewStorageServicePrincipalCredentialsIn(plan.ServicePrincipal.AccountUrl.ValueString(), plan.ServicePrincipal.ClientId.ValueString(), plan.ServicePrincipal.ClientSecret.ValueString(), plan.ServicePrincipal.TenantId.ValueString())
		if !plan.ServicePrincipal.AccountName.IsNull() && !plan.ServicePrincipal.AccountName.IsUnknown() {
			nested.SetAccountName(plan.ServicePrincipal.AccountName.ValueString())
		}
		body.SetServicePrincipal(*nested)
	}
	if !plan.StorageAccountKeys.IsNull() && !plan.StorageAccountKeys.IsUnknown() {
		nested := sdk.NewStorageAccountKeysCredentialsIn(plan.StorageAccountKeys.ConnectionString.ValueString())
		body.SetStorageAccountKeys(*nested)
	}
	// Retried: the spec marks this operation x-mc-terraform-retry-on-transient.
	out, err := withRetryOnTransient(ctx, func() (*sdk.AzureCollectionDataStoreOut, *http.Response, error) {
		return r.clients.api.CollectionDataStoresAPI.RegisterAzureCollectionDataStore(ctx).AzureCollectionDataStoreIn(*body).Execute()
	})
	if err != nil {
		resp.Diagnostics.AddError("Create azure_collection_data_store failed", apiErr(err))
		return
	}
	m := azureCollectionDataStoreToModel(out)
	applyAzureCollectionDataStoreNested(&m, plan)
	resp.Diagnostics.Append(resp.State.Set(ctx, m)...)
}

func (r *azureCollectionDataStoreResource) Read(ctx context.Context, req resource.ReadRequest, resp *resource.ReadResponse) {
	var state resource_azure_collection_data_store.AzureCollectionDataStoreModel
	resp.Diagnostics.Append(req.State.Get(ctx, &state)...)
	if resp.Diagnostics.HasError() {
		return
	}
	out, httpResp, err := r.clients.api.CollectionDataStoresAPI.GetAzureCollectionDataStore(ctx, state.Id.ValueString()).Execute()
	if err != nil {
		if httpResp != nil && httpResp.StatusCode == 404 {
			resp.State.RemoveResource(ctx)
			return
		}
		resp.Diagnostics.AddError("Read azure_collection_data_store failed", apiErr(err))
		return
	}
	m := azureCollectionDataStoreToModel(out)
	applyAzureCollectionDataStoreNested(&m, state)
	resp.Diagnostics.Append(resp.State.Set(ctx, m)...)
}

func (r *azureCollectionDataStoreResource) Update(ctx context.Context, req resource.UpdateRequest, resp *resource.UpdateResponse) {
	var plan, state resource_azure_collection_data_store.AzureCollectionDataStoreModel
	resp.Diagnostics.Append(req.Plan.Get(ctx, &plan)...)
	resp.Diagnostics.Append(req.State.Get(ctx, &state)...)
	if resp.Diagnostics.HasError() {
		return
	}
	body := sdk.NewAzureCollectionDataStorePatch()
	if !plan.AuthenticationType.IsNull() && !plan.AuthenticationType.IsUnknown() {
		body.SetAuthenticationType(sdk.AzureDataStoreAuthenticationType(plan.AuthenticationType.ValueString()))
	}
	if !plan.ContainerName.IsNull() && !plan.ContainerName.IsUnknown() {
		body.SetContainerName(plan.ContainerName.ValueString())
	}
	if !plan.Name.IsNull() && !plan.Name.IsUnknown() {
		body.SetName(plan.Name.ValueString())
	}
	if !plan.ServicePrincipal.IsNull() && !plan.ServicePrincipal.IsUnknown() {
		nested := sdk.NewStorageServicePrincipalCredentialsIn(plan.ServicePrincipal.AccountUrl.ValueString(), plan.ServicePrincipal.ClientId.ValueString(), plan.ServicePrincipal.ClientSecret.ValueString(), plan.ServicePrincipal.TenantId.ValueString())
		if !plan.ServicePrincipal.AccountName.IsNull() && !plan.ServicePrincipal.AccountName.IsUnknown() {
			nested.SetAccountName(plan.ServicePrincipal.AccountName.ValueString())
		}
		body.SetServicePrincipal(*nested)
	}
	if !plan.StorageAccountKeys.IsNull() && !plan.StorageAccountKeys.IsUnknown() {
		nested := sdk.NewStorageAccountKeysCredentialsIn(plan.StorageAccountKeys.ConnectionString.ValueString())
		body.SetStorageAccountKeys(*nested)
	}
	// Retried: the spec marks this operation x-mc-terraform-retry-on-transient.
	out, err := withRetryOnTransient(ctx, func() (*sdk.AzureCollectionDataStoreOut, *http.Response, error) {
		return r.clients.api.CollectionDataStoresAPI.UpdateAzureCollectionDataStore(ctx, state.Id.ValueString()).AzureCollectionDataStorePatch(*body).Execute()
	})
	if err != nil {
		resp.Diagnostics.AddError("Update azure_collection_data_store failed", apiErr(err))
		return
	}
	m := azureCollectionDataStoreToModel(out)
	applyAzureCollectionDataStoreNested(&m, plan)
	resp.Diagnostics.Append(resp.State.Set(ctx, m)...)
}

func (r *azureCollectionDataStoreResource) Delete(ctx context.Context, req resource.DeleteRequest, resp *resource.DeleteResponse) {
	var state resource_azure_collection_data_store.AzureCollectionDataStoreModel
	resp.Diagnostics.Append(req.State.Get(ctx, &state)...)
	if resp.Diagnostics.HasError() {
		return
	}
	if _, err := r.clients.api.CollectionDataStoresAPI.DeleteAzureCollectionDataStore(ctx, state.Id.ValueString()).Execute(); err != nil {
		resp.Diagnostics.AddError("Delete azure_collection_data_store failed", apiErr(err))
	}
}

func (r *azureCollectionDataStoreResource) ImportState(ctx context.Context, req resource.ImportStateRequest, resp *resource.ImportStateResponse) {
	resource.ImportStatePassthroughID(ctx, path.Root("id"), req, resp)
}

// applyAzureCollectionDataStoreNested copies the write-only nested credential blocks from src (plan on create,
// state on read) into m. These blocks are Optional+Computed and never returned by the API, so an
// omitted block — or an omitted optional sub-field — arrives unknown; resolve those to null so the
// applied result is fully known (Terraform rejects unknowns after apply).
func applyAzureCollectionDataStoreNested(m *resource_azure_collection_data_store.AzureCollectionDataStoreModel, src resource_azure_collection_data_store.AzureCollectionDataStoreModel) {
	if src.ServicePrincipal.IsNull() || src.ServicePrincipal.IsUnknown() {
		m.ServicePrincipal = resource_azure_collection_data_store.NewServicePrincipalValueNull()
	} else {
		v := src.ServicePrincipal
		if v.AccountName.IsUnknown() {
			v.AccountName = types.StringNull()
		}
		if v.AccountUrl.IsUnknown() {
			v.AccountUrl = types.StringNull()
		}
		if v.ClientId.IsUnknown() {
			v.ClientId = types.StringNull()
		}
		if v.ClientSecret.IsUnknown() {
			v.ClientSecret = types.StringNull()
		}
		if v.TenantId.IsUnknown() {
			v.TenantId = types.StringNull()
		}
		m.ServicePrincipal = v
	}
	if src.StorageAccountKeys.IsNull() || src.StorageAccountKeys.IsUnknown() {
		m.StorageAccountKeys = resource_azure_collection_data_store.NewStorageAccountKeysValueNull()
	} else {
		v := src.StorageAccountKeys
		if v.ConnectionString.IsUnknown() {
			v.ConnectionString = types.StringNull()
		}
		m.StorageAccountKeys = v
	}
}

func azureCollectionDataStoreToModel(o *sdk.AzureCollectionDataStoreOut) resource_azure_collection_data_store.AzureCollectionDataStoreModel {
	m := resource_azure_collection_data_store.AzureCollectionDataStoreModel{
		AuthenticationType: types.StringValue(string(o.GetAuthenticationType())),
		ContainerName:      types.StringValue(o.GetContainerName()),
		DeploymentId:       types.StringValue(o.GetDeploymentId()),
		Enabled:            types.BoolValue(o.GetEnabled()),
		Id:                 types.StringValue(o.GetId()),
		StorageType:        types.StringValue(string(o.GetStorageType())),
	}
	if v, ok := o.GetCreatedTimeOk(); ok && v != nil {
		m.CreatedTime = types.StringValue(v.Format(time.RFC3339))
	} else {
		m.CreatedTime = types.StringNull()
	}
	if v, ok := o.GetLastUpdatedTimeOk(); ok && v != nil {
		m.LastUpdatedTime = types.StringValue(v.Format(time.RFC3339))
	} else {
		m.LastUpdatedTime = types.StringNull()
	}
	if v, ok := o.GetNameOk(); ok && v != nil {
		m.Name = types.StringValue(*v)
	} else {
		m.Name = types.StringNull()
	}
	return m
}
