// Code generated by api-codegen; DO NOT EDIT.
package provider

import (
	"context"
	"fmt"

	"github.com/hashicorp/terraform-plugin-framework/datasource"
	"github.com/hashicorp/terraform-plugin-framework/types"
	"time"

	sdk "github.com/monte-carlo-data/mc-sdk-go/montecarlo"
	"github.com/monte-carlo-data/terraform-provider-montecarlo/internal/schema_gen/datasource_azure_sql_database_credentials"
)

var (
	_ datasource.DataSource              = (*azureSqlDatabaseCredentialsDataSource)(nil)
	_ datasource.DataSourceWithConfigure = (*azureSqlDatabaseCredentialsDataSource)(nil)
)

type azureSqlDatabaseCredentialsDataSource struct{ clients *clients }

func NewAzureSqlDatabaseCredentialsDataSource() datasource.DataSource {
	return &azureSqlDatabaseCredentialsDataSource{}
}

func (d *azureSqlDatabaseCredentialsDataSource) Metadata(_ context.Context, req datasource.MetadataRequest, resp *datasource.MetadataResponse) {
	resp.TypeName = req.ProviderTypeName + "_azure_sql_database_credentials"
}

func (d *azureSqlDatabaseCredentialsDataSource) Schema(ctx context.Context, _ datasource.SchemaRequest, resp *datasource.SchemaResponse) {
	resp.Schema = datasource_azure_sql_database_credentials.AzureSqlDatabaseCredentialsDataSourceSchema(ctx)
}

func (d *azureSqlDatabaseCredentialsDataSource) Configure(_ context.Context, req datasource.ConfigureRequest, resp *datasource.ConfigureResponse) {
	if req.ProviderData == nil {
		return
	}
	c, ok := req.ProviderData.(*clients)
	if !ok {
		resp.Diagnostics.AddError("unexpected provider data", fmt.Sprintf("got %T", req.ProviderData))
		return
	}
	d.clients = c
}

func (d *azureSqlDatabaseCredentialsDataSource) Read(ctx context.Context, req datasource.ReadRequest, resp *datasource.ReadResponse) {
	ctx = sdk.WithTelemetryCommand(ctx, "data.montecarlo_azure_sql_database_credentials read")
	var cfg datasource_azure_sql_database_credentials.AzureSqlDatabaseCredentialsModel
	resp.Diagnostics.Append(req.Config.Get(ctx, &cfg)...)
	if resp.Diagnostics.HasError() {
		return
	}
	out, _, err := d.clients.api.CredentialsAPI.GetAzureSqlDatabaseCredentials(ctx, cfg.CredentialsId.ValueString()).Execute()
	if err != nil {
		resp.Diagnostics.AddError("Read azure_sql_database_credentials failed", apiErr(err))
		return
	}
	m := datasource_azure_sql_database_credentials.AzureSqlDatabaseCredentialsModel{
		CredentialsId:  cfg.CredentialsId,
		ConnectionType: types.StringValue(out.GetConnectionType()),
		CreatedTime:    types.StringValue(out.GetCreatedTime().Format(time.RFC3339)),
		DbName:         types.StringValue(out.GetDbName()),
		Host:           types.StringValue(out.GetHost()),
		Id:             types.StringValue(out.GetId()),
		Port:           types.Int64Value(int64(out.GetPort())),
		StorageType:    types.StringValue(string(out.GetStorageType())),
		User:           types.StringValue(out.GetUser()),
	}
	resp.Diagnostics.Append(resp.State.Set(ctx, m)...)
}
