// Code generated by api-codegen; DO NOT EDIT.
package provider

import (
	"context"
	"fmt"
	"net/http"

	"github.com/hashicorp/terraform-plugin-framework/path"
	"github.com/hashicorp/terraform-plugin-framework/resource"
	"github.com/hashicorp/terraform-plugin-framework/types"
	"time"

	sdk "github.com/monte-carlo-data/mc-sdk-go/montecarlo"
	"github.com/monte-carlo-data/terraform-provider-montecarlo/internal/schema_gen/resource_bi_container"
)

var (
	_ resource.Resource                = (*biContainerResource)(nil)
	_ resource.ResourceWithConfigure   = (*biContainerResource)(nil)
	_ resource.ResourceWithImportState = (*biContainerResource)(nil)
)

type biContainerResource struct{ clients *clients }

func NewBiContainerResource() resource.Resource { return &biContainerResource{} }

func (r *biContainerResource) Metadata(_ context.Context, req resource.MetadataRequest, resp *resource.MetadataResponse) {
	resp.TypeName = req.ProviderTypeName + "_bi_container"
}

func (r *biContainerResource) Schema(ctx context.Context, _ resource.SchemaRequest, resp *resource.SchemaResponse) {
	s := resource_bi_container.BiContainerResourceSchema(ctx)
	// These holds come before the replacements below: plan modifiers run in the order they are attached.
	// Updating the resource never changes these, and a null in state is final. Only the plain modifier copies a null.
	useStateForUnknown(s.Attributes, "bi_container.created_time", &resp.Diagnostics)
	useStateForUnknown(s.Attributes, "bi_container.deployment_id", &resp.Diagnostics)
	useStateForUnknown(s.Attributes, "bi_container.id", &resp.Diagnostics)
	useStateForUnknown(s.Attributes, "bi_container.type", &resp.Diagnostics)
	// The API accepts these on create and not on update, so changing one replaces the resource.
	requiresReplace(s.Attributes, "bi_container.deployment_id", &resp.Diagnostics)
	requiresReplace(s.Attributes, "bi_container.type", &resp.Diagnostics)
	resp.Schema = s
}

func (r *biContainerResource) Configure(_ context.Context, req resource.ConfigureRequest, resp *resource.ConfigureResponse) {
	if req.ProviderData == nil {
		return
	}
	c, ok := req.ProviderData.(*clients)
	if !ok {
		resp.Diagnostics.AddError("unexpected provider data", fmt.Sprintf("got %T", req.ProviderData))
		return
	}
	r.clients = c
}

func (r *biContainerResource) Create(ctx context.Context, req resource.CreateRequest, resp *resource.CreateResponse) {
	ctx = sdk.WithTelemetryCommand(ctx, "montecarlo_bi_container create")
	var plan resource_bi_container.BiContainerModel
	resp.Diagnostics.Append(req.Plan.Get(ctx, &plan)...)
	if resp.Diagnostics.HasError() {
		return
	}
	body := sdk.NewBiContainerIn(sdk.NewBiContainerType(plan.Type.ValueString()), plan.Name.ValueString(), plan.DeploymentId.ValueString())
	// Retried: the spec marks this operation x-mc-retry-on-transient.
	out, err := withRetryOnTransient(ctx, func() (*sdk.BiContainerOut, *http.Response, error) {
		return r.clients.api.BiContainersAPI.CreateBiContainer(ctx).BiContainerIn(*body).Execute()
	})
	if err != nil {
		resp.Diagnostics.AddError("Create bi_container failed", apiErr(err))
		return
	}
	resp.Diagnostics.Append(resp.State.Set(ctx, biContainerToModel(out))...)
}

func (r *biContainerResource) Read(ctx context.Context, req resource.ReadRequest, resp *resource.ReadResponse) {
	ctx = sdk.WithTelemetryCommand(ctx, "montecarlo_bi_container read")
	var state resource_bi_container.BiContainerModel
	resp.Diagnostics.Append(req.State.Get(ctx, &state)...)
	if resp.Diagnostics.HasError() {
		return
	}
	out, httpResp, err := r.clients.api.BiContainersAPI.GetBiContainer(ctx, state.Id.ValueString()).Execute()
	if err != nil {
		if httpResp != nil && httpResp.StatusCode == 404 {
			resp.State.RemoveResource(ctx)
			return
		}
		resp.Diagnostics.AddError("Read bi_container failed", apiErr(err))
		return
	}
	resp.Diagnostics.Append(resp.State.Set(ctx, biContainerToModel(out))...)
}

func (r *biContainerResource) Update(ctx context.Context, req resource.UpdateRequest, resp *resource.UpdateResponse) {
	ctx = sdk.WithTelemetryCommand(ctx, "montecarlo_bi_container update")
	var plan, state resource_bi_container.BiContainerModel
	resp.Diagnostics.Append(req.Plan.Get(ctx, &plan)...)
	resp.Diagnostics.Append(req.State.Get(ctx, &state)...)
	if resp.Diagnostics.HasError() {
		return
	}
	body := sdk.NewBiContainerPatch()
	if !plan.Name.IsNull() && !plan.Name.IsUnknown() {
		body.SetName(plan.Name.ValueString())
	}
	// Retried: the spec marks this operation x-mc-retry-on-transient.
	out, err := withRetryOnTransient(ctx, func() (*sdk.BiContainerOut, *http.Response, error) {
		return r.clients.api.BiContainersAPI.UpdateBiContainer(ctx, state.Id.ValueString()).BiContainerPatch(*body).Execute()
	})
	if err != nil {
		resp.Diagnostics.AddError("Update bi_container failed", apiErr(err))
		return
	}
	resp.Diagnostics.Append(resp.State.Set(ctx, biContainerToModel(out))...)
}

func (r *biContainerResource) Delete(ctx context.Context, req resource.DeleteRequest, resp *resource.DeleteResponse) {
	ctx = sdk.WithTelemetryCommand(ctx, "montecarlo_bi_container delete")
	var state resource_bi_container.BiContainerModel
	resp.Diagnostics.Append(req.State.Get(ctx, &state)...)
	if resp.Diagnostics.HasError() {
		return
	}
	if _, err := r.clients.api.BiContainersAPI.DeleteBiContainer(ctx, state.Id.ValueString()).Execute(); err != nil {
		resp.Diagnostics.AddError("Delete bi_container failed", apiErr(err))
	}
}

func (r *biContainerResource) ImportState(ctx context.Context, req resource.ImportStateRequest, resp *resource.ImportStateResponse) {
	resource.ImportStatePassthroughID(ctx, path.Root("id"), req, resp)
}

func biContainerToModel(o *sdk.BiContainerOut) resource_bi_container.BiContainerModel {
	m := resource_bi_container.BiContainerModel{
		CreatedTime: types.StringValue(o.GetCreatedTime().Format(time.RFC3339)),
		Id:          types.StringValue(o.GetId()),
		Type:        types.StringValue(string(o.GetType())),
	}
	if v, ok := o.GetDeploymentIdOk(); ok && v != nil {
		m.DeploymentId = types.StringValue(*v)
	} else {
		m.DeploymentId = types.StringNull()
	}
	if v, ok := o.GetDeploymentNameOk(); ok && v != nil {
		m.DeploymentName = types.StringValue(*v)
	} else {
		m.DeploymentName = types.StringNull()
	}
	if v, ok := o.GetNameOk(); ok && v != nil {
		m.Name = types.StringValue(*v)
	} else {
		m.Name = types.StringNull()
	}
	return m
}
