// Code generated by api-codegen; DO NOT EDIT.
package provider

import (
	"context"
	"fmt"

	"github.com/hashicorp/terraform-plugin-framework/datasource"
	"github.com/hashicorp/terraform-plugin-framework/types"
	"time"

	sdk "github.com/monte-carlo-data/mc-sdk-go/montecarlo"
	"github.com/monte-carlo-data/terraform-provider-montecarlo/internal/schema_gen/datasource_bi_container"
)

var (
	_ datasource.DataSource              = (*biContainerDataSource)(nil)
	_ datasource.DataSourceWithConfigure = (*biContainerDataSource)(nil)
)

type biContainerDataSource struct{ clients *clients }

func NewBiContainerDataSource() datasource.DataSource { return &biContainerDataSource{} }

func (d *biContainerDataSource) Metadata(_ context.Context, req datasource.MetadataRequest, resp *datasource.MetadataResponse) {
	resp.TypeName = req.ProviderTypeName + "_bi_container"
}

func (d *biContainerDataSource) Schema(ctx context.Context, _ datasource.SchemaRequest, resp *datasource.SchemaResponse) {
	resp.Schema = datasource_bi_container.BiContainerDataSourceSchema(ctx)
}

func (d *biContainerDataSource) Configure(_ context.Context, req datasource.ConfigureRequest, resp *datasource.ConfigureResponse) {
	if req.ProviderData == nil {
		return
	}
	c, ok := req.ProviderData.(*clients)
	if !ok {
		resp.Diagnostics.AddError("unexpected provider data", fmt.Sprintf("got %T", req.ProviderData))
		return
	}
	d.clients = c
}

func (d *biContainerDataSource) Read(ctx context.Context, req datasource.ReadRequest, resp *datasource.ReadResponse) {
	ctx = sdk.WithTelemetryCommand(ctx, "data.montecarlo_bi_container read")
	var cfg datasource_bi_container.BiContainerModel
	resp.Diagnostics.Append(req.Config.Get(ctx, &cfg)...)
	if resp.Diagnostics.HasError() {
		return
	}
	out, _, err := d.clients.api.BiContainersAPI.GetBiContainer(ctx, cfg.BiContainerId.ValueString()).Execute()
	if err != nil {
		resp.Diagnostics.AddError("Read bi_container failed", apiErr(err))
		return
	}
	m := datasource_bi_container.BiContainerModel{
		BiContainerId: cfg.BiContainerId,
		CreatedTime:   types.StringValue(out.GetCreatedTime().Format(time.RFC3339)),
		Id:            types.StringValue(out.GetId()),
		Type:          types.StringValue(string(out.GetType())),
	}
	if v, ok := out.GetDeploymentIdOk(); ok && v != nil {
		m.DeploymentId = types.StringValue(*v)
	} else {
		m.DeploymentId = types.StringNull()
	}
	if v, ok := out.GetDeploymentNameOk(); ok && v != nil {
		m.DeploymentName = types.StringValue(*v)
	} else {
		m.DeploymentName = types.StringNull()
	}
	if v, ok := out.GetNameOk(); ok && v != nil {
		m.Name = types.StringValue(*v)
	} else {
		m.Name = types.StringNull()
	}
	resp.Diagnostics.Append(resp.State.Set(ctx, m)...)
}
