// Code generated by api-codegen; DO NOT EDIT.
package provider

import (
	"context"
	"fmt"

	"github.com/hashicorp/terraform-plugin-framework/datasource"
	"github.com/hashicorp/terraform-plugin-framework/types"
	"time"

	sdk "github.com/monte-carlo-data/mc-sdk-go/montecarlo"
	"github.com/monte-carlo-data/terraform-provider-montecarlo/internal/schema_gen/datasource_bigquery_credentials"
)

var (
	_ datasource.DataSource              = (*bigqueryCredentialsDataSource)(nil)
	_ datasource.DataSourceWithConfigure = (*bigqueryCredentialsDataSource)(nil)
)

type bigqueryCredentialsDataSource struct{ clients *clients }

func NewBigqueryCredentialsDataSource() datasource.DataSource {
	return &bigqueryCredentialsDataSource{}
}

func (d *bigqueryCredentialsDataSource) Metadata(_ context.Context, req datasource.MetadataRequest, resp *datasource.MetadataResponse) {
	resp.TypeName = req.ProviderTypeName + "_bigquery_credentials"
}

func (d *bigqueryCredentialsDataSource) Schema(ctx context.Context, _ datasource.SchemaRequest, resp *datasource.SchemaResponse) {
	resp.Schema = datasource_bigquery_credentials.BigqueryCredentialsDataSourceSchema(ctx)
}

func (d *bigqueryCredentialsDataSource) Configure(_ context.Context, req datasource.ConfigureRequest, resp *datasource.ConfigureResponse) {
	if req.ProviderData == nil {
		return
	}
	c, ok := req.ProviderData.(*clients)
	if !ok {
		resp.Diagnostics.AddError("unexpected provider data", fmt.Sprintf("got %T", req.ProviderData))
		return
	}
	d.clients = c
}

func (d *bigqueryCredentialsDataSource) Read(ctx context.Context, req datasource.ReadRequest, resp *datasource.ReadResponse) {
	ctx = sdk.WithTelemetryCommand(ctx, "data.montecarlo_bigquery_credentials read")
	var cfg datasource_bigquery_credentials.BigqueryCredentialsModel
	resp.Diagnostics.Append(req.Config.Get(ctx, &cfg)...)
	if resp.Diagnostics.HasError() {
		return
	}
	out, _, err := d.clients.api.CredentialsAPI.GetBigqueryCredentials(ctx, cfg.CredentialsId.ValueString()).Execute()
	if err != nil {
		resp.Diagnostics.AddError("Read bigquery_credentials failed", apiErr(err))
		return
	}
	m := datasource_bigquery_credentials.BigqueryCredentialsModel{
		CredentialsId:  cfg.CredentialsId,
		ClientEmail:    types.StringValue(out.GetClientEmail()),
		ConnectionType: types.StringValue(out.GetConnectionType()),
		CreatedTime:    types.StringValue(out.GetCreatedTime().Format(time.RFC3339)),
		Id:             types.StringValue(out.GetId()),
		ProjectId:      types.StringValue(out.GetProjectId()),
		StorageType:    types.StringValue(string(out.GetStorageType())),
	}
	resp.Diagnostics.Append(resp.State.Set(ctx, m)...)
}
