// Code generated by api-codegen; DO NOT EDIT.
package provider

import (
	"context"
	"fmt"

	"github.com/hashicorp/terraform-plugin-framework/datasource"
	"github.com/hashicorp/terraform-plugin-framework/types"
	"time"

	sdk "github.com/monte-carlo-data/mc-sdk-go/montecarlo"
	"github.com/monte-carlo-data/terraform-provider-montecarlo/internal/schema_gen/datasource_clickhouse_credentials"
)

var (
	_ datasource.DataSource              = (*clickhouseCredentialsDataSource)(nil)
	_ datasource.DataSourceWithConfigure = (*clickhouseCredentialsDataSource)(nil)
)

type clickhouseCredentialsDataSource struct{ clients *clients }

func NewClickhouseCredentialsDataSource() datasource.DataSource {
	return &clickhouseCredentialsDataSource{}
}

func (d *clickhouseCredentialsDataSource) Metadata(_ context.Context, req datasource.MetadataRequest, resp *datasource.MetadataResponse) {
	resp.TypeName = req.ProviderTypeName + "_clickhouse_credentials"
}

func (d *clickhouseCredentialsDataSource) Schema(ctx context.Context, _ datasource.SchemaRequest, resp *datasource.SchemaResponse) {
	resp.Schema = datasource_clickhouse_credentials.ClickhouseCredentialsDataSourceSchema(ctx)
}

func (d *clickhouseCredentialsDataSource) Configure(_ context.Context, req datasource.ConfigureRequest, resp *datasource.ConfigureResponse) {
	if req.ProviderData == nil {
		return
	}
	c, ok := req.ProviderData.(*clients)
	if !ok {
		resp.Diagnostics.AddError("unexpected provider data", fmt.Sprintf("got %T", req.ProviderData))
		return
	}
	d.clients = c
}

func (d *clickhouseCredentialsDataSource) Read(ctx context.Context, req datasource.ReadRequest, resp *datasource.ReadResponse) {
	ctx = sdk.WithTelemetryCommand(ctx, "data.montecarlo_clickhouse_credentials read")
	var cfg datasource_clickhouse_credentials.ClickhouseCredentialsModel
	resp.Diagnostics.Append(req.Config.Get(ctx, &cfg)...)
	if resp.Diagnostics.HasError() {
		return
	}
	out, _, err := d.clients.api.CredentialsAPI.GetClickhouseCredentials(ctx, cfg.CredentialsId.ValueString()).Execute()
	if err != nil {
		resp.Diagnostics.AddError("Read clickhouse_credentials failed", apiErr(err))
		return
	}
	m := datasource_clickhouse_credentials.ClickhouseCredentialsModel{
		CredentialsId:  cfg.CredentialsId,
		ConnectionType: types.StringValue(out.GetConnectionType()),
		CreatedTime:    types.StringValue(out.GetCreatedTime().Format(time.RFC3339)),
		Host:           types.StringValue(out.GetHost()),
		Id:             types.StringValue(out.GetId()),
		Port:           types.Int64Value(int64(out.GetPort())),
		StorageType:    types.StringValue(string(out.GetStorageType())),
		User:           types.StringValue(out.GetUser()),
	}
	if v, ok := out.GetDbNameOk(); ok && v != nil {
		m.DbName = types.StringValue(*v)
	} else {
		m.DbName = types.StringNull()
	}
	resp.Diagnostics.Append(resp.State.Set(ctx, m)...)
}
