// Code generated by api-codegen; DO NOT EDIT.
package provider

import (
	"context"
	"fmt"
	"net/http"

	"github.com/hashicorp/terraform-plugin-framework/path"
	"github.com/hashicorp/terraform-plugin-framework/resource"
	"github.com/hashicorp/terraform-plugin-framework/types"
	"time"

	sdk "github.com/monte-carlo-data/mc-sdk-go/montecarlo"
	"github.com/monte-carlo-data/terraform-provider-montecarlo/internal/schema_gen/resource_clickhouse_credentials"
)

var (
	_ resource.Resource                = (*clickhouseCredentialsResource)(nil)
	_ resource.ResourceWithConfigure   = (*clickhouseCredentialsResource)(nil)
	_ resource.ResourceWithImportState = (*clickhouseCredentialsResource)(nil)
)

type clickhouseCredentialsResource struct{ clients *clients }

func NewClickhouseCredentialsResource() resource.Resource { return &clickhouseCredentialsResource{} }

func (r *clickhouseCredentialsResource) Metadata(_ context.Context, req resource.MetadataRequest, resp *resource.MetadataResponse) {
	resp.TypeName = req.ProviderTypeName + "_clickhouse_credentials"
}

func (r *clickhouseCredentialsResource) Schema(ctx context.Context, _ resource.SchemaRequest, resp *resource.SchemaResponse) {
	s := resource_clickhouse_credentials.ClickhouseCredentialsResourceSchema(ctx)
	// Secrets: Terraform passes them to the provider on apply and never stores them.
	writeOnly(s.Attributes, "clickhouse_credentials.password_wo", &resp.Diagnostics)
	// Updating the resource never changes these, so the plan keeps what state holds.
	useNonNullStateForUnknown(s.Attributes, "clickhouse_credentials.connection_type", &resp.Diagnostics)
	useNonNullStateForUnknown(s.Attributes, "clickhouse_credentials.created_time", &resp.Diagnostics)
	useNonNullStateForUnknown(s.Attributes, "clickhouse_credentials.id", &resp.Diagnostics)
	useNonNullStateForUnknown(s.Attributes, "clickhouse_credentials.storage_type", &resp.Diagnostics)
	resp.Schema = s
}

func (r *clickhouseCredentialsResource) Configure(_ context.Context, req resource.ConfigureRequest, resp *resource.ConfigureResponse) {
	if req.ProviderData == nil {
		return
	}
	c, ok := req.ProviderData.(*clients)
	if !ok {
		resp.Diagnostics.AddError("unexpected provider data", fmt.Sprintf("got %T", req.ProviderData))
		return
	}
	r.clients = c
}

func (r *clickhouseCredentialsResource) Create(ctx context.Context, req resource.CreateRequest, resp *resource.CreateResponse) {
	ctx = sdk.WithTelemetryCommand(ctx, "montecarlo_clickhouse_credentials create")
	var plan resource_clickhouse_credentials.ClickhouseCredentialsModel
	resp.Diagnostics.Append(req.Plan.Get(ctx, &plan)...)
	// Terraform plans a write-only secret as null and passes it only in the configuration.
	var config resource_clickhouse_credentials.ClickhouseCredentialsModel
	resp.Diagnostics.Append(req.Config.Get(ctx, &config)...)
	if resp.Diagnostics.HasError() {
		return
	}
	body := sdk.NewClickHouseCredentialsIn(plan.Host.ValueString(), int32(plan.Port.ValueInt64()), plan.User.ValueString(), config.PasswordWo.ValueString())
	if !plan.DbName.IsNull() && !plan.DbName.IsUnknown() {
		body.SetDbName(plan.DbName.ValueString())
	}
	// Retried: the spec marks this operation x-mc-retry-on-transient.
	out, err := withRetryOnTransient(ctx, func() (*sdk.ClickHouseCredentialsOut, *http.Response, error) {
		return r.clients.api.CredentialsAPI.CreateClickhouseCredentials(ctx).ClickHouseCredentialsIn(*body).Execute()
	})
	if err != nil {
		resp.Diagnostics.AddError("Create clickhouse_credentials failed", apiErr(err))
		return
	}
	resp.Diagnostics.Append(resp.State.Set(ctx, clickhouseCredentialsToModel(out, plan.PasswordWoVersion))...)
}

func (r *clickhouseCredentialsResource) Read(ctx context.Context, req resource.ReadRequest, resp *resource.ReadResponse) {
	ctx = sdk.WithTelemetryCommand(ctx, "montecarlo_clickhouse_credentials read")
	var state resource_clickhouse_credentials.ClickhouseCredentialsModel
	resp.Diagnostics.Append(req.State.Get(ctx, &state)...)
	if resp.Diagnostics.HasError() {
		return
	}
	out, httpResp, err := r.clients.api.CredentialsAPI.GetClickhouseCredentials(ctx, state.Id.ValueString()).Execute()
	if err != nil {
		if httpResp != nil && httpResp.StatusCode == 404 {
			resp.State.RemoveResource(ctx)
			return
		}
		resp.Diagnostics.AddError("Read clickhouse_credentials failed", apiErr(err))
		return
	}
	resp.Diagnostics.Append(resp.State.Set(ctx, clickhouseCredentialsToModel(out, state.PasswordWoVersion))...)
}

func (r *clickhouseCredentialsResource) Update(ctx context.Context, req resource.UpdateRequest, resp *resource.UpdateResponse) {
	ctx = sdk.WithTelemetryCommand(ctx, "montecarlo_clickhouse_credentials update")
	var plan, state resource_clickhouse_credentials.ClickhouseCredentialsModel
	resp.Diagnostics.Append(req.Plan.Get(ctx, &plan)...)
	resp.Diagnostics.Append(req.State.Get(ctx, &state)...)
	// Terraform plans a write-only secret as null and passes it only in the configuration.
	var config resource_clickhouse_credentials.ClickhouseCredentialsModel
	resp.Diagnostics.Append(req.Config.Get(ctx, &config)...)
	if resp.Diagnostics.HasError() {
		return
	}
	body := sdk.NewClickHouseCredentialsPatch()
	if !plan.DbName.IsNull() && !plan.DbName.IsUnknown() {
		body.SetDbName(plan.DbName.ValueString())
	}
	if !plan.Host.IsNull() && !plan.Host.IsUnknown() {
		body.SetHost(plan.Host.ValueString())
	}
	if !config.PasswordWo.IsNull() && !config.PasswordWo.IsUnknown() {
		body.SetPassword(config.PasswordWo.ValueString())
	}
	if !plan.Port.IsNull() && !plan.Port.IsUnknown() {
		body.SetPort(int32(plan.Port.ValueInt64()))
	}
	if !plan.User.IsNull() && !plan.User.IsUnknown() {
		body.SetUser(plan.User.ValueString())
	}
	// Retried: the spec marks this operation x-mc-retry-on-transient.
	out, err := withRetryOnTransient(ctx, func() (*sdk.ClickHouseCredentialsOut, *http.Response, error) {
		return r.clients.api.CredentialsAPI.UpdateClickhouseCredentials(ctx, state.Id.ValueString()).ClickHouseCredentialsPatch(*body).Execute()
	})
	if err != nil {
		resp.Diagnostics.AddError("Update clickhouse_credentials failed", apiErr(err))
		return
	}
	resp.Diagnostics.Append(resp.State.Set(ctx, clickhouseCredentialsToModel(out, plan.PasswordWoVersion))...)
}

func (r *clickhouseCredentialsResource) Delete(ctx context.Context, req resource.DeleteRequest, resp *resource.DeleteResponse) {
	ctx = sdk.WithTelemetryCommand(ctx, "montecarlo_clickhouse_credentials delete")
	var state resource_clickhouse_credentials.ClickhouseCredentialsModel
	resp.Diagnostics.Append(req.State.Get(ctx, &state)...)
	if resp.Diagnostics.HasError() {
		return
	}
	if _, err := r.clients.api.CredentialsAPI.DeleteClickhouseCredentials(ctx, state.Id.ValueString()).Execute(); err != nil {
		resp.Diagnostics.AddError("Delete clickhouse_credentials failed", apiErr(err))
	}
}

func (r *clickhouseCredentialsResource) ImportState(ctx context.Context, req resource.ImportStateRequest, resp *resource.ImportStateResponse) {
	resource.ImportStatePassthroughID(ctx, path.Root("id"), req, resp)
}

func clickhouseCredentialsToModel(o *sdk.ClickHouseCredentialsOut, password_wo_version types.Int64) resource_clickhouse_credentials.ClickhouseCredentialsModel {
	m := resource_clickhouse_credentials.ClickhouseCredentialsModel{
		ConnectionType:    types.StringValue(o.GetConnectionType()),
		CreatedTime:       types.StringValue(o.GetCreatedTime().Format(time.RFC3339)),
		Host:              types.StringValue(o.GetHost()),
		Id:                types.StringValue(o.GetId()),
		Port:              types.Int64Value(int64(o.GetPort())),
		StorageType:       types.StringValue(string(o.GetStorageType())),
		User:              types.StringValue(o.GetUser()),
		PasswordWoVersion: password_wo_version,
	}
	if v, ok := o.GetDbNameOk(); ok && v != nil {
		m.DbName = types.StringValue(*v)
	} else {
		m.DbName = types.StringNull()
	}
	// An unreturned field the config omits arrives unknown and no response fills it, so it
	// resolves to null. Terraform rejects an unknown after apply.
	if password_wo_version.IsUnknown() {
		m.PasswordWoVersion = types.Int64Null()
	}
	return m
}
