// Code generated by api-codegen; DO NOT EDIT.
package provider

import (
	"context"
	"fmt"

	"github.com/hashicorp/terraform-plugin-framework/attr"
	"github.com/hashicorp/terraform-plugin-framework/datasource"
	"github.com/hashicorp/terraform-plugin-framework/diag"
	"github.com/hashicorp/terraform-plugin-framework/types"
	"time"

	sdk "github.com/monte-carlo-data/mc-sdk-go/montecarlo"
	"github.com/monte-carlo-data/terraform-provider-montecarlo/internal/schema_gen/datasource_custom_connector_type"
)

var (
	_ datasource.DataSource              = (*customConnectorTypeDataSource)(nil)
	_ datasource.DataSourceWithConfigure = (*customConnectorTypeDataSource)(nil)
)

type customConnectorTypeDataSource struct{ clients *clients }

func NewCustomConnectorTypeDataSource() datasource.DataSource {
	return &customConnectorTypeDataSource{}
}

func (d *customConnectorTypeDataSource) Metadata(_ context.Context, req datasource.MetadataRequest, resp *datasource.MetadataResponse) {
	resp.TypeName = req.ProviderTypeName + "_custom_connector_type"
}

func (d *customConnectorTypeDataSource) Schema(ctx context.Context, _ datasource.SchemaRequest, resp *datasource.SchemaResponse) {
	resp.Schema = datasource_custom_connector_type.CustomConnectorTypeDataSourceSchema(ctx)
}

func (d *customConnectorTypeDataSource) Configure(_ context.Context, req datasource.ConfigureRequest, resp *datasource.ConfigureResponse) {
	if req.ProviderData == nil {
		return
	}
	c, ok := req.ProviderData.(*clients)
	if !ok {
		resp.Diagnostics.AddError("unexpected provider data", fmt.Sprintf("got %T", req.ProviderData))
		return
	}
	d.clients = c
}

func (d *customConnectorTypeDataSource) Read(ctx context.Context, req datasource.ReadRequest, resp *datasource.ReadResponse) {
	ctx = sdk.WithTelemetryCommand(ctx, "data.montecarlo_custom_connector_type read")
	var cfg datasource_custom_connector_type.CustomConnectorTypeModel
	resp.Diagnostics.Append(req.Config.Get(ctx, &cfg)...)
	if resp.Diagnostics.HasError() {
		return
	}
	out, _, err := d.clients.api.CustomConnectorTypesAPI.GetCustomConnectorType(ctx, cfg.CustomConnectorTypeId.ValueString()).Execute()
	if err != nil {
		resp.Diagnostics.AddError("Read custom_connector_type failed", apiErr(err))
		return
	}
	diags := &resp.Diagnostics
	m := datasource_custom_connector_type.CustomConnectorTypeModel{
		CustomConnectorTypeId: cfg.CustomConnectorTypeId,
		AssetClass:            types.StringValue(string(out.GetAssetClass())),
		CollectionAgentId:     types.StringValue(out.GetCollectionAgentId()),
		CreatedTime:           types.StringValue(out.GetCreatedTime().Format(time.RFC3339)),
		DeploymentId:          types.StringValue(out.GetDeploymentId()),
		Id:                    types.StringValue(out.GetId()),
		JobTypes:              stringList(out.GetJobTypes()),
		Name:                  types.StringValue(out.GetName()),
		UpdatedTime:           types.StringValue(out.GetUpdatedTime().Format(time.RFC3339)),
	}
	if v, ok := out.GetCapabilitiesOk(); ok && v != nil {
		m.Capabilities = customConnectorTypeDataSourceCapabilities(ctx, *v, diags)
	} else {
		m.Capabilities = datasource_custom_connector_type.NewCapabilitiesValueNull()
	}
	if v, ok := out.GetIconUrlOk(); ok && v != nil {
		m.IconUrl = types.StringValue(*v)
	} else {
		m.IconUrl = types.StringNull()
	}
	if v, ok := out.GetTerminologyOk(); ok && v != nil {
		m.Terminology = customConnectorTypeDataSourceTerminology(ctx, *v, diags)
	} else {
		m.Terminology = datasource_custom_connector_type.NewTerminologyValueNull()
	}
	resp.Diagnostics.Append(resp.State.Set(ctx, m)...)
}

// customConnectorTypeDataSourceCapabilities converts the SDK's CustomConnectorCapabilities into the capabilities attribute's value.
func customConnectorTypeDataSourceCapabilities(ctx context.Context, o sdk.CustomConnectorCapabilities, diags *diag.Diagnostics) datasource_custom_connector_type.CapabilitiesValue {
	attrs := map[string]attr.Value{
		"supports_agent_monitor":                    types.BoolValue(o.GetSupportsAgentMonitor()),
		"supports_agent_trajectory_monitor":         types.BoolValue(o.GetSupportsAgentTrajectoryMonitor()),
		"supports_comparison_monitor":               types.BoolValue(o.GetSupportsComparisonMonitor()),
		"supports_custom_sql_monitor":               types.BoolValue(o.GetSupportsCustomSqlMonitor()),
		"supports_field_lineage":                    types.BoolValue(o.GetSupportsFieldLineage()),
		"supports_freshness":                        types.BoolValue(o.GetSupportsFreshness()),
		"supports_full_query_language":              types.BoolValue(o.GetSupportsFullQueryLanguage()),
		"supports_json_schema_monitor":              types.BoolValue(o.GetSupportsJsonSchemaMonitor()),
		"supports_lineage":                          types.BoolValue(o.GetSupportsLineage()),
		"supports_metadata":                         types.BoolValue(o.GetSupportsMetadata()),
		"supports_metric_monitors_on_unknown_types": types.BoolValue(o.GetSupportsMetricMonitorsOnUnknownTypes()),
		"supports_non_metadata_size_collection":     types.BoolValue(o.GetSupportsNonMetadataSizeCollection()),
		"supports_query_logs":                       types.BoolValue(o.GetSupportsQueryLogs()),
		"supports_schema":                           types.BoolValue(o.GetSupportsSchema()),
		"supports_stats_monitor":                    types.BoolValue(o.GetSupportsStatsMonitor()),
		"supports_transform":                        types.BoolValue(o.GetSupportsTransform()),
		"supports_validation_monitor":               types.BoolValue(o.GetSupportsValidationMonitor()),
		"supports_volume_bytes":                     types.BoolValue(o.GetSupportsVolumeBytes()),
		"supports_volume_rows":                      types.BoolValue(o.GetSupportsVolumeRows()),
	}
	v, d := datasource_custom_connector_type.NewCapabilitiesValue(datasource_custom_connector_type.CapabilitiesValue{}.AttributeTypes(ctx), attrs)
	diags.Append(d...)
	return v
}

// customConnectorTypeDataSourceTerminology converts the SDK's CustomConnectorTerminology into the terminology attribute's value.
func customConnectorTypeDataSourceTerminology(ctx context.Context, o sdk.CustomConnectorTerminology, diags *diag.Diagnostics) datasource_custom_connector_type.TerminologyValue {
	attrs := map[string]attr.Value{
		"job": types.StringValue(o.GetJob()),
	}
	if v, ok := o.GetGroupOk(); ok && v != nil {
		attrs["group"] = types.StringValue(*v)
	} else {
		attrs["group"] = types.StringNull()
	}
	if v, ok := o.GetTaskOk(); ok && v != nil {
		attrs["task"] = types.StringValue(*v)
	} else {
		attrs["task"] = types.StringNull()
	}
	v, d := datasource_custom_connector_type.NewTerminologyValue(datasource_custom_connector_type.TerminologyValue{}.AttributeTypes(ctx), attrs)
	diags.Append(d...)
	return v
}
