// Code generated by api-codegen; DO NOT EDIT.
package provider

import (
	"context"
	"fmt"
	"net/http"

	"github.com/hashicorp/terraform-plugin-framework/path"
	"github.com/hashicorp/terraform-plugin-framework/resource"
	"github.com/hashicorp/terraform-plugin-framework/types"
	"time"

	sdk "github.com/monte-carlo-data/mc-sdk-go/montecarlo"
	"github.com/monte-carlo-data/terraform-provider-montecarlo/internal/schema_gen/resource_databricks_sql_warehouse_credentials"
)

var (
	_ resource.Resource                = (*databricksSqlWarehouseCredentialsResource)(nil)
	_ resource.ResourceWithConfigure   = (*databricksSqlWarehouseCredentialsResource)(nil)
	_ resource.ResourceWithImportState = (*databricksSqlWarehouseCredentialsResource)(nil)
)

type databricksSqlWarehouseCredentialsResource struct{ clients *clients }

func NewDatabricksSqlWarehouseCredentialsResource() resource.Resource {
	return &databricksSqlWarehouseCredentialsResource{}
}

func (r *databricksSqlWarehouseCredentialsResource) Metadata(_ context.Context, req resource.MetadataRequest, resp *resource.MetadataResponse) {
	resp.TypeName = req.ProviderTypeName + "_databricks_sql_warehouse_credentials"
}

func (r *databricksSqlWarehouseCredentialsResource) Schema(ctx context.Context, _ resource.SchemaRequest, resp *resource.SchemaResponse) {
	s := resource_databricks_sql_warehouse_credentials.DatabricksSqlWarehouseCredentialsResourceSchema(ctx)
	// Secrets: Terraform passes them to the provider on apply and never stores them.
	writeOnly(s.Attributes, "databricks_sql_warehouse_credentials.oauth_client_secret_wo", &resp.Diagnostics)
	writeOnly(s.Attributes, "databricks_sql_warehouse_credentials.token_wo", &resp.Diagnostics)
	// Updating the resource never changes these, and a null in state is final. Only the plain modifier copies a null.
	useStateForUnknown(s.Attributes, "databricks_sql_warehouse_credentials.connection_type", &resp.Diagnostics)
	useStateForUnknown(s.Attributes, "databricks_sql_warehouse_credentials.created_time", &resp.Diagnostics)
	useStateForUnknown(s.Attributes, "databricks_sql_warehouse_credentials.id", &resp.Diagnostics)
	useStateForUnknown(s.Attributes, "databricks_sql_warehouse_credentials.storage_type", &resp.Diagnostics)
	resp.Schema = s
}

func (r *databricksSqlWarehouseCredentialsResource) Configure(_ context.Context, req resource.ConfigureRequest, resp *resource.ConfigureResponse) {
	if req.ProviderData == nil {
		return
	}
	c, ok := req.ProviderData.(*clients)
	if !ok {
		resp.Diagnostics.AddError("unexpected provider data", fmt.Sprintf("got %T", req.ProviderData))
		return
	}
	r.clients = c
}

func (r *databricksSqlWarehouseCredentialsResource) Create(ctx context.Context, req resource.CreateRequest, resp *resource.CreateResponse) {
	ctx = sdk.WithTelemetryCommand(ctx, "montecarlo_databricks_sql_warehouse_credentials create")
	var plan resource_databricks_sql_warehouse_credentials.DatabricksSqlWarehouseCredentialsModel
	resp.Diagnostics.Append(req.Plan.Get(ctx, &plan)...)
	// Terraform plans a write-only secret as null and passes it only in the configuration.
	var config resource_databricks_sql_warehouse_credentials.DatabricksSqlWarehouseCredentialsModel
	resp.Diagnostics.Append(req.Config.Get(ctx, &config)...)
	if resp.Diagnostics.HasError() {
		return
	}
	body := sdk.NewDatabricksSqlWarehouseCredentialsIn(plan.WorkspaceUrl.ValueString(), plan.SqlWarehouseId.ValueString())
	if !plan.AzureTenantId.IsNull() && !plan.AzureTenantId.IsUnknown() {
		body.SetAzureTenantId(plan.AzureTenantId.ValueString())
	}
	if !plan.AzureWorkspaceResourceId.IsNull() && !plan.AzureWorkspaceResourceId.IsUnknown() {
		body.SetAzureWorkspaceResourceId(plan.AzureWorkspaceResourceId.ValueString())
	}
	if !plan.OauthClientId.IsNull() && !plan.OauthClientId.IsUnknown() {
		body.SetOauthClientId(plan.OauthClientId.ValueString())
	}
	if !config.OauthClientSecretWo.IsNull() && !config.OauthClientSecretWo.IsUnknown() {
		body.SetOauthClientSecret(config.OauthClientSecretWo.ValueString())
	}
	if !config.TokenWo.IsNull() && !config.TokenWo.IsUnknown() {
		body.SetToken(config.TokenWo.ValueString())
	}
	if !plan.WorkspaceId.IsNull() && !plan.WorkspaceId.IsUnknown() {
		body.SetWorkspaceId(plan.WorkspaceId.ValueString())
	}
	// Retried: the spec marks this operation x-mc-retry-on-transient.
	out, err := withRetryOnTransient(ctx, func() (*sdk.DatabricksSqlWarehouseCredentialsOut, *http.Response, error) {
		return r.clients.api.CredentialsAPI.CreateDatabricksSqlWarehouseCredentials(ctx).DatabricksSqlWarehouseCredentialsIn(*body).Execute()
	})
	if err != nil {
		resp.Diagnostics.AddError("Create databricks_sql_warehouse_credentials failed", apiErr(err))
		return
	}
	resp.Diagnostics.Append(resp.State.Set(ctx, databricksSqlWarehouseCredentialsToModel(out, plan.OauthClientSecretWoVersion, plan.TokenWoVersion))...)
}

func (r *databricksSqlWarehouseCredentialsResource) Read(ctx context.Context, req resource.ReadRequest, resp *resource.ReadResponse) {
	ctx = sdk.WithTelemetryCommand(ctx, "montecarlo_databricks_sql_warehouse_credentials read")
	var state resource_databricks_sql_warehouse_credentials.DatabricksSqlWarehouseCredentialsModel
	resp.Diagnostics.Append(req.State.Get(ctx, &state)...)
	if resp.Diagnostics.HasError() {
		return
	}
	out, httpResp, err := r.clients.api.CredentialsAPI.GetDatabricksSqlWarehouseCredentials(ctx, state.Id.ValueString()).Execute()
	if err != nil {
		if httpResp != nil && httpResp.StatusCode == 404 {
			resp.State.RemoveResource(ctx)
			return
		}
		resp.Diagnostics.AddError("Read databricks_sql_warehouse_credentials failed", apiErr(err))
		return
	}
	resp.Diagnostics.Append(resp.State.Set(ctx, databricksSqlWarehouseCredentialsToModel(out, state.OauthClientSecretWoVersion, state.TokenWoVersion))...)
}

func (r *databricksSqlWarehouseCredentialsResource) Update(ctx context.Context, req resource.UpdateRequest, resp *resource.UpdateResponse) {
	ctx = sdk.WithTelemetryCommand(ctx, "montecarlo_databricks_sql_warehouse_credentials update")
	var plan, state resource_databricks_sql_warehouse_credentials.DatabricksSqlWarehouseCredentialsModel
	resp.Diagnostics.Append(req.Plan.Get(ctx, &plan)...)
	resp.Diagnostics.Append(req.State.Get(ctx, &state)...)
	// Terraform plans a write-only secret as null and passes it only in the configuration.
	var config resource_databricks_sql_warehouse_credentials.DatabricksSqlWarehouseCredentialsModel
	resp.Diagnostics.Append(req.Config.Get(ctx, &config)...)
	if resp.Diagnostics.HasError() {
		return
	}
	body := sdk.NewDatabricksSqlWarehouseCredentialsPatch()
	if !plan.AzureTenantId.IsNull() && !plan.AzureTenantId.IsUnknown() {
		body.SetAzureTenantId(plan.AzureTenantId.ValueString())
	}
	if !plan.AzureWorkspaceResourceId.IsNull() && !plan.AzureWorkspaceResourceId.IsUnknown() {
		body.SetAzureWorkspaceResourceId(plan.AzureWorkspaceResourceId.ValueString())
	}
	if !plan.OauthClientId.IsNull() && !plan.OauthClientId.IsUnknown() {
		body.SetOauthClientId(plan.OauthClientId.ValueString())
	}
	if !config.OauthClientSecretWo.IsNull() && !config.OauthClientSecretWo.IsUnknown() {
		body.SetOauthClientSecret(config.OauthClientSecretWo.ValueString())
	}
	if !plan.SqlWarehouseId.IsNull() && !plan.SqlWarehouseId.IsUnknown() {
		body.SetSqlWarehouseId(plan.SqlWarehouseId.ValueString())
	}
	if !config.TokenWo.IsNull() && !config.TokenWo.IsUnknown() {
		body.SetToken(config.TokenWo.ValueString())
	}
	if !plan.WorkspaceId.IsNull() && !plan.WorkspaceId.IsUnknown() {
		body.SetWorkspaceId(plan.WorkspaceId.ValueString())
	}
	if !plan.WorkspaceUrl.IsNull() && !plan.WorkspaceUrl.IsUnknown() {
		body.SetWorkspaceUrl(plan.WorkspaceUrl.ValueString())
	}
	// Retried: the spec marks this operation x-mc-retry-on-transient.
	out, err := withRetryOnTransient(ctx, func() (*sdk.DatabricksSqlWarehouseCredentialsOut, *http.Response, error) {
		return r.clients.api.CredentialsAPI.UpdateDatabricksSqlWarehouseCredentials(ctx, state.Id.ValueString()).DatabricksSqlWarehouseCredentialsPatch(*body).Execute()
	})
	if err != nil {
		resp.Diagnostics.AddError("Update databricks_sql_warehouse_credentials failed", apiErr(err))
		return
	}
	resp.Diagnostics.Append(resp.State.Set(ctx, databricksSqlWarehouseCredentialsToModel(out, plan.OauthClientSecretWoVersion, plan.TokenWoVersion))...)
}

func (r *databricksSqlWarehouseCredentialsResource) Delete(ctx context.Context, req resource.DeleteRequest, resp *resource.DeleteResponse) {
	ctx = sdk.WithTelemetryCommand(ctx, "montecarlo_databricks_sql_warehouse_credentials delete")
	var state resource_databricks_sql_warehouse_credentials.DatabricksSqlWarehouseCredentialsModel
	resp.Diagnostics.Append(req.State.Get(ctx, &state)...)
	if resp.Diagnostics.HasError() {
		return
	}
	if _, err := r.clients.api.CredentialsAPI.DeleteDatabricksSqlWarehouseCredentials(ctx, state.Id.ValueString()).Execute(); err != nil {
		resp.Diagnostics.AddError("Delete databricks_sql_warehouse_credentials failed", apiErr(err))
	}
}

func (r *databricksSqlWarehouseCredentialsResource) ImportState(ctx context.Context, req resource.ImportStateRequest, resp *resource.ImportStateResponse) {
	resource.ImportStatePassthroughID(ctx, path.Root("id"), req, resp)
}

func databricksSqlWarehouseCredentialsToModel(o *sdk.DatabricksSqlWarehouseCredentialsOut, oauth_client_secret_wo_version types.Int64, token_wo_version types.Int64) resource_databricks_sql_warehouse_credentials.DatabricksSqlWarehouseCredentialsModel {
	m := resource_databricks_sql_warehouse_credentials.DatabricksSqlWarehouseCredentialsModel{
		ConnectionType:             types.StringValue(o.GetConnectionType()),
		CreatedTime:                types.StringValue(o.GetCreatedTime().Format(time.RFC3339)),
		Id:                         types.StringValue(o.GetId()),
		SqlWarehouseId:             types.StringValue(o.GetSqlWarehouseId()),
		StorageType:                types.StringValue(string(o.GetStorageType())),
		WorkspaceUrl:               types.StringValue(o.GetWorkspaceUrl()),
		OauthClientSecretWoVersion: oauth_client_secret_wo_version,
		TokenWoVersion:             token_wo_version,
	}
	if v, ok := o.GetAzureTenantIdOk(); ok && v != nil {
		m.AzureTenantId = types.StringValue(*v)
	} else {
		m.AzureTenantId = types.StringNull()
	}
	if v, ok := o.GetAzureWorkspaceResourceIdOk(); ok && v != nil {
		m.AzureWorkspaceResourceId = types.StringValue(*v)
	} else {
		m.AzureWorkspaceResourceId = types.StringNull()
	}
	if v, ok := o.GetOauthClientIdOk(); ok && v != nil {
		m.OauthClientId = types.StringValue(*v)
	} else {
		m.OauthClientId = types.StringNull()
	}
	if v, ok := o.GetWorkspaceIdOk(); ok && v != nil {
		m.WorkspaceId = types.StringValue(*v)
	} else {
		m.WorkspaceId = types.StringNull()
	}
	// An unreturned field the config omits arrives unknown and no response fills it, so it
	// resolves to null. Terraform rejects an unknown after apply.
	if oauth_client_secret_wo_version.IsUnknown() {
		m.OauthClientSecretWoVersion = types.Int64Null()
	}
	if token_wo_version.IsUnknown() {
		m.TokenWoVersion = types.Int64Null()
	}
	return m
}
