// Code generated by api-codegen; DO NOT EDIT.
package provider

import (
	"context"
	"fmt"

	"github.com/hashicorp/terraform-plugin-framework/datasource"
	"github.com/hashicorp/terraform-plugin-framework/types"
	"time"

	sdk "github.com/monte-carlo-data/mc-sdk-go/montecarlo"
	"github.com/monte-carlo-data/terraform-provider-montecarlo/internal/schema_gen/datasource_databricks_sql_warehouse_credentials"
)

var (
	_ datasource.DataSource              = (*databricksSqlWarehouseCredentialsDataSource)(nil)
	_ datasource.DataSourceWithConfigure = (*databricksSqlWarehouseCredentialsDataSource)(nil)
)

type databricksSqlWarehouseCredentialsDataSource struct{ clients *clients }

func NewDatabricksSqlWarehouseCredentialsDataSource() datasource.DataSource {
	return &databricksSqlWarehouseCredentialsDataSource{}
}

func (d *databricksSqlWarehouseCredentialsDataSource) Metadata(_ context.Context, req datasource.MetadataRequest, resp *datasource.MetadataResponse) {
	resp.TypeName = req.ProviderTypeName + "_databricks_sql_warehouse_credentials"
}

func (d *databricksSqlWarehouseCredentialsDataSource) Schema(ctx context.Context, _ datasource.SchemaRequest, resp *datasource.SchemaResponse) {
	resp.Schema = datasource_databricks_sql_warehouse_credentials.DatabricksSqlWarehouseCredentialsDataSourceSchema(ctx)
}

func (d *databricksSqlWarehouseCredentialsDataSource) Configure(_ context.Context, req datasource.ConfigureRequest, resp *datasource.ConfigureResponse) {
	if req.ProviderData == nil {
		return
	}
	c, ok := req.ProviderData.(*clients)
	if !ok {
		resp.Diagnostics.AddError("unexpected provider data", fmt.Sprintf("got %T", req.ProviderData))
		return
	}
	d.clients = c
}

func (d *databricksSqlWarehouseCredentialsDataSource) Read(ctx context.Context, req datasource.ReadRequest, resp *datasource.ReadResponse) {
	ctx = sdk.WithTelemetryCommand(ctx, "data.montecarlo_databricks_sql_warehouse_credentials read")
	var cfg datasource_databricks_sql_warehouse_credentials.DatabricksSqlWarehouseCredentialsModel
	resp.Diagnostics.Append(req.Config.Get(ctx, &cfg)...)
	if resp.Diagnostics.HasError() {
		return
	}
	out, _, err := d.clients.api.CredentialsAPI.GetDatabricksSqlWarehouseCredentials(ctx, cfg.CredentialsId.ValueString()).Execute()
	if err != nil {
		resp.Diagnostics.AddError("Read databricks_sql_warehouse_credentials failed", apiErr(err))
		return
	}
	m := datasource_databricks_sql_warehouse_credentials.DatabricksSqlWarehouseCredentialsModel{
		CredentialsId:  cfg.CredentialsId,
		ConnectionType: types.StringValue(out.GetConnectionType()),
		CreatedTime:    types.StringValue(out.GetCreatedTime().Format(time.RFC3339)),
		Id:             types.StringValue(out.GetId()),
		SqlWarehouseId: types.StringValue(out.GetSqlWarehouseId()),
		StorageType:    types.StringValue(string(out.GetStorageType())),
		WorkspaceUrl:   types.StringValue(out.GetWorkspaceUrl()),
	}
	if v, ok := out.GetAzureTenantIdOk(); ok && v != nil {
		m.AzureTenantId = types.StringValue(*v)
	} else {
		m.AzureTenantId = types.StringNull()
	}
	if v, ok := out.GetAzureWorkspaceResourceIdOk(); ok && v != nil {
		m.AzureWorkspaceResourceId = types.StringValue(*v)
	} else {
		m.AzureWorkspaceResourceId = types.StringNull()
	}
	if v, ok := out.GetOauthClientIdOk(); ok && v != nil {
		m.OauthClientId = types.StringValue(*v)
	} else {
		m.OauthClientId = types.StringNull()
	}
	if v, ok := out.GetWorkspaceIdOk(); ok && v != nil {
		m.WorkspaceId = types.StringValue(*v)
	} else {
		m.WorkspaceId = types.StringNull()
	}
	resp.Diagnostics.Append(resp.State.Set(ctx, m)...)
}
