// Code generated by api-codegen; DO NOT EDIT.
package provider

import (
	"context"
	"fmt"
	"net/http"

	"github.com/hashicorp/terraform-plugin-framework/path"
	"github.com/hashicorp/terraform-plugin-framework/resource"
	"github.com/hashicorp/terraform-plugin-framework/types"
	"time"

	sdk "github.com/monte-carlo-data/mc-sdk-go/montecarlo"
	"github.com/monte-carlo-data/terraform-provider-montecarlo/internal/schema_gen/resource_etl_container"
)

var (
	_ resource.Resource                = (*etlContainerResource)(nil)
	_ resource.ResourceWithConfigure   = (*etlContainerResource)(nil)
	_ resource.ResourceWithImportState = (*etlContainerResource)(nil)
)

type etlContainerResource struct{ clients *clients }

func NewEtlContainerResource() resource.Resource { return &etlContainerResource{} }

func (r *etlContainerResource) Metadata(_ context.Context, req resource.MetadataRequest, resp *resource.MetadataResponse) {
	resp.TypeName = req.ProviderTypeName + "_etl_container"
}

func (r *etlContainerResource) Schema(ctx context.Context, _ resource.SchemaRequest, resp *resource.SchemaResponse) {
	s := resource_etl_container.EtlContainerResourceSchema(ctx)
	// These holds come before the replacements below: plan modifiers run in the order they are attached.
	// Updating the resource never changes these, and a null in state is final. Only the plain modifier copies a null.
	useStateForUnknown(s.Attributes, "etl_container.created_time", &resp.Diagnostics)
	useStateForUnknown(s.Attributes, "etl_container.deployment_id", &resp.Diagnostics)
	useStateForUnknown(s.Attributes, "etl_container.id", &resp.Diagnostics)
	useStateForUnknown(s.Attributes, "etl_container.is_synthetic", &resp.Diagnostics)
	useStateForUnknown(s.Attributes, "etl_container.type", &resp.Diagnostics)
	// The API accepts these on create and not on update, so changing one replaces the resource.
	requiresReplace(s.Attributes, "etl_container.deployment_id", &resp.Diagnostics)
	requiresReplace(s.Attributes, "etl_container.type", &resp.Diagnostics)
	resp.Schema = s
}

func (r *etlContainerResource) Configure(_ context.Context, req resource.ConfigureRequest, resp *resource.ConfigureResponse) {
	if req.ProviderData == nil {
		return
	}
	c, ok := req.ProviderData.(*clients)
	if !ok {
		resp.Diagnostics.AddError("unexpected provider data", fmt.Sprintf("got %T", req.ProviderData))
		return
	}
	r.clients = c
}

func (r *etlContainerResource) Create(ctx context.Context, req resource.CreateRequest, resp *resource.CreateResponse) {
	ctx = sdk.WithTelemetryCommand(ctx, "montecarlo_etl_container create")
	var plan resource_etl_container.EtlContainerModel
	resp.Diagnostics.Append(req.Plan.Get(ctx, &plan)...)
	if resp.Diagnostics.HasError() {
		return
	}
	body := sdk.NewEtlContainerIn(sdk.NewEtlContainerType(plan.Type.ValueString()), plan.Name.ValueString())
	if !plan.DeploymentId.IsNull() && !plan.DeploymentId.IsUnknown() {
		body.SetDeploymentId(plan.DeploymentId.ValueString())
	}
	// Retried: the spec marks this operation x-mc-retry-on-transient.
	out, err := withRetryOnTransient(ctx, func() (*sdk.EtlContainerOut, *http.Response, error) {
		return r.clients.api.EtlContainersAPI.CreateEtlContainer(ctx).EtlContainerIn(*body).Execute()
	})
	if err != nil {
		resp.Diagnostics.AddError("Create etl_container failed", apiErr(err))
		return
	}
	resp.Diagnostics.Append(resp.State.Set(ctx, etlContainerToModel(out))...)
}

func (r *etlContainerResource) Read(ctx context.Context, req resource.ReadRequest, resp *resource.ReadResponse) {
	ctx = sdk.WithTelemetryCommand(ctx, "montecarlo_etl_container read")
	var state resource_etl_container.EtlContainerModel
	resp.Diagnostics.Append(req.State.Get(ctx, &state)...)
	if resp.Diagnostics.HasError() {
		return
	}
	out, httpResp, err := r.clients.api.EtlContainersAPI.GetEtlContainer(ctx, state.Id.ValueString()).Execute()
	if err != nil {
		if httpResp != nil && httpResp.StatusCode == 404 {
			resp.State.RemoveResource(ctx)
			return
		}
		resp.Diagnostics.AddError("Read etl_container failed", apiErr(err))
		return
	}
	resp.Diagnostics.Append(resp.State.Set(ctx, etlContainerToModel(out))...)
}

func (r *etlContainerResource) Update(ctx context.Context, req resource.UpdateRequest, resp *resource.UpdateResponse) {
	ctx = sdk.WithTelemetryCommand(ctx, "montecarlo_etl_container update")
	var plan, state resource_etl_container.EtlContainerModel
	resp.Diagnostics.Append(req.Plan.Get(ctx, &plan)...)
	resp.Diagnostics.Append(req.State.Get(ctx, &state)...)
	if resp.Diagnostics.HasError() {
		return
	}
	body := sdk.NewEtlContainerPatch()
	if !plan.Name.IsNull() && !plan.Name.IsUnknown() {
		body.SetName(plan.Name.ValueString())
	}
	// Retried: the spec marks this operation x-mc-retry-on-transient.
	out, err := withRetryOnTransient(ctx, func() (*sdk.EtlContainerOut, *http.Response, error) {
		return r.clients.api.EtlContainersAPI.UpdateEtlContainer(ctx, state.Id.ValueString()).EtlContainerPatch(*body).Execute()
	})
	if err != nil {
		resp.Diagnostics.AddError("Update etl_container failed", apiErr(err))
		return
	}
	resp.Diagnostics.Append(resp.State.Set(ctx, etlContainerToModel(out))...)
}

func (r *etlContainerResource) Delete(ctx context.Context, req resource.DeleteRequest, resp *resource.DeleteResponse) {
	ctx = sdk.WithTelemetryCommand(ctx, "montecarlo_etl_container delete")
	var state resource_etl_container.EtlContainerModel
	resp.Diagnostics.Append(req.State.Get(ctx, &state)...)
	if resp.Diagnostics.HasError() {
		return
	}
	if _, err := r.clients.api.EtlContainersAPI.DeleteEtlContainer(ctx, state.Id.ValueString()).Execute(); err != nil {
		resp.Diagnostics.AddError("Delete etl_container failed", apiErr(err))
	}
}

func (r *etlContainerResource) ImportState(ctx context.Context, req resource.ImportStateRequest, resp *resource.ImportStateResponse) {
	resource.ImportStatePassthroughID(ctx, path.Root("id"), req, resp)
}

func etlContainerToModel(o *sdk.EtlContainerOut) resource_etl_container.EtlContainerModel {
	m := resource_etl_container.EtlContainerModel{
		CreatedTime: types.StringValue(o.GetCreatedTime().Format(time.RFC3339)),
		Id:          types.StringValue(o.GetId()),
		IsSynthetic: types.BoolValue(o.GetIsSynthetic()),
		Name:        types.StringValue(o.GetName()),
		Type:        types.StringValue(string(o.GetType())),
	}
	if v, ok := o.GetDeploymentIdOk(); ok && v != nil {
		m.DeploymentId = types.StringValue(*v)
	} else {
		m.DeploymentId = types.StringNull()
	}
	if v, ok := o.GetDeploymentNameOk(); ok && v != nil {
		m.DeploymentName = types.StringValue(*v)
	} else {
		m.DeploymentName = types.StringNull()
	}
	return m
}
