// Code generated by api-codegen; DO NOT EDIT.
package provider

import (
	"context"
	"fmt"

	"github.com/hashicorp/terraform-plugin-framework/datasource"
	"github.com/hashicorp/terraform-plugin-framework/types"
	"time"

	sdk "github.com/monte-carlo-data/mc-sdk-go/montecarlo"
	"github.com/monte-carlo-data/terraform-provider-montecarlo/internal/schema_gen/datasource_etl_container"
)

var (
	_ datasource.DataSource              = (*etlContainerDataSource)(nil)
	_ datasource.DataSourceWithConfigure = (*etlContainerDataSource)(nil)
)

type etlContainerDataSource struct{ clients *clients }

func NewEtlContainerDataSource() datasource.DataSource { return &etlContainerDataSource{} }

func (d *etlContainerDataSource) Metadata(_ context.Context, req datasource.MetadataRequest, resp *datasource.MetadataResponse) {
	resp.TypeName = req.ProviderTypeName + "_etl_container"
}

func (d *etlContainerDataSource) Schema(ctx context.Context, _ datasource.SchemaRequest, resp *datasource.SchemaResponse) {
	resp.Schema = datasource_etl_container.EtlContainerDataSourceSchema(ctx)
}

func (d *etlContainerDataSource) Configure(_ context.Context, req datasource.ConfigureRequest, resp *datasource.ConfigureResponse) {
	if req.ProviderData == nil {
		return
	}
	c, ok := req.ProviderData.(*clients)
	if !ok {
		resp.Diagnostics.AddError("unexpected provider data", fmt.Sprintf("got %T", req.ProviderData))
		return
	}
	d.clients = c
}

func (d *etlContainerDataSource) Read(ctx context.Context, req datasource.ReadRequest, resp *datasource.ReadResponse) {
	ctx = sdk.WithTelemetryCommand(ctx, "data.montecarlo_etl_container read")
	var cfg datasource_etl_container.EtlContainerModel
	resp.Diagnostics.Append(req.Config.Get(ctx, &cfg)...)
	if resp.Diagnostics.HasError() {
		return
	}
	out, _, err := d.clients.api.EtlContainersAPI.GetEtlContainer(ctx, cfg.EtlContainerId.ValueString()).Execute()
	if err != nil {
		resp.Diagnostics.AddError("Read etl_container failed", apiErr(err))
		return
	}
	m := datasource_etl_container.EtlContainerModel{
		EtlContainerId: cfg.EtlContainerId,
		CreatedTime:    types.StringValue(out.GetCreatedTime().Format(time.RFC3339)),
		Id:             types.StringValue(out.GetId()),
		IsSynthetic:    types.BoolValue(out.GetIsSynthetic()),
		Name:           types.StringValue(out.GetName()),
		Type:           types.StringValue(string(out.GetType())),
	}
	if v, ok := out.GetDeploymentIdOk(); ok && v != nil {
		m.DeploymentId = types.StringValue(*v)
	} else {
		m.DeploymentId = types.StringNull()
	}
	if v, ok := out.GetDeploymentNameOk(); ok && v != nil {
		m.DeploymentName = types.StringValue(*v)
	} else {
		m.DeploymentName = types.StringNull()
	}
	resp.Diagnostics.Append(resp.State.Set(ctx, m)...)
}
