// Code generated by api-codegen; DO NOT EDIT.
package provider

import (
	"context"
	"fmt"
	"net/http"

	"github.com/hashicorp/terraform-plugin-framework/path"
	"github.com/hashicorp/terraform-plugin-framework/resource"
	"github.com/hashicorp/terraform-plugin-framework/types"
	"time"

	sdk "github.com/monte-carlo-data/mc-sdk-go/montecarlo"
	"github.com/monte-carlo-data/terraform-provider-montecarlo/internal/schema_gen/resource_gcp_dataform_credentials"
)

var (
	_ resource.Resource                = (*gcpDataformCredentialsResource)(nil)
	_ resource.ResourceWithConfigure   = (*gcpDataformCredentialsResource)(nil)
	_ resource.ResourceWithImportState = (*gcpDataformCredentialsResource)(nil)
)

type gcpDataformCredentialsResource struct{ clients *clients }

func NewGcpDataformCredentialsResource() resource.Resource { return &gcpDataformCredentialsResource{} }

func (r *gcpDataformCredentialsResource) Metadata(_ context.Context, req resource.MetadataRequest, resp *resource.MetadataResponse) {
	resp.TypeName = req.ProviderTypeName + "_gcp_dataform_credentials"
}

func (r *gcpDataformCredentialsResource) Schema(ctx context.Context, _ resource.SchemaRequest, resp *resource.SchemaResponse) {
	s := resource_gcp_dataform_credentials.GcpDataformCredentialsResourceSchema(ctx)
	// Secrets: Terraform passes them to the provider on apply and never stores them.
	writeOnly(s.Attributes, "gcp_dataform_credentials.service_account_key_wo", &resp.Diagnostics)
	// Updating the resource never changes these, and a null in state is final. Only the plain modifier copies a null.
	useStateForUnknown(s.Attributes, "gcp_dataform_credentials.connection_type", &resp.Diagnostics)
	useStateForUnknown(s.Attributes, "gcp_dataform_credentials.created_time", &resp.Diagnostics)
	useStateForUnknown(s.Attributes, "gcp_dataform_credentials.id", &resp.Diagnostics)
	useStateForUnknown(s.Attributes, "gcp_dataform_credentials.storage_type", &resp.Diagnostics)
	resp.Schema = s
}

func (r *gcpDataformCredentialsResource) Configure(_ context.Context, req resource.ConfigureRequest, resp *resource.ConfigureResponse) {
	if req.ProviderData == nil {
		return
	}
	c, ok := req.ProviderData.(*clients)
	if !ok {
		resp.Diagnostics.AddError("unexpected provider data", fmt.Sprintf("got %T", req.ProviderData))
		return
	}
	r.clients = c
}

func (r *gcpDataformCredentialsResource) Create(ctx context.Context, req resource.CreateRequest, resp *resource.CreateResponse) {
	ctx = sdk.WithTelemetryCommand(ctx, "montecarlo_gcp_dataform_credentials create")
	var plan resource_gcp_dataform_credentials.GcpDataformCredentialsModel
	resp.Diagnostics.Append(req.Plan.Get(ctx, &plan)...)
	// Terraform plans a write-only secret as null and passes it only in the configuration.
	var config resource_gcp_dataform_credentials.GcpDataformCredentialsModel
	resp.Diagnostics.Append(req.Config.Get(ctx, &config)...)
	if resp.Diagnostics.HasError() {
		return
	}
	body := sdk.NewGcpDataformCredentialsIn(plan.ProjectId.ValueString(), listOfStrings(ctx, plan.Locations), config.ServiceAccountKeyWo.ValueString())
	// Retried: the spec marks this operation x-mc-retry-on-transient.
	out, err := withRetryOnTransient(ctx, func() (*sdk.GcpDataformCredentialsOut, *http.Response, error) {
		return r.clients.api.CredentialsAPI.CreateGcpDataformCredentials(ctx).GcpDataformCredentialsIn(*body).Execute()
	})
	if err != nil {
		resp.Diagnostics.AddError("Create gcp_dataform_credentials failed", apiErr(err))
		return
	}
	resp.Diagnostics.Append(resp.State.Set(ctx, gcpDataformCredentialsToModel(out, plan.ServiceAccountKeyWoVersion))...)
}

func (r *gcpDataformCredentialsResource) Read(ctx context.Context, req resource.ReadRequest, resp *resource.ReadResponse) {
	ctx = sdk.WithTelemetryCommand(ctx, "montecarlo_gcp_dataform_credentials read")
	var state resource_gcp_dataform_credentials.GcpDataformCredentialsModel
	resp.Diagnostics.Append(req.State.Get(ctx, &state)...)
	if resp.Diagnostics.HasError() {
		return
	}
	out, httpResp, err := r.clients.api.CredentialsAPI.GetGcpDataformCredentials(ctx, state.Id.ValueString()).Execute()
	if err != nil {
		if httpResp != nil && httpResp.StatusCode == 404 {
			resp.State.RemoveResource(ctx)
			return
		}
		resp.Diagnostics.AddError("Read gcp_dataform_credentials failed", apiErr(err))
		return
	}
	resp.Diagnostics.Append(resp.State.Set(ctx, gcpDataformCredentialsToModel(out, state.ServiceAccountKeyWoVersion))...)
}

func (r *gcpDataformCredentialsResource) Update(ctx context.Context, req resource.UpdateRequest, resp *resource.UpdateResponse) {
	ctx = sdk.WithTelemetryCommand(ctx, "montecarlo_gcp_dataform_credentials update")
	var plan, state resource_gcp_dataform_credentials.GcpDataformCredentialsModel
	resp.Diagnostics.Append(req.Plan.Get(ctx, &plan)...)
	resp.Diagnostics.Append(req.State.Get(ctx, &state)...)
	// Terraform plans a write-only secret as null and passes it only in the configuration.
	var config resource_gcp_dataform_credentials.GcpDataformCredentialsModel
	resp.Diagnostics.Append(req.Config.Get(ctx, &config)...)
	if resp.Diagnostics.HasError() {
		return
	}
	body := sdk.NewGcpDataformCredentialsPatch()
	if !plan.Locations.IsNull() && !plan.Locations.IsUnknown() {
		body.SetLocations(listOfStrings(ctx, plan.Locations))
	}
	if !plan.ProjectId.IsNull() && !plan.ProjectId.IsUnknown() {
		body.SetProjectId(plan.ProjectId.ValueString())
	}
	if !config.ServiceAccountKeyWo.IsNull() && !config.ServiceAccountKeyWo.IsUnknown() {
		body.SetServiceAccountKey(config.ServiceAccountKeyWo.ValueString())
	}
	// Retried: the spec marks this operation x-mc-retry-on-transient.
	out, err := withRetryOnTransient(ctx, func() (*sdk.GcpDataformCredentialsOut, *http.Response, error) {
		return r.clients.api.CredentialsAPI.UpdateGcpDataformCredentials(ctx, state.Id.ValueString()).GcpDataformCredentialsPatch(*body).Execute()
	})
	if err != nil {
		resp.Diagnostics.AddError("Update gcp_dataform_credentials failed", apiErr(err))
		return
	}
	resp.Diagnostics.Append(resp.State.Set(ctx, gcpDataformCredentialsToModel(out, plan.ServiceAccountKeyWoVersion))...)
}

func (r *gcpDataformCredentialsResource) Delete(ctx context.Context, req resource.DeleteRequest, resp *resource.DeleteResponse) {
	ctx = sdk.WithTelemetryCommand(ctx, "montecarlo_gcp_dataform_credentials delete")
	var state resource_gcp_dataform_credentials.GcpDataformCredentialsModel
	resp.Diagnostics.Append(req.State.Get(ctx, &state)...)
	if resp.Diagnostics.HasError() {
		return
	}
	if _, err := r.clients.api.CredentialsAPI.DeleteGcpDataformCredentials(ctx, state.Id.ValueString()).Execute(); err != nil {
		resp.Diagnostics.AddError("Delete gcp_dataform_credentials failed", apiErr(err))
	}
}

func (r *gcpDataformCredentialsResource) ImportState(ctx context.Context, req resource.ImportStateRequest, resp *resource.ImportStateResponse) {
	resource.ImportStatePassthroughID(ctx, path.Root("id"), req, resp)
}

func gcpDataformCredentialsToModel(o *sdk.GcpDataformCredentialsOut, service_account_key_wo_version types.Int64) resource_gcp_dataform_credentials.GcpDataformCredentialsModel {
	m := resource_gcp_dataform_credentials.GcpDataformCredentialsModel{
		ClientEmail:                types.StringValue(o.GetClientEmail()),
		ConnectionType:             types.StringValue(o.GetConnectionType()),
		CreatedTime:                types.StringValue(o.GetCreatedTime().Format(time.RFC3339)),
		Id:                         types.StringValue(o.GetId()),
		Locations:                  stringList(o.GetLocations()),
		ProjectId:                  types.StringValue(o.GetProjectId()),
		StorageType:                types.StringValue(string(o.GetStorageType())),
		ServiceAccountKeyWoVersion: service_account_key_wo_version,
	}
	// An unreturned field the config omits arrives unknown and no response fills it, so it
	// resolves to null. Terraform rejects an unknown after apply.
	if service_account_key_wo_version.IsUnknown() {
		m.ServiceAccountKeyWoVersion = types.Int64Null()
	}
	return m
}
