// Code generated by api-codegen; DO NOT EDIT.
package provider

import (
	"context"
	"fmt"
	"net/http"

	"github.com/hashicorp/terraform-plugin-framework/path"
	"github.com/hashicorp/terraform-plugin-framework/resource"
	"github.com/hashicorp/terraform-plugin-framework/types"
	"time"

	sdk "github.com/monte-carlo-data/mc-sdk-go/montecarlo"
	"github.com/monte-carlo-data/terraform-provider-montecarlo/internal/schema_gen/resource_informatica_v2_credentials"
)

var (
	_ resource.Resource                = (*informaticaV2CredentialsResource)(nil)
	_ resource.ResourceWithConfigure   = (*informaticaV2CredentialsResource)(nil)
	_ resource.ResourceWithImportState = (*informaticaV2CredentialsResource)(nil)
)

type informaticaV2CredentialsResource struct{ clients *clients }

func NewInformaticaV2CredentialsResource() resource.Resource {
	return &informaticaV2CredentialsResource{}
}

func (r *informaticaV2CredentialsResource) Metadata(_ context.Context, req resource.MetadataRequest, resp *resource.MetadataResponse) {
	resp.TypeName = req.ProviderTypeName + "_informatica_v2_credentials"
}

func (r *informaticaV2CredentialsResource) Schema(ctx context.Context, _ resource.SchemaRequest, resp *resource.SchemaResponse) {
	s := resource_informatica_v2_credentials.InformaticaV2CredentialsResourceSchema(ctx)
	// Secrets: Terraform passes them to the provider on apply and never stores them.
	writeOnly(s.Attributes, "informatica_v2_credentials.oauth_client_secret_wo", &resp.Diagnostics)
	writeOnly(s.Attributes, "informatica_v2_credentials.oauth_password_wo", &resp.Diagnostics)
	writeOnly(s.Attributes, "informatica_v2_credentials.password_wo", &resp.Diagnostics)
	// Updating the resource never changes these, and a null in state is final. Only the plain modifier copies a null.
	useStateForUnknown(s.Attributes, "informatica_v2_credentials.connection_type", &resp.Diagnostics)
	useStateForUnknown(s.Attributes, "informatica_v2_credentials.created_time", &resp.Diagnostics)
	useStateForUnknown(s.Attributes, "informatica_v2_credentials.id", &resp.Diagnostics)
	useStateForUnknown(s.Attributes, "informatica_v2_credentials.storage_type", &resp.Diagnostics)
	resp.Schema = s
}

func (r *informaticaV2CredentialsResource) Configure(_ context.Context, req resource.ConfigureRequest, resp *resource.ConfigureResponse) {
	if req.ProviderData == nil {
		return
	}
	c, ok := req.ProviderData.(*clients)
	if !ok {
		resp.Diagnostics.AddError("unexpected provider data", fmt.Sprintf("got %T", req.ProviderData))
		return
	}
	r.clients = c
}

func (r *informaticaV2CredentialsResource) Create(ctx context.Context, req resource.CreateRequest, resp *resource.CreateResponse) {
	ctx = sdk.WithTelemetryCommand(ctx, "montecarlo_informatica_v2_credentials create")
	var plan resource_informatica_v2_credentials.InformaticaV2CredentialsModel
	resp.Diagnostics.Append(req.Plan.Get(ctx, &plan)...)
	// Terraform plans a write-only secret as null and passes it only in the configuration.
	var config resource_informatica_v2_credentials.InformaticaV2CredentialsModel
	resp.Diagnostics.Append(req.Config.Get(ctx, &config)...)
	if resp.Diagnostics.HasError() {
		return
	}
	body := sdk.NewInformaticaV2CredentialsIn(sdk.InformaticaV2AuthMode(plan.AuthMode.ValueString()))
	if !plan.BaseUrl.IsNull() && !plan.BaseUrl.IsUnknown() {
		body.SetBaseUrl(plan.BaseUrl.ValueString())
	}
	if !plan.OauthAccessTokenEndpoint.IsNull() && !plan.OauthAccessTokenEndpoint.IsUnknown() {
		body.SetOauthAccessTokenEndpoint(plan.OauthAccessTokenEndpoint.ValueString())
	}
	if !plan.OauthClientId.IsNull() && !plan.OauthClientId.IsUnknown() {
		body.SetOauthClientId(plan.OauthClientId.ValueString())
	}
	if !config.OauthClientSecretWo.IsNull() && !config.OauthClientSecretWo.IsUnknown() {
		body.SetOauthClientSecret(config.OauthClientSecretWo.ValueString())
	}
	if !plan.OauthGrantType.IsNull() && !plan.OauthGrantType.IsUnknown() {
		body.SetOauthGrantType(sdk.OAuthGrantType(plan.OauthGrantType.ValueString()))
	}
	if !config.OauthPasswordWo.IsNull() && !config.OauthPasswordWo.IsUnknown() {
		body.SetOauthPassword(config.OauthPasswordWo.ValueString())
	}
	if !plan.OauthScope.IsNull() && !plan.OauthScope.IsUnknown() {
		body.SetOauthScope(plan.OauthScope.ValueString())
	}
	if !plan.OauthUsername.IsNull() && !plan.OauthUsername.IsUnknown() {
		body.SetOauthUsername(plan.OauthUsername.ValueString())
	}
	if !plan.OrgId.IsNull() && !plan.OrgId.IsUnknown() {
		body.SetOrgId(plan.OrgId.ValueString())
	}
	if !config.PasswordWo.IsNull() && !config.PasswordWo.IsUnknown() {
		body.SetPassword(config.PasswordWo.ValueString())
	}
	if !plan.Username.IsNull() && !plan.Username.IsUnknown() {
		body.SetUsername(plan.Username.ValueString())
	}
	// Retried: the spec marks this operation x-mc-retry-on-transient.
	out, err := withRetryOnTransient(ctx, func() (*sdk.InformaticaV2CredentialsOut, *http.Response, error) {
		return r.clients.api.CredentialsAPI.CreateInformaticaV2Credentials(ctx).InformaticaV2CredentialsIn(*body).Execute()
	})
	if err != nil {
		resp.Diagnostics.AddError("Create informatica_v2_credentials failed", apiErr(err))
		return
	}
	resp.Diagnostics.Append(resp.State.Set(ctx, informaticaV2CredentialsToModel(out, plan.OauthClientSecretWoVersion, plan.OauthPasswordWoVersion, plan.PasswordWoVersion))...)
}

func (r *informaticaV2CredentialsResource) Read(ctx context.Context, req resource.ReadRequest, resp *resource.ReadResponse) {
	ctx = sdk.WithTelemetryCommand(ctx, "montecarlo_informatica_v2_credentials read")
	var state resource_informatica_v2_credentials.InformaticaV2CredentialsModel
	resp.Diagnostics.Append(req.State.Get(ctx, &state)...)
	if resp.Diagnostics.HasError() {
		return
	}
	out, httpResp, err := r.clients.api.CredentialsAPI.GetInformaticaV2Credentials(ctx, state.Id.ValueString()).Execute()
	if err != nil {
		if httpResp != nil && httpResp.StatusCode == 404 {
			resp.State.RemoveResource(ctx)
			return
		}
		resp.Diagnostics.AddError("Read informatica_v2_credentials failed", apiErr(err))
		return
	}
	resp.Diagnostics.Append(resp.State.Set(ctx, informaticaV2CredentialsToModel(out, state.OauthClientSecretWoVersion, state.OauthPasswordWoVersion, state.PasswordWoVersion))...)
}

func (r *informaticaV2CredentialsResource) Update(ctx context.Context, req resource.UpdateRequest, resp *resource.UpdateResponse) {
	ctx = sdk.WithTelemetryCommand(ctx, "montecarlo_informatica_v2_credentials update")
	var plan, state resource_informatica_v2_credentials.InformaticaV2CredentialsModel
	resp.Diagnostics.Append(req.Plan.Get(ctx, &plan)...)
	resp.Diagnostics.Append(req.State.Get(ctx, &state)...)
	// Terraform plans a write-only secret as null and passes it only in the configuration.
	var config resource_informatica_v2_credentials.InformaticaV2CredentialsModel
	resp.Diagnostics.Append(req.Config.Get(ctx, &config)...)
	if resp.Diagnostics.HasError() {
		return
	}
	body := sdk.NewInformaticaV2CredentialsPatch()
	if !plan.AuthMode.IsNull() && !plan.AuthMode.IsUnknown() {
		body.SetAuthMode(sdk.InformaticaV2AuthMode(plan.AuthMode.ValueString()))
	}
	if !plan.BaseUrl.IsNull() && !plan.BaseUrl.IsUnknown() {
		body.SetBaseUrl(plan.BaseUrl.ValueString())
	}
	if !plan.OauthAccessTokenEndpoint.IsNull() && !plan.OauthAccessTokenEndpoint.IsUnknown() {
		body.SetOauthAccessTokenEndpoint(plan.OauthAccessTokenEndpoint.ValueString())
	}
	if !plan.OauthClientId.IsNull() && !plan.OauthClientId.IsUnknown() {
		body.SetOauthClientId(plan.OauthClientId.ValueString())
	}
	if !config.OauthClientSecretWo.IsNull() && !config.OauthClientSecretWo.IsUnknown() {
		body.SetOauthClientSecret(config.OauthClientSecretWo.ValueString())
	}
	if !plan.OauthGrantType.IsNull() && !plan.OauthGrantType.IsUnknown() {
		body.SetOauthGrantType(sdk.OAuthGrantType(plan.OauthGrantType.ValueString()))
	}
	if !config.OauthPasswordWo.IsNull() && !config.OauthPasswordWo.IsUnknown() {
		body.SetOauthPassword(config.OauthPasswordWo.ValueString())
	}
	if !plan.OauthScope.IsNull() && !plan.OauthScope.IsUnknown() {
		body.SetOauthScope(plan.OauthScope.ValueString())
	}
	if !plan.OauthUsername.IsNull() && !plan.OauthUsername.IsUnknown() {
		body.SetOauthUsername(plan.OauthUsername.ValueString())
	}
	if !plan.OrgId.IsNull() && !plan.OrgId.IsUnknown() {
		body.SetOrgId(plan.OrgId.ValueString())
	}
	if !config.PasswordWo.IsNull() && !config.PasswordWo.IsUnknown() {
		body.SetPassword(config.PasswordWo.ValueString())
	}
	if !plan.Username.IsNull() && !plan.Username.IsUnknown() {
		body.SetUsername(plan.Username.ValueString())
	}
	// Retried: the spec marks this operation x-mc-retry-on-transient.
	out, err := withRetryOnTransient(ctx, func() (*sdk.InformaticaV2CredentialsOut, *http.Response, error) {
		return r.clients.api.CredentialsAPI.UpdateInformaticaV2Credentials(ctx, state.Id.ValueString()).InformaticaV2CredentialsPatch(*body).Execute()
	})
	if err != nil {
		resp.Diagnostics.AddError("Update informatica_v2_credentials failed", apiErr(err))
		return
	}
	resp.Diagnostics.Append(resp.State.Set(ctx, informaticaV2CredentialsToModel(out, plan.OauthClientSecretWoVersion, plan.OauthPasswordWoVersion, plan.PasswordWoVersion))...)
}

func (r *informaticaV2CredentialsResource) Delete(ctx context.Context, req resource.DeleteRequest, resp *resource.DeleteResponse) {
	ctx = sdk.WithTelemetryCommand(ctx, "montecarlo_informatica_v2_credentials delete")
	var state resource_informatica_v2_credentials.InformaticaV2CredentialsModel
	resp.Diagnostics.Append(req.State.Get(ctx, &state)...)
	if resp.Diagnostics.HasError() {
		return
	}
	if _, err := r.clients.api.CredentialsAPI.DeleteInformaticaV2Credentials(ctx, state.Id.ValueString()).Execute(); err != nil {
		resp.Diagnostics.AddError("Delete informatica_v2_credentials failed", apiErr(err))
	}
}

func (r *informaticaV2CredentialsResource) ImportState(ctx context.Context, req resource.ImportStateRequest, resp *resource.ImportStateResponse) {
	resource.ImportStatePassthroughID(ctx, path.Root("id"), req, resp)
}

func informaticaV2CredentialsToModel(o *sdk.InformaticaV2CredentialsOut, oauth_client_secret_wo_version types.Int64, oauth_password_wo_version types.Int64, password_wo_version types.Int64) resource_informatica_v2_credentials.InformaticaV2CredentialsModel {
	m := resource_informatica_v2_credentials.InformaticaV2CredentialsModel{
		AuthMode:                   types.StringValue(string(o.GetAuthMode())),
		ConnectionType:             types.StringValue(o.GetConnectionType()),
		CreatedTime:                types.StringValue(o.GetCreatedTime().Format(time.RFC3339)),
		Id:                         types.StringValue(o.GetId()),
		StorageType:                types.StringValue(string(o.GetStorageType())),
		OauthClientSecretWoVersion: oauth_client_secret_wo_version,
		OauthPasswordWoVersion:     oauth_password_wo_version,
		PasswordWoVersion:          password_wo_version,
	}
	if v, ok := o.GetBaseUrlOk(); ok && v != nil {
		m.BaseUrl = types.StringValue(*v)
	} else {
		m.BaseUrl = types.StringNull()
	}
	if v, ok := o.GetOauthAccessTokenEndpointOk(); ok && v != nil {
		m.OauthAccessTokenEndpoint = types.StringValue(*v)
	} else {
		m.OauthAccessTokenEndpoint = types.StringNull()
	}
	if v, ok := o.GetOauthClientIdOk(); ok && v != nil {
		m.OauthClientId = types.StringValue(*v)
	} else {
		m.OauthClientId = types.StringNull()
	}
	if v, ok := o.GetOauthGrantTypeOk(); ok && v != nil {
		m.OauthGrantType = types.StringValue(string(*v))
	} else {
		m.OauthGrantType = types.StringNull()
	}
	if v, ok := o.GetOauthScopeOk(); ok && v != nil {
		m.OauthScope = types.StringValue(*v)
	} else {
		m.OauthScope = types.StringNull()
	}
	if v, ok := o.GetOauthUsernameOk(); ok && v != nil {
		m.OauthUsername = types.StringValue(*v)
	} else {
		m.OauthUsername = types.StringNull()
	}
	if v, ok := o.GetOrgIdOk(); ok && v != nil {
		m.OrgId = types.StringValue(*v)
	} else {
		m.OrgId = types.StringNull()
	}
	if v, ok := o.GetUsernameOk(); ok && v != nil {
		m.Username = types.StringValue(*v)
	} else {
		m.Username = types.StringNull()
	}
	// An unreturned field the config omits arrives unknown and no response fills it, so it
	// resolves to null. Terraform rejects an unknown after apply.
	if oauth_client_secret_wo_version.IsUnknown() {
		m.OauthClientSecretWoVersion = types.Int64Null()
	}
	if oauth_password_wo_version.IsUnknown() {
		m.OauthPasswordWoVersion = types.Int64Null()
	}
	if password_wo_version.IsUnknown() {
		m.PasswordWoVersion = types.Int64Null()
	}
	return m
}
