// Code generated by api-codegen; DO NOT EDIT.
package provider

import (
	"context"
	"fmt"

	"github.com/hashicorp/terraform-plugin-framework/datasource"
	"github.com/hashicorp/terraform-plugin-framework/types"
	"time"

	sdk "github.com/monte-carlo-data/mc-sdk-go/montecarlo"
	"github.com/monte-carlo-data/terraform-provider-montecarlo/internal/schema_gen/datasource_mulesoft_credentials"
)

var (
	_ datasource.DataSource              = (*mulesoftCredentialsDataSource)(nil)
	_ datasource.DataSourceWithConfigure = (*mulesoftCredentialsDataSource)(nil)
)

type mulesoftCredentialsDataSource struct{ clients *clients }

func NewMulesoftCredentialsDataSource() datasource.DataSource {
	return &mulesoftCredentialsDataSource{}
}

func (d *mulesoftCredentialsDataSource) Metadata(_ context.Context, req datasource.MetadataRequest, resp *datasource.MetadataResponse) {
	resp.TypeName = req.ProviderTypeName + "_mulesoft_credentials"
}

func (d *mulesoftCredentialsDataSource) Schema(ctx context.Context, _ datasource.SchemaRequest, resp *datasource.SchemaResponse) {
	resp.Schema = datasource_mulesoft_credentials.MulesoftCredentialsDataSourceSchema(ctx)
}

func (d *mulesoftCredentialsDataSource) Configure(_ context.Context, req datasource.ConfigureRequest, resp *datasource.ConfigureResponse) {
	if req.ProviderData == nil {
		return
	}
	c, ok := req.ProviderData.(*clients)
	if !ok {
		resp.Diagnostics.AddError("unexpected provider data", fmt.Sprintf("got %T", req.ProviderData))
		return
	}
	d.clients = c
}

func (d *mulesoftCredentialsDataSource) Read(ctx context.Context, req datasource.ReadRequest, resp *datasource.ReadResponse) {
	ctx = sdk.WithTelemetryCommand(ctx, "data.montecarlo_mulesoft_credentials read")
	var cfg datasource_mulesoft_credentials.MulesoftCredentialsModel
	resp.Diagnostics.Append(req.Config.Get(ctx, &cfg)...)
	if resp.Diagnostics.HasError() {
		return
	}
	out, _, err := d.clients.api.CredentialsAPI.GetMulesoftCredentials(ctx, cfg.CredentialsId.ValueString()).Execute()
	if err != nil {
		resp.Diagnostics.AddError("Read mulesoft_credentials failed", apiErr(err))
		return
	}
	m := datasource_mulesoft_credentials.MulesoftCredentialsModel{
		CredentialsId:  cfg.CredentialsId,
		AppClientId:    types.StringValue(out.GetAppClientId()),
		ConnectionType: types.StringValue(out.GetConnectionType()),
		CreatedTime:    types.StringValue(out.GetCreatedTime().Format(time.RFC3339)),
		Id:             types.StringValue(out.GetId()),
		Region:         types.StringValue(string(out.GetRegion())),
		StorageType:    types.StringValue(string(out.GetStorageType())),
	}
	if v, ok := out.GetOrgIdOk(); ok && v != nil {
		m.OrgId = types.StringValue(*v)
	} else {
		m.OrgId = types.StringNull()
	}
	resp.Diagnostics.Append(resp.State.Set(ctx, m)...)
}
