// Code generated by api-codegen; DO NOT EDIT.
package provider

import (
	"context"
	"fmt"
	"net/http"

	"github.com/hashicorp/terraform-plugin-framework/path"
	"github.com/hashicorp/terraform-plugin-framework/resource"
	"github.com/hashicorp/terraform-plugin-framework/types"
	"time"

	sdk "github.com/monte-carlo-data/mc-sdk-go/montecarlo"
	"github.com/monte-carlo-data/terraform-provider-montecarlo/internal/schema_gen/resource_oracle_credentials"
)

var (
	_ resource.Resource                = (*oracleCredentialsResource)(nil)
	_ resource.ResourceWithConfigure   = (*oracleCredentialsResource)(nil)
	_ resource.ResourceWithImportState = (*oracleCredentialsResource)(nil)
)

type oracleCredentialsResource struct{ clients *clients }

func NewOracleCredentialsResource() resource.Resource { return &oracleCredentialsResource{} }

func (r *oracleCredentialsResource) Metadata(_ context.Context, req resource.MetadataRequest, resp *resource.MetadataResponse) {
	resp.TypeName = req.ProviderTypeName + "_oracle_credentials"
}

func (r *oracleCredentialsResource) Schema(ctx context.Context, _ resource.SchemaRequest, resp *resource.SchemaResponse) {
	s := resource_oracle_credentials.OracleCredentialsResourceSchema(ctx)
	// Secrets: Terraform passes them to the provider on apply and never stores them.
	writeOnly(s.Attributes, "oracle_credentials.password_wo", &resp.Diagnostics)
	// Updating the resource never changes these, so the plan keeps what state holds.
	useNonNullStateForUnknown(s.Attributes, "oracle_credentials.connection_type", &resp.Diagnostics)
	useNonNullStateForUnknown(s.Attributes, "oracle_credentials.created_time", &resp.Diagnostics)
	useNonNullStateForUnknown(s.Attributes, "oracle_credentials.id", &resp.Diagnostics)
	useNonNullStateForUnknown(s.Attributes, "oracle_credentials.storage_type", &resp.Diagnostics)
	resp.Schema = s
}

func (r *oracleCredentialsResource) Configure(_ context.Context, req resource.ConfigureRequest, resp *resource.ConfigureResponse) {
	if req.ProviderData == nil {
		return
	}
	c, ok := req.ProviderData.(*clients)
	if !ok {
		resp.Diagnostics.AddError("unexpected provider data", fmt.Sprintf("got %T", req.ProviderData))
		return
	}
	r.clients = c
}

func (r *oracleCredentialsResource) Create(ctx context.Context, req resource.CreateRequest, resp *resource.CreateResponse) {
	ctx = sdk.WithTelemetryCommand(ctx, "montecarlo_oracle_credentials create")
	var plan resource_oracle_credentials.OracleCredentialsModel
	resp.Diagnostics.Append(req.Plan.Get(ctx, &plan)...)
	// Terraform plans a write-only secret as null and passes it only in the configuration.
	var config resource_oracle_credentials.OracleCredentialsModel
	resp.Diagnostics.Append(req.Config.Get(ctx, &config)...)
	if resp.Diagnostics.HasError() {
		return
	}
	body := sdk.NewOracleCredentialsIn(plan.Host.ValueString(), int32(plan.Port.ValueInt64()), plan.User.ValueString(), config.PasswordWo.ValueString(), plan.DbName.ValueString())
	if !plan.SslCaData.IsNull() && !plan.SslCaData.IsUnknown() {
		body.SetSslCaData(plan.SslCaData.ValueString())
	}
	if !plan.SslDisabled.IsNull() && !plan.SslDisabled.IsUnknown() {
		body.SetSslDisabled(plan.SslDisabled.ValueBool())
	}
	if !plan.SslSkipCertVerification.IsNull() && !plan.SslSkipCertVerification.IsUnknown() {
		body.SetSslSkipCertVerification(plan.SslSkipCertVerification.ValueBool())
	}
	if !plan.SslVerifyCert.IsNull() && !plan.SslVerifyCert.IsUnknown() {
		body.SetSslVerifyCert(plan.SslVerifyCert.ValueBool())
	}
	if !plan.SslVerifyIdentity.IsNull() && !plan.SslVerifyIdentity.IsUnknown() {
		body.SetSslVerifyIdentity(plan.SslVerifyIdentity.ValueBool())
	}
	// Retried: the spec marks this operation x-mc-retry-on-transient.
	out, err := withRetryOnTransient(ctx, func() (*sdk.OracleCredentialsOut, *http.Response, error) {
		return r.clients.api.CredentialsAPI.CreateOracleCredentials(ctx).OracleCredentialsIn(*body).Execute()
	})
	if err != nil {
		resp.Diagnostics.AddError("Create oracle_credentials failed", apiErr(err))
		return
	}
	resp.Diagnostics.Append(resp.State.Set(ctx, oracleCredentialsToModel(out, plan.PasswordWoVersion))...)
}

func (r *oracleCredentialsResource) Read(ctx context.Context, req resource.ReadRequest, resp *resource.ReadResponse) {
	ctx = sdk.WithTelemetryCommand(ctx, "montecarlo_oracle_credentials read")
	var state resource_oracle_credentials.OracleCredentialsModel
	resp.Diagnostics.Append(req.State.Get(ctx, &state)...)
	if resp.Diagnostics.HasError() {
		return
	}
	out, httpResp, err := r.clients.api.CredentialsAPI.GetOracleCredentials(ctx, state.Id.ValueString()).Execute()
	if err != nil {
		if httpResp != nil && httpResp.StatusCode == 404 {
			resp.State.RemoveResource(ctx)
			return
		}
		resp.Diagnostics.AddError("Read oracle_credentials failed", apiErr(err))
		return
	}
	resp.Diagnostics.Append(resp.State.Set(ctx, oracleCredentialsToModel(out, state.PasswordWoVersion))...)
}

func (r *oracleCredentialsResource) Update(ctx context.Context, req resource.UpdateRequest, resp *resource.UpdateResponse) {
	ctx = sdk.WithTelemetryCommand(ctx, "montecarlo_oracle_credentials update")
	var plan, state resource_oracle_credentials.OracleCredentialsModel
	resp.Diagnostics.Append(req.Plan.Get(ctx, &plan)...)
	resp.Diagnostics.Append(req.State.Get(ctx, &state)...)
	// Terraform plans a write-only secret as null and passes it only in the configuration.
	var config resource_oracle_credentials.OracleCredentialsModel
	resp.Diagnostics.Append(req.Config.Get(ctx, &config)...)
	if resp.Diagnostics.HasError() {
		return
	}
	body := sdk.NewOracleCredentialsPatch()
	if !plan.DbName.IsNull() && !plan.DbName.IsUnknown() {
		body.SetDbName(plan.DbName.ValueString())
	}
	if !plan.Host.IsNull() && !plan.Host.IsUnknown() {
		body.SetHost(plan.Host.ValueString())
	}
	if !config.PasswordWo.IsNull() && !config.PasswordWo.IsUnknown() {
		body.SetPassword(config.PasswordWo.ValueString())
	}
	if !plan.Port.IsNull() && !plan.Port.IsUnknown() {
		body.SetPort(int32(plan.Port.ValueInt64()))
	}
	if !plan.SslCaData.IsNull() && !plan.SslCaData.IsUnknown() {
		body.SetSslCaData(plan.SslCaData.ValueString())
	}
	if !plan.SslDisabled.IsNull() && !plan.SslDisabled.IsUnknown() {
		body.SetSslDisabled(plan.SslDisabled.ValueBool())
	}
	if !plan.SslSkipCertVerification.IsNull() && !plan.SslSkipCertVerification.IsUnknown() {
		body.SetSslSkipCertVerification(plan.SslSkipCertVerification.ValueBool())
	}
	if !plan.SslVerifyCert.IsNull() && !plan.SslVerifyCert.IsUnknown() {
		body.SetSslVerifyCert(plan.SslVerifyCert.ValueBool())
	}
	if !plan.SslVerifyIdentity.IsNull() && !plan.SslVerifyIdentity.IsUnknown() {
		body.SetSslVerifyIdentity(plan.SslVerifyIdentity.ValueBool())
	}
	if !plan.User.IsNull() && !plan.User.IsUnknown() {
		body.SetUser(plan.User.ValueString())
	}
	// Retried: the spec marks this operation x-mc-retry-on-transient.
	out, err := withRetryOnTransient(ctx, func() (*sdk.OracleCredentialsOut, *http.Response, error) {
		return r.clients.api.CredentialsAPI.UpdateOracleCredentials(ctx, state.Id.ValueString()).OracleCredentialsPatch(*body).Execute()
	})
	if err != nil {
		resp.Diagnostics.AddError("Update oracle_credentials failed", apiErr(err))
		return
	}
	resp.Diagnostics.Append(resp.State.Set(ctx, oracleCredentialsToModel(out, plan.PasswordWoVersion))...)
}

func (r *oracleCredentialsResource) Delete(ctx context.Context, req resource.DeleteRequest, resp *resource.DeleteResponse) {
	ctx = sdk.WithTelemetryCommand(ctx, "montecarlo_oracle_credentials delete")
	var state resource_oracle_credentials.OracleCredentialsModel
	resp.Diagnostics.Append(req.State.Get(ctx, &state)...)
	if resp.Diagnostics.HasError() {
		return
	}
	if _, err := r.clients.api.CredentialsAPI.DeleteOracleCredentials(ctx, state.Id.ValueString()).Execute(); err != nil {
		resp.Diagnostics.AddError("Delete oracle_credentials failed", apiErr(err))
	}
}

func (r *oracleCredentialsResource) ImportState(ctx context.Context, req resource.ImportStateRequest, resp *resource.ImportStateResponse) {
	resource.ImportStatePassthroughID(ctx, path.Root("id"), req, resp)
}

func oracleCredentialsToModel(o *sdk.OracleCredentialsOut, password_wo_version types.Int64) resource_oracle_credentials.OracleCredentialsModel {
	m := resource_oracle_credentials.OracleCredentialsModel{
		ConnectionType:    types.StringValue(o.GetConnectionType()),
		CreatedTime:       types.StringValue(o.GetCreatedTime().Format(time.RFC3339)),
		DbName:            types.StringValue(o.GetDbName()),
		Host:              types.StringValue(o.GetHost()),
		Id:                types.StringValue(o.GetId()),
		Port:              types.Int64Value(int64(o.GetPort())),
		StorageType:       types.StringValue(string(o.GetStorageType())),
		User:              types.StringValue(o.GetUser()),
		PasswordWoVersion: password_wo_version,
	}
	if v, ok := o.GetSslCaDataOk(); ok && v != nil {
		m.SslCaData = types.StringValue(*v)
	} else {
		m.SslCaData = types.StringNull()
	}
	if v, ok := o.GetSslDisabledOk(); ok && v != nil {
		m.SslDisabled = types.BoolValue(*v)
	} else {
		m.SslDisabled = types.BoolNull()
	}
	if v, ok := o.GetSslSkipCertVerificationOk(); ok && v != nil {
		m.SslSkipCertVerification = types.BoolValue(*v)
	} else {
		m.SslSkipCertVerification = types.BoolNull()
	}
	if v, ok := o.GetSslVerifyCertOk(); ok && v != nil {
		m.SslVerifyCert = types.BoolValue(*v)
	} else {
		m.SslVerifyCert = types.BoolNull()
	}
	if v, ok := o.GetSslVerifyIdentityOk(); ok && v != nil {
		m.SslVerifyIdentity = types.BoolValue(*v)
	} else {
		m.SslVerifyIdentity = types.BoolNull()
	}
	// An unreturned field the config omits arrives unknown and no response fills it, so it
	// resolves to null. Terraform rejects an unknown after apply.
	if password_wo_version.IsUnknown() {
		m.PasswordWoVersion = types.Int64Null()
	}
	return m
}
