// Code generated by api-codegen; DO NOT EDIT.
package provider

import (
	"context"
	"fmt"

	"github.com/hashicorp/terraform-plugin-framework/datasource"
	"github.com/hashicorp/terraform-plugin-framework/types"
	"time"

	sdk "github.com/monte-carlo-data/mc-sdk-go/montecarlo"
	"github.com/monte-carlo-data/terraform-provider-montecarlo/internal/schema_gen/datasource_postgres_credentials"
)

var (
	_ datasource.DataSource              = (*postgresCredentialsDataSource)(nil)
	_ datasource.DataSourceWithConfigure = (*postgresCredentialsDataSource)(nil)
)

type postgresCredentialsDataSource struct{ clients *clients }

func NewPostgresCredentialsDataSource() datasource.DataSource {
	return &postgresCredentialsDataSource{}
}

func (d *postgresCredentialsDataSource) Metadata(_ context.Context, req datasource.MetadataRequest, resp *datasource.MetadataResponse) {
	resp.TypeName = req.ProviderTypeName + "_postgres_credentials"
}

func (d *postgresCredentialsDataSource) Schema(ctx context.Context, _ datasource.SchemaRequest, resp *datasource.SchemaResponse) {
	resp.Schema = datasource_postgres_credentials.PostgresCredentialsDataSourceSchema(ctx)
}

func (d *postgresCredentialsDataSource) Configure(_ context.Context, req datasource.ConfigureRequest, resp *datasource.ConfigureResponse) {
	if req.ProviderData == nil {
		return
	}
	c, ok := req.ProviderData.(*clients)
	if !ok {
		resp.Diagnostics.AddError("unexpected provider data", fmt.Sprintf("got %T", req.ProviderData))
		return
	}
	d.clients = c
}

func (d *postgresCredentialsDataSource) Read(ctx context.Context, req datasource.ReadRequest, resp *datasource.ReadResponse) {
	ctx = sdk.WithTelemetryCommand(ctx, "data.montecarlo_postgres_credentials read")
	var cfg datasource_postgres_credentials.PostgresCredentialsModel
	resp.Diagnostics.Append(req.Config.Get(ctx, &cfg)...)
	if resp.Diagnostics.HasError() {
		return
	}
	out, _, err := d.clients.api.CredentialsAPI.GetPostgresCredentials(ctx, cfg.CredentialsId.ValueString()).Execute()
	if err != nil {
		resp.Diagnostics.AddError("Read postgres_credentials failed", apiErr(err))
		return
	}
	m := datasource_postgres_credentials.PostgresCredentialsModel{
		CredentialsId:  cfg.CredentialsId,
		ConnectionType: types.StringValue(out.GetConnectionType()),
		CreatedTime:    types.StringValue(out.GetCreatedTime().Format(time.RFC3339)),
		DbName:         types.StringValue(out.GetDbName()),
		Host:           types.StringValue(out.GetHost()),
		Id:             types.StringValue(out.GetId()),
		Port:           types.Int64Value(int64(out.GetPort())),
		StorageType:    types.StringValue(string(out.GetStorageType())),
		User:           types.StringValue(out.GetUser()),
	}
	if v, ok := out.GetRdsProxyOk(); ok && v != nil {
		m.RdsProxy = types.BoolValue(*v)
	} else {
		m.RdsProxy = types.BoolNull()
	}
	if v, ok := out.GetSslCaDataOk(); ok && v != nil {
		m.SslCaData = types.StringValue(*v)
	} else {
		m.SslCaData = types.StringNull()
	}
	if v, ok := out.GetSslDisabledOk(); ok && v != nil {
		m.SslDisabled = types.BoolValue(*v)
	} else {
		m.SslDisabled = types.BoolNull()
	}
	if v, ok := out.GetSslSkipCertVerificationOk(); ok && v != nil {
		m.SslSkipCertVerification = types.BoolValue(*v)
	} else {
		m.SslSkipCertVerification = types.BoolNull()
	}
	if v, ok := out.GetSslVerifyCertOk(); ok && v != nil {
		m.SslVerifyCert = types.BoolValue(*v)
	} else {
		m.SslVerifyCert = types.BoolNull()
	}
	if v, ok := out.GetSslVerifyIdentityOk(); ok && v != nil {
		m.SslVerifyIdentity = types.BoolValue(*v)
	} else {
		m.SslVerifyIdentity = types.BoolNull()
	}
	resp.Diagnostics.Append(resp.State.Set(ctx, m)...)
}
