// Code generated by api-codegen; DO NOT EDIT.
package provider

import (
	"context"
	"fmt"

	"github.com/hashicorp/terraform-plugin-framework/datasource"
	"github.com/hashicorp/terraform-plugin-framework/types"
	"time"

	sdk "github.com/monte-carlo-data/mc-sdk-go/montecarlo"
	"github.com/monte-carlo-data/terraform-provider-montecarlo/internal/schema_gen/datasource_power_bi_credentials"
)

var (
	_ datasource.DataSource              = (*powerBiCredentialsDataSource)(nil)
	_ datasource.DataSourceWithConfigure = (*powerBiCredentialsDataSource)(nil)
)

type powerBiCredentialsDataSource struct{ clients *clients }

func NewPowerBiCredentialsDataSource() datasource.DataSource { return &powerBiCredentialsDataSource{} }

func (d *powerBiCredentialsDataSource) Metadata(_ context.Context, req datasource.MetadataRequest, resp *datasource.MetadataResponse) {
	resp.TypeName = req.ProviderTypeName + "_power_bi_credentials"
}

func (d *powerBiCredentialsDataSource) Schema(ctx context.Context, _ datasource.SchemaRequest, resp *datasource.SchemaResponse) {
	resp.Schema = datasource_power_bi_credentials.PowerBiCredentialsDataSourceSchema(ctx)
}

func (d *powerBiCredentialsDataSource) Configure(_ context.Context, req datasource.ConfigureRequest, resp *datasource.ConfigureResponse) {
	if req.ProviderData == nil {
		return
	}
	c, ok := req.ProviderData.(*clients)
	if !ok {
		resp.Diagnostics.AddError("unexpected provider data", fmt.Sprintf("got %T", req.ProviderData))
		return
	}
	d.clients = c
}

func (d *powerBiCredentialsDataSource) Read(ctx context.Context, req datasource.ReadRequest, resp *datasource.ReadResponse) {
	ctx = sdk.WithTelemetryCommand(ctx, "data.montecarlo_power_bi_credentials read")
	var cfg datasource_power_bi_credentials.PowerBiCredentialsModel
	resp.Diagnostics.Append(req.Config.Get(ctx, &cfg)...)
	if resp.Diagnostics.HasError() {
		return
	}
	out, _, err := d.clients.api.CredentialsAPI.GetPowerBiCredentials(ctx, cfg.CredentialsId.ValueString()).Execute()
	if err != nil {
		resp.Diagnostics.AddError("Read power_bi_credentials failed", apiErr(err))
		return
	}
	m := datasource_power_bi_credentials.PowerBiCredentialsModel{
		CredentialsId:  cfg.CredentialsId,
		AppClientId:    types.StringValue(out.GetAppClientId()),
		AuthMode:       types.StringValue(string(out.GetAuthMode())),
		ConnectionType: types.StringValue(out.GetConnectionType()),
		CreatedTime:    types.StringValue(out.GetCreatedTime().Format(time.RFC3339)),
		Id:             types.StringValue(out.GetId()),
		StorageType:    types.StringValue(string(out.GetStorageType())),
		TenantId:       types.StringValue(out.GetTenantId()),
	}
	if v, ok := out.GetUsernameOk(); ok && v != nil {
		m.Username = types.StringValue(*v)
	} else {
		m.Username = types.StringNull()
	}
	resp.Diagnostics.Append(resp.State.Set(ctx, m)...)
}
