// Code generated by api-codegen; DO NOT EDIT.
package provider

import (
	"context"

	"github.com/hashicorp/terraform-plugin-framework/datasource"
	"github.com/hashicorp/terraform-plugin-framework/provider"
	"github.com/hashicorp/terraform-plugin-framework/provider/schema"
	"github.com/hashicorp/terraform-plugin-framework/resource"
	"github.com/hashicorp/terraform-plugin-framework/types"

	sdk "github.com/monte-carlo-data/mc-sdk-go/montecarlo"
)

// clients is handed to every resource and data source through Configure. The client already
// authenticates each request, so there is nothing to attach per call.
type clients struct {
	api *sdk.APIClient
}

type mcProvider struct{}

func New() func() provider.Provider {
	return func() provider.Provider { return &mcProvider{} }
}

func (p *mcProvider) Metadata(_ context.Context, _ provider.MetadataRequest, resp *provider.MetadataResponse) {
	resp.TypeName = "montecarlo"
}

type providerModel struct {
	Endpoint     types.String `tfsdk:"endpoint"`
	TokenID      types.String `tfsdk:"token_id"`
	TokenSecret  types.String `tfsdk:"token_secret"`
	Token        types.String `tfsdk:"token"`
	ClientID     types.String `tfsdk:"client_id"`
	ClientSecret types.String `tfsdk:"client_secret"`
	Instance     types.String `tfsdk:"instance"`
	TokenURL     types.String `tfsdk:"token_url"`
	Profile      types.String `tfsdk:"profile"`
}

func (p *mcProvider) Schema(_ context.Context, _ provider.SchemaRequest, resp *provider.SchemaResponse) {
	resp.Schema = schema.Schema{
		Description: "Manage Monte Carlo with Terraform. Credentials may be set here, taken " +
			"from the environment, or read from a profile written by the Monte Carlo CLI.",
		Attributes: map[string]schema.Attribute{
			"endpoint": schema.StringAttribute{
				Optional: true,
				Description: "API base URL, for example https://api.getmontecarlo.com. Required, " +
					"but may come from the profile's mcd_api_endpoint instead of being set here.",
			},
			"token_id": schema.StringAttribute{
				Optional: true,
				Description: "Monte Carlo API token id. Defaults to MCD_DEFAULT_API_ID, then to " +
					"the profile's mcd_id.",
			},
			"token_secret": schema.StringAttribute{
				Optional:  true,
				Sensitive: true,
				Description: "Monte Carlo API token secret. Defaults to MCD_DEFAULT_API_TOKEN, " +
					"then to the profile's mcd_token.",
			},
			"token": schema.StringAttribute{
				Optional:    true,
				Sensitive:   true,
				Description: "A bearer credential obtained elsewhere, used instead of token_id and token_secret.",
			},
			"client_id": schema.StringAttribute{
				Optional: true,
				Description: "OAuth client id. Defaults to MCD_DEFAULT_OAUTH_CLIENT_ID, then to " +
					"the profile's mcd_oauth_client_id.",
			},
			"client_secret": schema.StringAttribute{
				Optional:  true,
				Sensitive: true,
				Description: "OAuth client secret. Defaults to MCD_DEFAULT_OAUTH_CLIENT_SECRET, " +
					"then to the profile's mcd_oauth_client_secret.",
			},
			"instance": schema.StringAttribute{
				Optional: true,
				Description: "Monte Carlo instance, for example us1. Required with OAuth " +
					"credentials. Defaults to MCD_DEFAULT_INSTANCE_ID, then to the profile's " +
					"mcd_instance_id.",
			},
			"token_url": schema.StringAttribute{
				Optional: true,
				Description: "Where OAuth client credentials are exchanged. Defaults to the " +
					"endpoint with /oauth2/token appended.",
			},
			"profile": schema.StringAttribute{
				Optional: true,
				Description: "A profile in ~/.mcd/profiles.ini, written by the Monte Carlo CLI. " +
					"Defaults to MCD_DEFAULT_PROFILE, then to the profile named default. A " +
					"profile named here must exist.",
			},
		},
	}
}

func (p *mcProvider) Configure(ctx context.Context, req provider.ConfigureRequest, resp *provider.ConfigureResponse) {
	var cfg providerModel
	resp.Diagnostics.Append(req.Config.Get(ctx, &cfg)...)
	if resp.Diagnostics.HasError() {
		return
	}

	// Only what the configuration set is passed on. The SDK resolves the environment variables
	// and the profile.
	api, err := sdk.NewClient(ctx, sdk.Options{
		Endpoint:     cfg.Endpoint.ValueString(),
		TokenID:      cfg.TokenID.ValueString(),
		TokenSecret:  cfg.TokenSecret.ValueString(),
		Token:        cfg.Token.ValueString(),
		ClientID:     cfg.ClientID.ValueString(),
		ClientSecret: cfg.ClientSecret.ValueString(),
		Instance:     cfg.Instance.ValueString(),
		TokenURL:     cfg.TokenURL.ValueString(),
		Profile:      cfg.Profile.ValueString(),
		// The gateway drops User-Agent, so these identify the provider to usage telemetry.
		// Each resource and data source operation adds its own command.
		TelemetryReason:  "terraform",
		TelemetryService: "terraform-provider-montecarlo",
	})
	if err != nil {
		resp.Diagnostics.AddError("Monte Carlo credentials", err.Error())
		return
	}

	resp.ResourceData = &clients{api: api}
	resp.DataSourceData = &clients{api: api}
}

func (p *mcProvider) Resources(_ context.Context) []func() resource.Resource {
	return []func() resource.Resource{
		NewAirflowCredentialsResource,
		NewAwsCollectionAgentResource,
		NewAwsCollectionDataStoreResource,
		NewAzureCollectionAgentResource,
		NewAzureCollectionDataStoreResource,
		NewAzureDataFactoryCredentialsResource,
		NewAzureDedicatedSqlPoolCredentialsResource,
		NewAzureSqlDatabaseCredentialsResource,
		NewBiContainerResource,
		NewBigqueryCredentialsResource,
		NewClickhouseCredentialsResource,
		NewConnectionResource,
		NewDatabricksMetastoreSqlWarehouseCredentialsResource,
		NewDatabricksSqlWarehouseCredentialsResource,
		NewDb2CredentialsResource,
		NewDeploymentResource,
		NewEtlContainerResource,
		NewFivetranCredentialsResource,
		NewGcpCollectionAgentResource,
		NewGcpCollectionDataStoreResource,
		NewGcpDataformCredentialsResource,
		NewGenericCollectionAgentResource,
		NewGenericCollectionAgentOauthClientResource,
		NewGenericCollectionAgentTokenResource,
		NewInformaticaV2CredentialsResource,
		NewLookerCredentialsResource,
		NewLookerGitCloneCredentialsResource,
		NewMariadbCredentialsResource,
		NewMulesoftCredentialsResource,
		NewMysqlCredentialsResource,
		NewOracleCredentialsResource,
		NewPostgresCredentialsResource,
		NewPowerBiCredentialsResource,
		NewRedshiftCredentialsResource,
		NewSapHanaCredentialsResource,
		NewSelfHostedAwsCredentialsResource,
		NewSelfHostedAzureCredentialsResource,
		NewSelfHostedEnvVarCredentialsResource,
		NewSelfHostedFileCredentialsResource,
		NewSelfHostedGcpCredentialsResource,
		NewSnowflakeCredentialsResource,
		NewSqlServerCredentialsResource,
		NewStarburstEnterpriseCredentialsResource,
		NewStarburstGalaxyCredentialsResource,
		NewTableauCredentialsResource,
		NewTeradataCredentialsResource,
		NewWarehouseResource,
	}
}

func (p *mcProvider) DataSources(_ context.Context) []func() datasource.DataSource {
	return []func() datasource.DataSource{
		NewAirflowCredentialsDataSource,
		NewAwsCollectionAgentDataSource,
		NewAwsCollectionDataStoreDataSource,
		NewAzureCollectionAgentDataSource,
		NewAzureCollectionDataStoreDataSource,
		NewAzureDataFactoryCredentialsDataSource,
		NewAzureDedicatedSqlPoolCredentialsDataSource,
		NewAzureSqlDatabaseCredentialsDataSource,
		NewBiContainerDataSource,
		NewBigqueryCredentialsDataSource,
		NewClickhouseCredentialsDataSource,
		NewConnectionDataSource,
		NewDatabricksMetastoreSqlWarehouseCredentialsDataSource,
		NewDatabricksSqlWarehouseCredentialsDataSource,
		NewDb2CredentialsDataSource,
		NewEtlContainerDataSource,
		NewFivetranCredentialsDataSource,
		NewGcpCollectionAgentDataSource,
		NewGcpCollectionDataStoreDataSource,
		NewGcpDataformCredentialsDataSource,
		NewGenericCollectionAgentDataSource,
		NewGenericCollectionAgentOauthClientDataSource,
		NewGenericCollectionAgentTokenDataSource,
		NewInformaticaV2CredentialsDataSource,
		NewLookerCredentialsDataSource,
		NewLookerGitCloneCredentialsDataSource,
		NewMariadbCredentialsDataSource,
		NewMulesoftCredentialsDataSource,
		NewMysqlCredentialsDataSource,
		NewOracleCredentialsDataSource,
		NewPostgresCredentialsDataSource,
		NewPowerBiCredentialsDataSource,
		NewRedshiftCredentialsDataSource,
		NewSapHanaCredentialsDataSource,
		NewSelfHostedAwsCredentialsDataSource,
		NewSelfHostedAzureCredentialsDataSource,
		NewSelfHostedEnvVarCredentialsDataSource,
		NewSelfHostedFileCredentialsDataSource,
		NewSelfHostedGcpCredentialsDataSource,
		NewSnowflakeCredentialsDataSource,
		NewSqlServerCredentialsDataSource,
		NewStarburstEnterpriseCredentialsDataSource,
		NewStarburstGalaxyCredentialsDataSource,
		NewTableauCredentialsDataSource,
		NewTeradataCredentialsDataSource,
		NewWarehouseDataSource,
	}
}
