// Code generated by api-codegen; DO NOT EDIT.
package provider

import (
	"context"
	"fmt"
	"net/http"

	"github.com/hashicorp/terraform-plugin-framework/path"
	"github.com/hashicorp/terraform-plugin-framework/resource"
	"github.com/hashicorp/terraform-plugin-framework/types"
	"time"

	sdk "github.com/monte-carlo-data/mc-sdk-go/montecarlo"
	"github.com/monte-carlo-data/terraform-provider-montecarlo/internal/schema_gen/resource_self_hosted_gcp_credentials"
)

var (
	_ resource.Resource                = (*selfHostedGcpCredentialsResource)(nil)
	_ resource.ResourceWithConfigure   = (*selfHostedGcpCredentialsResource)(nil)
	_ resource.ResourceWithImportState = (*selfHostedGcpCredentialsResource)(nil)
)

type selfHostedGcpCredentialsResource struct{ clients *clients }

func NewSelfHostedGcpCredentialsResource() resource.Resource {
	return &selfHostedGcpCredentialsResource{}
}

func (r *selfHostedGcpCredentialsResource) Metadata(_ context.Context, req resource.MetadataRequest, resp *resource.MetadataResponse) {
	resp.TypeName = req.ProviderTypeName + "_self_hosted_gcp_credentials"
}

func (r *selfHostedGcpCredentialsResource) Schema(ctx context.Context, _ resource.SchemaRequest, resp *resource.SchemaResponse) {
	s := resource_self_hosted_gcp_credentials.SelfHostedGcpCredentialsResourceSchema(ctx)
	// These holds come before the replacements below: plan modifiers run in the order they are attached.
	// Updating the resource never changes these, so the plan keeps what state holds.
	useNonNullStateForUnknown(s.Attributes, "self_hosted_gcp_credentials.connection_type", &resp.Diagnostics)
	useNonNullStateForUnknown(s.Attributes, "self_hosted_gcp_credentials.created_time", &resp.Diagnostics)
	useNonNullStateForUnknown(s.Attributes, "self_hosted_gcp_credentials.id", &resp.Diagnostics)
	useNonNullStateForUnknown(s.Attributes, "self_hosted_gcp_credentials.storage_type", &resp.Diagnostics)
	// The API accepts these on create and not on update, so changing one replaces the resource.
	requiresReplace(s.Attributes, "self_hosted_gcp_credentials.connection_type", &resp.Diagnostics)
	resp.Schema = s
}

func (r *selfHostedGcpCredentialsResource) Configure(_ context.Context, req resource.ConfigureRequest, resp *resource.ConfigureResponse) {
	if req.ProviderData == nil {
		return
	}
	c, ok := req.ProviderData.(*clients)
	if !ok {
		resp.Diagnostics.AddError("unexpected provider data", fmt.Sprintf("got %T", req.ProviderData))
		return
	}
	r.clients = c
}

func (r *selfHostedGcpCredentialsResource) Create(ctx context.Context, req resource.CreateRequest, resp *resource.CreateResponse) {
	var plan resource_self_hosted_gcp_credentials.SelfHostedGcpCredentialsModel
	resp.Diagnostics.Append(req.Plan.Get(ctx, &plan)...)
	if resp.Diagnostics.HasError() {
		return
	}
	body := sdk.NewGcpSecretManagerCredentialsIn(plan.ConnectionType.ValueString(), plan.GcpSecret.ValueString())
	if !plan.BqProjectId.IsNull() && !plan.BqProjectId.IsUnknown() {
		body.SetBqProjectId(plan.BqProjectId.ValueString())
	}
	if !plan.DatabricksWarehouseId.IsNull() && !plan.DatabricksWarehouseId.IsUnknown() {
		body.SetDatabricksWarehouseId(plan.DatabricksWarehouseId.ValueString())
	}
	// Retried: the spec marks this operation x-mc-retry-on-transient.
	out, err := withRetryOnTransient(ctx, func() (*sdk.GcpSecretManagerCredentialsOut, *http.Response, error) {
		return r.clients.api.CredentialsAPI.CreateGcpSecretManagerCredentials(ctx).GcpSecretManagerCredentialsIn(*body).Execute()
	})
	if err != nil {
		resp.Diagnostics.AddError("Create self_hosted_gcp_credentials failed", apiErr(err))
		return
	}
	resp.Diagnostics.Append(resp.State.Set(ctx, selfHostedGcpCredentialsToModel(out))...)
}

func (r *selfHostedGcpCredentialsResource) Read(ctx context.Context, req resource.ReadRequest, resp *resource.ReadResponse) {
	var state resource_self_hosted_gcp_credentials.SelfHostedGcpCredentialsModel
	resp.Diagnostics.Append(req.State.Get(ctx, &state)...)
	if resp.Diagnostics.HasError() {
		return
	}
	out, httpResp, err := r.clients.api.CredentialsAPI.GetGcpSecretManagerCredentials(ctx, state.Id.ValueString()).Execute()
	if err != nil {
		if httpResp != nil && httpResp.StatusCode == 404 {
			resp.State.RemoveResource(ctx)
			return
		}
		resp.Diagnostics.AddError("Read self_hosted_gcp_credentials failed", apiErr(err))
		return
	}
	resp.Diagnostics.Append(resp.State.Set(ctx, selfHostedGcpCredentialsToModel(out))...)
}

func (r *selfHostedGcpCredentialsResource) Update(ctx context.Context, req resource.UpdateRequest, resp *resource.UpdateResponse) {
	var plan, state resource_self_hosted_gcp_credentials.SelfHostedGcpCredentialsModel
	resp.Diagnostics.Append(req.Plan.Get(ctx, &plan)...)
	resp.Diagnostics.Append(req.State.Get(ctx, &state)...)
	if resp.Diagnostics.HasError() {
		return
	}
	body := sdk.NewGcpSecretManagerCredentialsPatch()
	if !plan.BqProjectId.IsNull() && !plan.BqProjectId.IsUnknown() {
		body.SetBqProjectId(plan.BqProjectId.ValueString())
	}
	if !plan.DatabricksWarehouseId.IsNull() && !plan.DatabricksWarehouseId.IsUnknown() {
		body.SetDatabricksWarehouseId(plan.DatabricksWarehouseId.ValueString())
	}
	if !plan.GcpSecret.IsNull() && !plan.GcpSecret.IsUnknown() {
		body.SetGcpSecret(plan.GcpSecret.ValueString())
	}
	// Retried: the spec marks this operation x-mc-retry-on-transient.
	out, err := withRetryOnTransient(ctx, func() (*sdk.GcpSecretManagerCredentialsOut, *http.Response, error) {
		return r.clients.api.CredentialsAPI.UpdateGcpSecretManagerCredentials(ctx, state.Id.ValueString()).GcpSecretManagerCredentialsPatch(*body).Execute()
	})
	if err != nil {
		resp.Diagnostics.AddError("Update self_hosted_gcp_credentials failed", apiErr(err))
		return
	}
	resp.Diagnostics.Append(resp.State.Set(ctx, selfHostedGcpCredentialsToModel(out))...)
}

func (r *selfHostedGcpCredentialsResource) Delete(ctx context.Context, req resource.DeleteRequest, resp *resource.DeleteResponse) {
	var state resource_self_hosted_gcp_credentials.SelfHostedGcpCredentialsModel
	resp.Diagnostics.Append(req.State.Get(ctx, &state)...)
	if resp.Diagnostics.HasError() {
		return
	}
	if _, err := r.clients.api.CredentialsAPI.DeleteGcpSecretManagerCredentials(ctx, state.Id.ValueString()).Execute(); err != nil {
		resp.Diagnostics.AddError("Delete self_hosted_gcp_credentials failed", apiErr(err))
	}
}

func (r *selfHostedGcpCredentialsResource) ImportState(ctx context.Context, req resource.ImportStateRequest, resp *resource.ImportStateResponse) {
	resource.ImportStatePassthroughID(ctx, path.Root("id"), req, resp)
}

func selfHostedGcpCredentialsToModel(o *sdk.GcpSecretManagerCredentialsOut) resource_self_hosted_gcp_credentials.SelfHostedGcpCredentialsModel {
	m := resource_self_hosted_gcp_credentials.SelfHostedGcpCredentialsModel{
		ConnectionType: types.StringValue(o.GetConnectionType()),
		CreatedTime:    types.StringValue(o.GetCreatedTime().Format(time.RFC3339)),
		GcpSecret:      types.StringValue(o.GetGcpSecret()),
		Id:             types.StringValue(o.GetId()),
		StorageType:    types.StringValue(string(o.GetStorageType())),
	}
	if v, ok := o.GetBqProjectIdOk(); ok && v != nil {
		m.BqProjectId = types.StringValue(*v)
	} else {
		m.BqProjectId = types.StringNull()
	}
	if v, ok := o.GetDatabricksWarehouseIdOk(); ok && v != nil {
		m.DatabricksWarehouseId = types.StringValue(*v)
	} else {
		m.DatabricksWarehouseId = types.StringNull()
	}
	return m
}
