// Code generated by api-codegen; DO NOT EDIT.
package provider

import (
	"context"
	"fmt"

	"github.com/hashicorp/terraform-plugin-framework/datasource"
	"github.com/hashicorp/terraform-plugin-framework/types"
	"time"

	sdk "github.com/monte-carlo-data/mc-sdk-go/montecarlo"
	"github.com/monte-carlo-data/terraform-provider-montecarlo/internal/schema_gen/datasource_self_hosted_env_var_credentials"
)

var (
	_ datasource.DataSource              = (*selfHostedEnvVarCredentialsDataSource)(nil)
	_ datasource.DataSourceWithConfigure = (*selfHostedEnvVarCredentialsDataSource)(nil)
)

type selfHostedEnvVarCredentialsDataSource struct{ clients *clients }

func NewSelfHostedEnvVarCredentialsDataSource() datasource.DataSource {
	return &selfHostedEnvVarCredentialsDataSource{}
}

func (d *selfHostedEnvVarCredentialsDataSource) Metadata(_ context.Context, req datasource.MetadataRequest, resp *datasource.MetadataResponse) {
	resp.TypeName = req.ProviderTypeName + "_self_hosted_env_var_credentials"
}

func (d *selfHostedEnvVarCredentialsDataSource) Schema(ctx context.Context, _ datasource.SchemaRequest, resp *datasource.SchemaResponse) {
	resp.Schema = datasource_self_hosted_env_var_credentials.SelfHostedEnvVarCredentialsDataSourceSchema(ctx)
}

func (d *selfHostedEnvVarCredentialsDataSource) Configure(_ context.Context, req datasource.ConfigureRequest, resp *datasource.ConfigureResponse) {
	if req.ProviderData == nil {
		return
	}
	c, ok := req.ProviderData.(*clients)
	if !ok {
		resp.Diagnostics.AddError("unexpected provider data", fmt.Sprintf("got %T", req.ProviderData))
		return
	}
	d.clients = c
}

func (d *selfHostedEnvVarCredentialsDataSource) Read(ctx context.Context, req datasource.ReadRequest, resp *datasource.ReadResponse) {
	ctx = sdk.WithTelemetryCommand(ctx, "data.montecarlo_self_hosted_env_var_credentials read")
	var cfg datasource_self_hosted_env_var_credentials.SelfHostedEnvVarCredentialsModel
	resp.Diagnostics.Append(req.Config.Get(ctx, &cfg)...)
	if resp.Diagnostics.HasError() {
		return
	}
	out, _, err := d.clients.api.CredentialsAPI.GetEnvVarCredentials(ctx, cfg.CredentialsId.ValueString()).Execute()
	if err != nil {
		resp.Diagnostics.AddError("Read self_hosted_env_var_credentials failed", apiErr(err))
		return
	}
	m := datasource_self_hosted_env_var_credentials.SelfHostedEnvVarCredentialsModel{
		CredentialsId:  cfg.CredentialsId,
		ConnectionType: types.StringValue(out.GetConnectionType()),
		CreatedTime:    types.StringValue(out.GetCreatedTime().Format(time.RFC3339)),
		EnvVarName:     types.StringValue(out.GetEnvVarName()),
		Id:             types.StringValue(out.GetId()),
		StorageType:    types.StringValue(string(out.GetStorageType())),
	}
	if v, ok := out.GetBqProjectIdOk(); ok && v != nil {
		m.BqProjectId = types.StringValue(*v)
	} else {
		m.BqProjectId = types.StringNull()
	}
	if v, ok := out.GetDatabricksWarehouseIdOk(); ok && v != nil {
		m.DatabricksWarehouseId = types.StringValue(*v)
	} else {
		m.DatabricksWarehouseId = types.StringNull()
	}
	if v, ok := out.GetKmsKeyIdOk(); ok && v != nil {
		m.KmsKeyId = types.StringValue(*v)
	} else {
		m.KmsKeyId = types.StringNull()
	}
	resp.Diagnostics.Append(resp.State.Set(ctx, m)...)
}
