// Code generated by api-codegen; DO NOT EDIT.
package provider

import (
	"context"
	"fmt"
	"net/http"

	"github.com/hashicorp/terraform-plugin-framework/path"
	"github.com/hashicorp/terraform-plugin-framework/resource"
	"github.com/hashicorp/terraform-plugin-framework/types"
	"time"

	sdk "github.com/monte-carlo-data/mc-sdk-go/montecarlo"
	"github.com/monte-carlo-data/terraform-provider-montecarlo/internal/schema_gen/resource_self_hosted_env_var_credentials"
)

var (
	_ resource.Resource                = (*selfHostedEnvVarCredentialsResource)(nil)
	_ resource.ResourceWithConfigure   = (*selfHostedEnvVarCredentialsResource)(nil)
	_ resource.ResourceWithImportState = (*selfHostedEnvVarCredentialsResource)(nil)
)

type selfHostedEnvVarCredentialsResource struct{ clients *clients }

func NewSelfHostedEnvVarCredentialsResource() resource.Resource {
	return &selfHostedEnvVarCredentialsResource{}
}

func (r *selfHostedEnvVarCredentialsResource) Metadata(_ context.Context, req resource.MetadataRequest, resp *resource.MetadataResponse) {
	resp.TypeName = req.ProviderTypeName + "_self_hosted_env_var_credentials"
}

func (r *selfHostedEnvVarCredentialsResource) Schema(ctx context.Context, _ resource.SchemaRequest, resp *resource.SchemaResponse) {
	s := resource_self_hosted_env_var_credentials.SelfHostedEnvVarCredentialsResourceSchema(ctx)
	// These holds come before the replacements below: plan modifiers run in the order they are attached.
	// Updating the resource never changes these, and a null in state is final. Only the plain modifier copies a null.
	useStateForUnknown(s.Attributes, "self_hosted_env_var_credentials.connection_type", &resp.Diagnostics)
	useStateForUnknown(s.Attributes, "self_hosted_env_var_credentials.created_time", &resp.Diagnostics)
	useStateForUnknown(s.Attributes, "self_hosted_env_var_credentials.id", &resp.Diagnostics)
	useStateForUnknown(s.Attributes, "self_hosted_env_var_credentials.storage_type", &resp.Diagnostics)
	// The API accepts these on create and not on update, so changing one replaces the resource.
	requiresReplace(s.Attributes, "self_hosted_env_var_credentials.connection_type", &resp.Diagnostics)
	resp.Schema = s
}

func (r *selfHostedEnvVarCredentialsResource) Configure(_ context.Context, req resource.ConfigureRequest, resp *resource.ConfigureResponse) {
	if req.ProviderData == nil {
		return
	}
	c, ok := req.ProviderData.(*clients)
	if !ok {
		resp.Diagnostics.AddError("unexpected provider data", fmt.Sprintf("got %T", req.ProviderData))
		return
	}
	r.clients = c
}

func (r *selfHostedEnvVarCredentialsResource) Create(ctx context.Context, req resource.CreateRequest, resp *resource.CreateResponse) {
	ctx = sdk.WithTelemetryCommand(ctx, "montecarlo_self_hosted_env_var_credentials create")
	var plan resource_self_hosted_env_var_credentials.SelfHostedEnvVarCredentialsModel
	resp.Diagnostics.Append(req.Plan.Get(ctx, &plan)...)
	if resp.Diagnostics.HasError() {
		return
	}
	body := sdk.NewEnvVarCredentialsIn(plan.ConnectionType.ValueString(), plan.EnvVarName.ValueString())
	if !plan.BqProjectId.IsNull() && !plan.BqProjectId.IsUnknown() {
		body.SetBqProjectId(plan.BqProjectId.ValueString())
	}
	if !plan.KmsKeyId.IsNull() && !plan.KmsKeyId.IsUnknown() {
		body.SetKmsKeyId(plan.KmsKeyId.ValueString())
	}
	if !plan.SqlWarehouseId.IsNull() && !plan.SqlWarehouseId.IsUnknown() {
		body.SetSqlWarehouseId(plan.SqlWarehouseId.ValueString())
	}
	// Retried: the spec marks this operation x-mc-retry-on-transient.
	out, err := withRetryOnTransient(ctx, func() (*sdk.EnvVarCredentialsOut, *http.Response, error) {
		return r.clients.api.CredentialsAPI.CreateEnvVarCredentials(ctx).EnvVarCredentialsIn(*body).Execute()
	})
	if err != nil {
		resp.Diagnostics.AddError("Create self_hosted_env_var_credentials failed", apiErr(err))
		return
	}
	resp.Diagnostics.Append(resp.State.Set(ctx, selfHostedEnvVarCredentialsToModel(out))...)
}

func (r *selfHostedEnvVarCredentialsResource) Read(ctx context.Context, req resource.ReadRequest, resp *resource.ReadResponse) {
	ctx = sdk.WithTelemetryCommand(ctx, "montecarlo_self_hosted_env_var_credentials read")
	var state resource_self_hosted_env_var_credentials.SelfHostedEnvVarCredentialsModel
	resp.Diagnostics.Append(req.State.Get(ctx, &state)...)
	if resp.Diagnostics.HasError() {
		return
	}
	out, httpResp, err := r.clients.api.CredentialsAPI.GetEnvVarCredentials(ctx, state.Id.ValueString()).Execute()
	if err != nil {
		if httpResp != nil && httpResp.StatusCode == 404 {
			resp.State.RemoveResource(ctx)
			return
		}
		resp.Diagnostics.AddError("Read self_hosted_env_var_credentials failed", apiErr(err))
		return
	}
	resp.Diagnostics.Append(resp.State.Set(ctx, selfHostedEnvVarCredentialsToModel(out))...)
}

func (r *selfHostedEnvVarCredentialsResource) Update(ctx context.Context, req resource.UpdateRequest, resp *resource.UpdateResponse) {
	ctx = sdk.WithTelemetryCommand(ctx, "montecarlo_self_hosted_env_var_credentials update")
	var plan, state resource_self_hosted_env_var_credentials.SelfHostedEnvVarCredentialsModel
	resp.Diagnostics.Append(req.Plan.Get(ctx, &plan)...)
	resp.Diagnostics.Append(req.State.Get(ctx, &state)...)
	if resp.Diagnostics.HasError() {
		return
	}
	body := sdk.NewEnvVarCredentialsPatch()
	if !plan.BqProjectId.IsNull() && !plan.BqProjectId.IsUnknown() {
		body.SetBqProjectId(plan.BqProjectId.ValueString())
	}
	if !plan.EnvVarName.IsNull() && !plan.EnvVarName.IsUnknown() {
		body.SetEnvVarName(plan.EnvVarName.ValueString())
	}
	if !plan.KmsKeyId.IsNull() && !plan.KmsKeyId.IsUnknown() {
		body.SetKmsKeyId(plan.KmsKeyId.ValueString())
	}
	if !plan.SqlWarehouseId.IsNull() && !plan.SqlWarehouseId.IsUnknown() {
		body.SetSqlWarehouseId(plan.SqlWarehouseId.ValueString())
	}
	// Retried: the spec marks this operation x-mc-retry-on-transient.
	out, err := withRetryOnTransient(ctx, func() (*sdk.EnvVarCredentialsOut, *http.Response, error) {
		return r.clients.api.CredentialsAPI.UpdateEnvVarCredentials(ctx, state.Id.ValueString()).EnvVarCredentialsPatch(*body).Execute()
	})
	if err != nil {
		resp.Diagnostics.AddError("Update self_hosted_env_var_credentials failed", apiErr(err))
		return
	}
	resp.Diagnostics.Append(resp.State.Set(ctx, selfHostedEnvVarCredentialsToModel(out))...)
}

func (r *selfHostedEnvVarCredentialsResource) Delete(ctx context.Context, req resource.DeleteRequest, resp *resource.DeleteResponse) {
	ctx = sdk.WithTelemetryCommand(ctx, "montecarlo_self_hosted_env_var_credentials delete")
	var state resource_self_hosted_env_var_credentials.SelfHostedEnvVarCredentialsModel
	resp.Diagnostics.Append(req.State.Get(ctx, &state)...)
	if resp.Diagnostics.HasError() {
		return
	}
	if _, err := r.clients.api.CredentialsAPI.DeleteEnvVarCredentials(ctx, state.Id.ValueString()).Execute(); err != nil {
		resp.Diagnostics.AddError("Delete self_hosted_env_var_credentials failed", apiErr(err))
	}
}

func (r *selfHostedEnvVarCredentialsResource) ImportState(ctx context.Context, req resource.ImportStateRequest, resp *resource.ImportStateResponse) {
	resource.ImportStatePassthroughID(ctx, path.Root("id"), req, resp)
}

func selfHostedEnvVarCredentialsToModel(o *sdk.EnvVarCredentialsOut) resource_self_hosted_env_var_credentials.SelfHostedEnvVarCredentialsModel {
	m := resource_self_hosted_env_var_credentials.SelfHostedEnvVarCredentialsModel{
		ConnectionType: types.StringValue(o.GetConnectionType()),
		CreatedTime:    types.StringValue(o.GetCreatedTime().Format(time.RFC3339)),
		EnvVarName:     types.StringValue(o.GetEnvVarName()),
		Id:             types.StringValue(o.GetId()),
		StorageType:    types.StringValue(string(o.GetStorageType())),
	}
	if v, ok := o.GetBqProjectIdOk(); ok && v != nil {
		m.BqProjectId = types.StringValue(*v)
	} else {
		m.BqProjectId = types.StringNull()
	}
	if v, ok := o.GetKmsKeyIdOk(); ok && v != nil {
		m.KmsKeyId = types.StringValue(*v)
	} else {
		m.KmsKeyId = types.StringNull()
	}
	if v, ok := o.GetSqlWarehouseIdOk(); ok && v != nil {
		m.SqlWarehouseId = types.StringValue(*v)
	} else {
		m.SqlWarehouseId = types.StringNull()
	}
	return m
}
