// Code generated by api-codegen; DO NOT EDIT.
package provider

import (
	"context"
	"fmt"
	"net/http"

	"github.com/hashicorp/terraform-plugin-framework/path"
	"github.com/hashicorp/terraform-plugin-framework/resource"
	"github.com/hashicorp/terraform-plugin-framework/types"
	"time"

	sdk "github.com/monte-carlo-data/mc-sdk-go/montecarlo"
	"github.com/monte-carlo-data/terraform-provider-montecarlo/internal/schema_gen/resource_warehouse"
)

var (
	_ resource.Resource                = (*warehouseResource)(nil)
	_ resource.ResourceWithConfigure   = (*warehouseResource)(nil)
	_ resource.ResourceWithImportState = (*warehouseResource)(nil)
)

type warehouseResource struct{ clients *clients }

func NewWarehouseResource() resource.Resource { return &warehouseResource{} }

func (r *warehouseResource) Metadata(_ context.Context, req resource.MetadataRequest, resp *resource.MetadataResponse) {
	resp.TypeName = req.ProviderTypeName + "_warehouse"
}

func (r *warehouseResource) Schema(ctx context.Context, _ resource.SchemaRequest, resp *resource.SchemaResponse) {
	s := resource_warehouse.WarehouseResourceSchema(ctx)
	// These holds come before the replacements below: plan modifiers run in the order they are attached.
	// Updating the resource never changes these, so the plan keeps what state holds.
	useNonNullStateForUnknown(s.Attributes, "warehouse.created_time", &resp.Diagnostics)
	useNonNullStateForUnknown(s.Attributes, "warehouse.deployment_id", &resp.Diagnostics)
	useNonNullStateForUnknown(s.Attributes, "warehouse.id", &resp.Diagnostics)
	useNonNullStateForUnknown(s.Attributes, "warehouse.type", &resp.Diagnostics)
	// No response carries these, so state holds null. Only the plain modifier copies a null.
	useStateForUnknown(s.Attributes, "warehouse.connection_type", &resp.Diagnostics)
	// The API accepts these on create and not on update, so changing one replaces the resource.
	requiresReplace(s.Attributes, "warehouse.connection_type", &resp.Diagnostics)
	requiresReplace(s.Attributes, "warehouse.deployment_id", &resp.Diagnostics)
	requiresReplace(s.Attributes, "warehouse.type", &resp.Diagnostics)
	resp.Schema = s
}

func (r *warehouseResource) Configure(_ context.Context, req resource.ConfigureRequest, resp *resource.ConfigureResponse) {
	if req.ProviderData == nil {
		return
	}
	c, ok := req.ProviderData.(*clients)
	if !ok {
		resp.Diagnostics.AddError("unexpected provider data", fmt.Sprintf("got %T", req.ProviderData))
		return
	}
	r.clients = c
}

func (r *warehouseResource) Create(ctx context.Context, req resource.CreateRequest, resp *resource.CreateResponse) {
	ctx = sdk.WithTelemetryCommand(ctx, "montecarlo_warehouse create")
	var plan resource_warehouse.WarehouseModel
	resp.Diagnostics.Append(req.Plan.Get(ctx, &plan)...)
	if resp.Diagnostics.HasError() {
		return
	}
	body := sdk.NewWarehouseIn(plan.Name.ValueString(), plan.DeploymentId.ValueString())
	if !plan.ConnectionType.IsNull() && !plan.ConnectionType.IsUnknown() {
		body.SetConnectionType(plan.ConnectionType.ValueString())
	}
	if !plan.Type.IsNull() && !plan.Type.IsUnknown() {
		body.SetType(sdk.WarehouseType(plan.Type.ValueString()))
	}
	// Retried: the spec marks this operation x-mc-retry-on-transient.
	out, err := withRetryOnTransient(ctx, func() (*sdk.WarehouseOut, *http.Response, error) {
		return r.clients.api.WarehousesAPI.CreateWarehouse(ctx).WarehouseIn(*body).Execute()
	})
	if err != nil {
		resp.Diagnostics.AddError("Create warehouse failed", apiErr(err))
		return
	}
	resp.Diagnostics.Append(resp.State.Set(ctx, warehouseToModel(out, plan.ConnectionType))...)
}

func (r *warehouseResource) Read(ctx context.Context, req resource.ReadRequest, resp *resource.ReadResponse) {
	ctx = sdk.WithTelemetryCommand(ctx, "montecarlo_warehouse read")
	var state resource_warehouse.WarehouseModel
	resp.Diagnostics.Append(req.State.Get(ctx, &state)...)
	if resp.Diagnostics.HasError() {
		return
	}
	out, httpResp, err := r.clients.api.WarehousesAPI.GetWarehouse(ctx, state.Id.ValueString()).Execute()
	if err != nil {
		if httpResp != nil && httpResp.StatusCode == 404 {
			resp.State.RemoveResource(ctx)
			return
		}
		resp.Diagnostics.AddError("Read warehouse failed", apiErr(err))
		return
	}
	resp.Diagnostics.Append(resp.State.Set(ctx, warehouseToModel(out, state.ConnectionType))...)
}

func (r *warehouseResource) Update(ctx context.Context, req resource.UpdateRequest, resp *resource.UpdateResponse) {
	ctx = sdk.WithTelemetryCommand(ctx, "montecarlo_warehouse update")
	var plan, state resource_warehouse.WarehouseModel
	resp.Diagnostics.Append(req.Plan.Get(ctx, &plan)...)
	resp.Diagnostics.Append(req.State.Get(ctx, &state)...)
	if resp.Diagnostics.HasError() {
		return
	}
	body := sdk.NewWarehousePatch()
	if !plan.Name.IsNull() && !plan.Name.IsUnknown() {
		body.SetName(plan.Name.ValueString())
	}
	// Retried: the spec marks this operation x-mc-retry-on-transient.
	out, err := withRetryOnTransient(ctx, func() (*sdk.WarehouseOut, *http.Response, error) {
		return r.clients.api.WarehousesAPI.UpdateWarehouse(ctx, state.Id.ValueString()).WarehousePatch(*body).Execute()
	})
	if err != nil {
		resp.Diagnostics.AddError("Update warehouse failed", apiErr(err))
		return
	}
	resp.Diagnostics.Append(resp.State.Set(ctx, warehouseToModel(out, plan.ConnectionType))...)
}

func (r *warehouseResource) Delete(ctx context.Context, req resource.DeleteRequest, resp *resource.DeleteResponse) {
	ctx = sdk.WithTelemetryCommand(ctx, "montecarlo_warehouse delete")
	var state resource_warehouse.WarehouseModel
	resp.Diagnostics.Append(req.State.Get(ctx, &state)...)
	if resp.Diagnostics.HasError() {
		return
	}
	if _, err := r.clients.api.WarehousesAPI.DeleteWarehouse(ctx, state.Id.ValueString()).Execute(); err != nil {
		resp.Diagnostics.AddError("Delete warehouse failed", apiErr(err))
	}
}

func (r *warehouseResource) ImportState(ctx context.Context, req resource.ImportStateRequest, resp *resource.ImportStateResponse) {
	resource.ImportStatePassthroughID(ctx, path.Root("id"), req, resp)
}

func warehouseToModel(o *sdk.WarehouseOut, connection_type types.String) resource_warehouse.WarehouseModel {
	m := resource_warehouse.WarehouseModel{
		CreatedTime:    types.StringValue(o.GetCreatedTime().Format(time.RFC3339)),
		Id:             types.StringValue(o.GetId()),
		Type:           types.StringValue(string(o.GetType())),
		ConnectionType: connection_type,
	}
	if v, ok := o.GetDeploymentIdOk(); ok && v != nil {
		m.DeploymentId = types.StringValue(*v)
	} else {
		m.DeploymentId = types.StringNull()
	}
	if v, ok := o.GetNameOk(); ok && v != nil {
		m.Name = types.StringValue(*v)
	} else {
		m.Name = types.StringNull()
	}
	// An unreturned field the config omits arrives unknown and no response fills it, so it
	// resolves to null. Terraform rejects an unknown after apply.
	if connection_type.IsUnknown() {
		m.ConnectionType = types.StringNull()
	}
	return m
}
