// Code generated by terraform-plugin-framework-generator DO NOT EDIT.

package resource_looker_git_clone_credentials

import (
	"context"
	"github.com/hashicorp/terraform-plugin-framework-validators/int64validator"
	"github.com/hashicorp/terraform-plugin-framework-validators/stringvalidator"
	"github.com/hashicorp/terraform-plugin-framework/path"
	"github.com/hashicorp/terraform-plugin-framework/schema/validator"
	"github.com/hashicorp/terraform-plugin-framework/types"

	"github.com/hashicorp/terraform-plugin-framework/resource/schema"
)

func LookerGitCloneCredentialsResourceSchema(ctx context.Context) schema.Schema {
	return schema.Schema{
		Attributes: map[string]schema.Attribute{
			"connection_type": schema.StringAttribute{
				Computed:            true,
				Description:         "The connection type the credentials are for, such as `snowflake`. Fixed once created.",
				MarkdownDescription: "The connection type the credentials are for, such as `snowflake`. Fixed once created.",
			},
			"created_time": schema.StringAttribute{
				Computed:            true,
				Description:         "When the credentials were created.",
				MarkdownDescription: "When the credentials were created.",
			},
			"id": schema.StringAttribute{
				Computed:            true,
				Description:         "Unique identifier of the credentials.",
				MarkdownDescription: "Unique identifier of the credentials.",
			},
			"repo_url": schema.StringAttribute{
				Required:            true,
				Description:         "Clone URL of the LookML repository, over HTTPS or SSH.",
				MarkdownDescription: "Clone URL of the LookML repository, over HTTPS or SSH.",
				Validators: []validator.String{
					stringvalidator.LengthBetween(1, 2048),
				},
			},
			"ssh_key_wo": schema.StringAttribute{
				Optional:            true,
				Sensitive:           true,
				Description:         "Private key for an SSH clone, as PEM text including its BEGIN and END lines. Send this or `username` and `token`. Stored by Monte Carlo and never returned.",
				MarkdownDescription: "Private key for an SSH clone, as PEM text including its BEGIN and END lines. Send this or `username` and `token`. Stored by Monte Carlo and never returned.",
				Validators: []validator.String{
					stringvalidator.LengthBetween(1, 32768),
					stringvalidator.AlsoRequires(path.MatchRelative().AtParent().AtName("ssh_key_wo_version")),
				},
			},
			"ssh_key_wo_version": schema.Int64Attribute{
				Optional:            true,
				Description:         "Bump to send `ssh_key_wo` again. Terraform stores this, never the secret.",
				MarkdownDescription: "Bump to send `ssh_key_wo` again. Terraform stores this, never the secret.",
				Validators: []validator.Int64{
					int64validator.AlsoRequires(path.MatchRelative().AtParent().AtName("ssh_key_wo")),
				},
			},
			"ssl_ca_data": schema.StringAttribute{
				Optional:            true,
				Computed:            true,
				Description:         "PEM certificate of the CA that signed the git server's certificate.",
				MarkdownDescription: "PEM certificate of the CA that signed the git server's certificate.",
				Validators: []validator.String{
					stringvalidator.LengthBetween(1, 65536),
				},
			},
			"ssl_skip_cert_verification": schema.BoolAttribute{
				Optional:            true,
				Computed:            true,
				Description:         "Skip verifying the git server's TLS certificate.",
				MarkdownDescription: "Skip verifying the git server's TLS certificate.",
			},
			"storage_type": schema.StringAttribute{
				Computed:            true,
				Description:         "Where the secret lives. Fixed once created.",
				MarkdownDescription: "Where the secret lives. Fixed once created.",
			},
			"token_wo": schema.StringAttribute{
				Optional:            true,
				Sensitive:           true,
				Description:         "Access token of `username`, for an HTTPS clone. Send this or `ssh_key`. Stored by Monte Carlo and never returned.",
				MarkdownDescription: "Access token of `username`, for an HTTPS clone. Send this or `ssh_key`. Stored by Monte Carlo and never returned.",
				Validators: []validator.String{
					stringvalidator.LengthBetween(1, 1024),
					stringvalidator.AlsoRequires(path.MatchRelative().AtParent().AtName("token_wo_version")),
				},
			},
			"token_wo_version": schema.Int64Attribute{
				Optional:            true,
				Description:         "Bump to send `token_wo` again. Terraform stores this, never the secret.",
				MarkdownDescription: "Bump to send `token_wo` again. Terraform stores this, never the secret.",
				Validators: []validator.Int64{
					int64validator.AlsoRequires(path.MatchRelative().AtParent().AtName("token_wo")),
				},
			},
			"username": schema.StringAttribute{
				Optional:            true,
				Computed:            true,
				Description:         "Git user for an HTTPS clone. Send it with `token`.",
				MarkdownDescription: "Git user for an HTTPS clone. Send it with `token`.",
				Validators: []validator.String{
					stringvalidator.LengthBetween(1, 200),
				},
			},
		},
	}
}

type LookerGitCloneCredentialsModel struct {
	ConnectionType          types.String `tfsdk:"connection_type"`
	CreatedTime             types.String `tfsdk:"created_time"`
	Id                      types.String `tfsdk:"id"`
	RepoUrl                 types.String `tfsdk:"repo_url"`
	SshKeyWo                types.String `tfsdk:"ssh_key_wo"`
	SshKeyWoVersion         types.Int64  `tfsdk:"ssh_key_wo_version"`
	SslCaData               types.String `tfsdk:"ssl_ca_data"`
	SslSkipCertVerification types.Bool   `tfsdk:"ssl_skip_cert_verification"`
	StorageType             types.String `tfsdk:"storage_type"`
	TokenWo                 types.String `tfsdk:"token_wo"`
	TokenWoVersion          types.Int64  `tfsdk:"token_wo_version"`
	Username                types.String `tfsdk:"username"`
}
