// Code generated by terraform-plugin-framework-generator DO NOT EDIT.

package resource_self_hosted_file_credentials

import (
	"context"
	"github.com/hashicorp/terraform-plugin-framework-validators/stringvalidator"
	"github.com/hashicorp/terraform-plugin-framework/schema/validator"
	"github.com/hashicorp/terraform-plugin-framework/types"

	"github.com/hashicorp/terraform-plugin-framework/resource/schema"
)

func SelfHostedFileCredentialsResourceSchema(ctx context.Context) schema.Schema {
	return schema.Schema{
		Attributes: map[string]schema.Attribute{
			"bq_project_id": schema.StringAttribute{
				Optional:            true,
				Computed:            true,
				Description:         "BigQuery project the connection reads from. Only for a BigQuery connection.",
				MarkdownDescription: "BigQuery project the connection reads from. Only for a BigQuery connection.",
				Validators: []validator.String{
					stringvalidator.LengthBetween(1, 200),
				},
			},
			"connection_type": schema.StringAttribute{
				Required:            true,
				Description:         "The connection type the credentials are for, such as `snowflake` or `bigquery`, or one of your custom connector types. Fixed once created.",
				MarkdownDescription: "The connection type the credentials are for, such as `snowflake` or `bigquery`, or one of your custom connector types. Fixed once created.",
				Validators: []validator.String{
					stringvalidator.LengthBetween(1, 200),
				},
			},
			"created_time": schema.StringAttribute{
				Computed:            true,
				Description:         "When the credentials were created.",
				MarkdownDescription: "When the credentials were created.",
			},
			"file_path": schema.StringAttribute{
				Required:            true,
				Description:         "Path of the file on the deployment that holds the connection's credentials.",
				MarkdownDescription: "Path of the file on the deployment that holds the connection's credentials.",
				Validators: []validator.String{
					stringvalidator.LengthBetween(1, 1024),
				},
			},
			"id": schema.StringAttribute{
				Computed:            true,
				Description:         "Unique identifier of the credentials.",
				MarkdownDescription: "Unique identifier of the credentials.",
			},
			"sql_warehouse_id": schema.StringAttribute{
				Optional:            true,
				Computed:            true,
				Description:         "Databricks SQL warehouse the connection runs queries on. Required for a `databricks-sql-warehouse` or `databricks-metastore-sql-warehouse` connection.",
				MarkdownDescription: "Databricks SQL warehouse the connection runs queries on. Required for a `databricks-sql-warehouse` or `databricks-metastore-sql-warehouse` connection.",
				Validators: []validator.String{
					stringvalidator.LengthBetween(1, 200),
				},
			},
			"storage_type": schema.StringAttribute{
				Computed:            true,
				Description:         "Where the secret lives. Fixed once created.",
				MarkdownDescription: "Where the secret lives. Fixed once created.",
			},
		},
	}
}

type SelfHostedFileCredentialsModel struct {
	BqProjectId    types.String `tfsdk:"bq_project_id"`
	ConnectionType types.String `tfsdk:"connection_type"`
	CreatedTime    types.String `tfsdk:"created_time"`
	FilePath       types.String `tfsdk:"file_path"`
	Id             types.String `tfsdk:"id"`
	SqlWarehouseId types.String `tfsdk:"sql_warehouse_id"`
	StorageType    types.String `tfsdk:"storage_type"`
}
