// Code generated by terraform-plugin-framework-generator DO NOT EDIT.

package datasource_gcp_collection_data_store

import (
	"context"
	"github.com/hashicorp/terraform-plugin-framework/types"

	"github.com/hashicorp/terraform-plugin-framework/datasource/schema"
)

func GcpCollectionDataStoreDataSourceSchema(ctx context.Context) schema.Schema {
	return schema.Schema{
		Attributes: map[string]schema.Attribute{
			"authentication_type": schema.StringAttribute{
				Computed:            true,
				Description:         "How Monte Carlo authenticates when it reaches the data store.",
				MarkdownDescription: "How Monte Carlo authenticates when it reaches the data store.",
			},
			"bucket_name": schema.StringAttribute{
				Computed:            true,
				Description:         "Name of the Cloud Storage bucket Monte Carlo uses. Empty until it has been registered.",
				MarkdownDescription: "Name of the Cloud Storage bucket Monte Carlo uses. Empty until it has been registered.",
			},
			"collection_data_store_id": schema.StringAttribute{
				Required: true,
			},
			"created_time": schema.StringAttribute{
				Computed:            true,
				Description:         "When the data store was created, which is when its deployment was provisioned.",
				MarkdownDescription: "When the data store was created, which is when its deployment was provisioned.",
			},
			"deployment_id": schema.StringAttribute{
				Computed:            true,
				Description:         "Identifier of the deployment this data store belongs to.",
				MarkdownDescription: "Identifier of the deployment this data store belongs to.",
			},
			"enabled": schema.BoolAttribute{
				Computed:            true,
				Description:         "Whether Monte Carlo is using this data store. One that is unregistered, or whose validation failed, is not enabled.",
				MarkdownDescription: "Whether Monte Carlo is using this data store. One that is unregistered, or whose validation failed, is not enabled.",
			},
			"id": schema.StringAttribute{
				Computed:            true,
				Description:         "Unique identifier of the data store.",
				MarkdownDescription: "Unique identifier of the data store.",
			},
			"last_updated_time": schema.StringAttribute{
				Computed:            true,
				Description:         "When the data store was last registered, renamed, or given different storage or credentials. Null until one of those has happened.",
				MarkdownDescription: "When the data store was last registered, renamed, or given different storage or credentials. Null until one of those has happened.",
			},
			"name": schema.StringAttribute{
				Computed:            true,
				Description:         "Display name of the data store. Null when it has no name.",
				MarkdownDescription: "Display name of the data store. Null when it has no name.",
			},
			"storage_type": schema.StringAttribute{
				Computed:            true,
				Description:         "Which kind of storage the data store keeps its data in.",
				MarkdownDescription: "Which kind of storage the data store keeps its data in.",
			},
		},
	}
}

type GcpCollectionDataStoreModel struct {
	AuthenticationType    types.String `tfsdk:"authentication_type"`
	BucketName            types.String `tfsdk:"bucket_name"`
	CollectionDataStoreId types.String `tfsdk:"collection_data_store_id"`
	CreatedTime           types.String `tfsdk:"created_time"`
	DeploymentId          types.String `tfsdk:"deployment_id"`
	Enabled               types.Bool   `tfsdk:"enabled"`
	Id                    types.String `tfsdk:"id"`
	LastUpdatedTime       types.String `tfsdk:"last_updated_time"`
	Name                  types.String `tfsdk:"name"`
	StorageType           types.String `tfsdk:"storage_type"`
}
