// Code generated by terraform-plugin-framework-generator DO NOT EDIT.

package datasource_aws_collection_data_store

import (
	"context"
	"github.com/hashicorp/terraform-plugin-framework/types"

	"github.com/hashicorp/terraform-plugin-framework/datasource/schema"
)

func AwsCollectionDataStoreDataSourceSchema(ctx context.Context) schema.Schema {
	return schema.Schema{
		Attributes: map[string]schema.Attribute{
			"authentication_type": schema.StringAttribute{
				Computed:            true,
				Description:         "How Monte Carlo authenticates when it reaches the data store.",
				MarkdownDescription: "How Monte Carlo authenticates when it reaches the data store.",
			},
			"bucket_name": schema.StringAttribute{
				Computed:            true,
				Description:         "Name of the S3 bucket Monte Carlo uses. Empty until it has been registered.",
				MarkdownDescription: "Name of the S3 bucket Monte Carlo uses. Empty until it has been registered.",
			},
			"collection_data_store_id": schema.StringAttribute{
				Required:            true,
				Description:         "Id of the collection data store, as returned when it is registered or listed.",
				MarkdownDescription: "Id of the collection data store, as returned when it is registered or listed.",
			},
			"created_time": schema.StringAttribute{
				Computed:            true,
				Description:         "When the data store was created, which is when its deployment was provisioned.",
				MarkdownDescription: "When the data store was created, which is when its deployment was provisioned.",
			},
			"deployment_id": schema.StringAttribute{
				Computed:            true,
				Description:         "Identifier of the deployment this data store belongs to.",
				MarkdownDescription: "Identifier of the deployment this data store belongs to.",
			},
			"enabled": schema.BoolAttribute{
				Computed:            true,
				Description:         "Whether Monte Carlo is using this data store. One that is unregistered, or whose validation failed, is not enabled.",
				MarkdownDescription: "Whether Monte Carlo is using this data store. One that is unregistered, or whose validation failed, is not enabled.",
			},
			"external_id": schema.StringAttribute{
				Computed:            true,
				Description:         "Value to put in the trust policy of the role Monte Carlo assumes to access the bucket. Null before Monte Carlo has generated one, and for a caller who cannot register a data store. Also null if the value could not be read just now, so retry once before treating it as absent.",
				MarkdownDescription: "Value to put in the trust policy of the role Monte Carlo assumes to access the bucket. Null before Monte Carlo has generated one, and for a caller who cannot register a data store. Also null if the value could not be read just now, so retry once before treating it as absent.",
			},
			"id": schema.StringAttribute{
				Computed:            true,
				Description:         "Unique identifier of the data store.",
				MarkdownDescription: "Unique identifier of the data store.",
			},
			"last_updated_time": schema.StringAttribute{
				Computed:            true,
				Description:         "When the data store was last registered, renamed, or given different storage or credentials. Null until one of those has happened.",
				MarkdownDescription: "When the data store was last registered, renamed, or given different storage or credentials. Null until one of those has happened.",
			},
			"name": schema.StringAttribute{
				Computed:            true,
				Description:         "Display name of the data store. Null when it has no name.",
				MarkdownDescription: "Display name of the data store. Null when it has no name.",
			},
			"storage_type": schema.StringAttribute{
				Computed:            true,
				Description:         "Which kind of storage the data store keeps its data in.",
				MarkdownDescription: "Which kind of storage the data store keeps its data in.",
			},
		},
		Description:         "An AWS collection data store is an S3 bucket in your AWS account where Monte Carlo keeps your account's query results, samples and temporary data, so they stay in your storage. Monte Carlo accesses it by assuming a role you create. Registering it completes a deployment provisioned for an AWS data store.",
		MarkdownDescription: "An AWS collection data store is an S3 bucket in your AWS account where Monte Carlo keeps your account's query results, samples and temporary data, so they stay in your storage. Monte Carlo accesses it by assuming a role you create. Registering it completes a deployment provisioned for an AWS data store.",
	}
}

type AwsCollectionDataStoreModel struct {
	AuthenticationType    types.String `tfsdk:"authentication_type"`
	BucketName            types.String `tfsdk:"bucket_name"`
	CollectionDataStoreId types.String `tfsdk:"collection_data_store_id"`
	CreatedTime           types.String `tfsdk:"created_time"`
	DeploymentId          types.String `tfsdk:"deployment_id"`
	Enabled               types.Bool   `tfsdk:"enabled"`
	ExternalId            types.String `tfsdk:"external_id"`
	Id                    types.String `tfsdk:"id"`
	LastUpdatedTime       types.String `tfsdk:"last_updated_time"`
	Name                  types.String `tfsdk:"name"`
	StorageType           types.String `tfsdk:"storage_type"`
}
