// Code generated by terraform-plugin-framework-generator DO NOT EDIT.

package datasource_aws_collection_data_store

import (
	"context"
	"github.com/hashicorp/terraform-plugin-framework/types"

	"github.com/hashicorp/terraform-plugin-framework/datasource/schema"
)

func AwsCollectionDataStoreDataSourceSchema(ctx context.Context) schema.Schema {
	return schema.Schema{
		Attributes: map[string]schema.Attribute{
			"authentication_type": schema.StringAttribute{
				Computed:            true,
				Description:         "How Monte Carlo authenticates to a collection agent or a data store.\n\nWhich values are possible depends on the platform it runs on.",
				MarkdownDescription: "How Monte Carlo authenticates to a collection agent or a data store.\n\nWhich values are possible depends on the platform it runs on.",
			},
			"bucket_name": schema.StringAttribute{
				Computed:            true,
				Description:         "Name of the S3 bucket Monte Carlo uses. Empty until it has been registered.",
				MarkdownDescription: "Name of the S3 bucket Monte Carlo uses. Empty until it has been registered.",
			},
			"collection_data_store_id": schema.StringAttribute{
				Required: true,
			},
			"created_time": schema.StringAttribute{
				Computed: true,
			},
			"deployment_id": schema.StringAttribute{
				Computed:            true,
				Description:         "Identifier of the deployment this data store belongs to.",
				MarkdownDescription: "Identifier of the deployment this data store belongs to.",
			},
			"enabled": schema.BoolAttribute{
				Computed:            true,
				Description:         "Whether Monte Carlo is using this data store. One that is unregistered, or whose validation failed, is not enabled.",
				MarkdownDescription: "Whether Monte Carlo is using this data store. One that is unregistered, or whose validation failed, is not enabled.",
			},
			"external_id": schema.StringAttribute{
				Computed: true,
			},
			"id": schema.StringAttribute{
				Computed:            true,
				Description:         "Unique identifier of the data store.",
				MarkdownDescription: "Unique identifier of the data store.",
			},
			"last_updated_time": schema.StringAttribute{
				Computed: true,
			},
			"name": schema.StringAttribute{
				Computed: true,
			},
			"storage_type": schema.StringAttribute{
				Computed:            true,
				Description:         "Which kind of storage a collection data store keeps its data in.\n\nWhich values are possible depends on the platform the data store runs on.",
				MarkdownDescription: "Which kind of storage a collection data store keeps its data in.\n\nWhich values are possible depends on the platform the data store runs on.",
			},
		},
	}
}

type AwsCollectionDataStoreModel struct {
	AuthenticationType    types.String `tfsdk:"authentication_type"`
	BucketName            types.String `tfsdk:"bucket_name"`
	CollectionDataStoreId types.String `tfsdk:"collection_data_store_id"`
	CreatedTime           types.String `tfsdk:"created_time"`
	DeploymentId          types.String `tfsdk:"deployment_id"`
	Enabled               types.Bool   `tfsdk:"enabled"`
	ExternalId            types.String `tfsdk:"external_id"`
	Id                    types.String `tfsdk:"id"`
	LastUpdatedTime       types.String `tfsdk:"last_updated_time"`
	Name                  types.String `tfsdk:"name"`
	StorageType           types.String `tfsdk:"storage_type"`
}
