// Code generated by terraform-plugin-framework-generator DO NOT EDIT.

package datasource_connection

import (
	"context"
	"github.com/hashicorp/terraform-plugin-framework/types"

	"github.com/hashicorp/terraform-plugin-framework/datasource/schema"
)

func ConnectionDataSourceSchema(ctx context.Context) schema.Schema {
	return schema.Schema{
		Attributes: map[string]schema.Attribute{
			"bi_container_id": schema.StringAttribute{
				Computed:            true,
				Description:         "The BI container the connection belongs to. Null for a connection on a warehouse. Fixed once created.",
				MarkdownDescription: "The BI container the connection belongs to. Null for a connection on a warehouse. Fixed once created.",
			},
			"bi_container_name": schema.StringAttribute{
				Computed:            true,
				Description:         "Display name of that BI container. Null for a container that was never named, and for a connection on a warehouse.",
				MarkdownDescription: "Display name of that BI container. Null for a container that was never named, and for a connection on a warehouse.",
			},
			"connection_id": schema.StringAttribute{
				Required:            true,
				Description:         "Id of the connection, as returned when it is created or listed.",
				MarkdownDescription: "Id of the connection, as returned when it is created or listed.",
			},
			"connection_type": schema.StringAttribute{
				Computed:            true,
				Description:         "What the connection reaches, such as `snowflake`. Taken from the credentials the connection was created with, and fixed once created.",
				MarkdownDescription: "What the connection reaches, such as `snowflake`. Taken from the credentials the connection was created with, and fixed once created.",
			},
			"created_time": schema.StringAttribute{
				Computed:            true,
				Description:         "When the connection was created.",
				MarkdownDescription: "When the connection was created.",
			},
			"credentials_id": schema.StringAttribute{
				Computed:            true,
				Description:         "The credentials the connection reads with. Null for a connection created before credentials became their own resource, and for one created outside this API.",
				MarkdownDescription: "The credentials the connection reads with. Null for a connection created before credentials became their own resource, and for one created outside this API.",
			},
			"credentials_storage_type": schema.StringAttribute{
				Computed:            true,
				Description:         "Where that secret lives. Null when there are no credentials to describe.",
				MarkdownDescription: "Where that secret lives. Null when there are no credentials to describe.",
			},
			"deployment_id": schema.StringAttribute{
				Computed:            true,
				Description:         "The deployment the connection runs through, taken from its warehouse or BI container. Null when that has no deployment. The id may name a deployment on Monte Carlo's older collection platform, which the deployments endpoints do not list.",
				MarkdownDescription: "The deployment the connection runs through, taken from its warehouse or BI container. Null when that has no deployment. The id may name a deployment on Monte Carlo's older collection platform, which the deployments endpoints do not list.",
			},
			"deployment_name": schema.StringAttribute{
				Computed:            true,
				Description:         "Display name of that deployment. Null when there is no deployment to name.",
				MarkdownDescription: "Display name of that deployment. Null when there is no deployment to name.",
			},
			"id": schema.StringAttribute{
				Computed:            true,
				Description:         "Unique identifier of the connection.",
				MarkdownDescription: "Unique identifier of the connection.",
			},
			"job_types": schema.ListAttribute{
				ElementType:         types.StringType,
				Computed:            true,
				Description:         "The jobs Monte Carlo runs on this connection, such as `metadata`.",
				MarkdownDescription: "The jobs Monte Carlo runs on this connection, such as `metadata`.",
			},
			"name": schema.StringAttribute{
				Computed:            true,
				Description:         "Display name of the connection. Null for a connection that was never named.",
				MarkdownDescription: "Display name of the connection. Null for a connection that was never named.",
			},
			"warehouse_id": schema.StringAttribute{
				Computed:            true,
				Description:         "The warehouse the connection belongs to. Null for a connection on a BI container. Fixed once created.",
				MarkdownDescription: "The warehouse the connection belongs to. Null for a connection on a BI container. Fixed once created.",
			},
			"warehouse_name": schema.StringAttribute{
				Computed:            true,
				Description:         "Display name of that warehouse. Null for a warehouse that was never named, and for a connection on a BI container.",
				MarkdownDescription: "Display name of that warehouse. Null for a warehouse that was never named, and for a connection on a BI container.",
			},
		},
		Description:         "A connection lets Monte Carlo reach a warehouse's data platform or a BI container's BI tool with one set of credentials. It belongs to a warehouse or a BI container and takes its type from the credentials it references.",
		MarkdownDescription: "A connection lets Monte Carlo reach a warehouse's data platform or a BI container's BI tool with one set of credentials. It belongs to a warehouse or a BI container and takes its type from the credentials it references.",
	}
}

type ConnectionModel struct {
	BiContainerId          types.String `tfsdk:"bi_container_id"`
	BiContainerName        types.String `tfsdk:"bi_container_name"`
	ConnectionId           types.String `tfsdk:"connection_id"`
	ConnectionType         types.String `tfsdk:"connection_type"`
	CreatedTime            types.String `tfsdk:"created_time"`
	CredentialsId          types.String `tfsdk:"credentials_id"`
	CredentialsStorageType types.String `tfsdk:"credentials_storage_type"`
	DeploymentId           types.String `tfsdk:"deployment_id"`
	DeploymentName         types.String `tfsdk:"deployment_name"`
	Id                     types.String `tfsdk:"id"`
	JobTypes               types.List   `tfsdk:"job_types"`
	Name                   types.String `tfsdk:"name"`
	WarehouseId            types.String `tfsdk:"warehouse_id"`
	WarehouseName          types.String `tfsdk:"warehouse_name"`
}
