// Code generated by terraform-plugin-framework-generator DO NOT EDIT.

package resource_fivetran_credentials

import (
	"context"
	"github.com/hashicorp/terraform-plugin-framework-validators/stringvalidator"
	"github.com/hashicorp/terraform-plugin-framework/schema/validator"
	"github.com/hashicorp/terraform-plugin-framework/types"

	"github.com/hashicorp/terraform-plugin-framework/resource/schema"
)

func FivetranCredentialsResourceSchema(ctx context.Context) schema.Schema {
	return schema.Schema{
		Attributes: map[string]schema.Attribute{
			"api_key_wo": schema.StringAttribute{
				Required:            true,
				Sensitive:           true,
				Description:         "Key of the Fivetran API key. Stored by Monte Carlo and never returned.",
				MarkdownDescription: "Key of the Fivetran API key. Stored by Monte Carlo and never returned.",
				Validators: []validator.String{
					stringvalidator.LengthBetween(1, 1024),
				},
			},
			"api_key_wo_version": schema.Int64Attribute{
				Required:            true,
				Description:         "Bump to send `api_key_wo` again. Terraform stores this, never the secret.",
				MarkdownDescription: "Bump to send `api_key_wo` again. Terraform stores this, never the secret.",
			},
			"api_password_wo": schema.StringAttribute{
				Required:            true,
				Sensitive:           true,
				Description:         "Secret of the Fivetran API key. Stored by Monte Carlo and never returned.",
				MarkdownDescription: "Secret of the Fivetran API key. Stored by Monte Carlo and never returned.",
				Validators: []validator.String{
					stringvalidator.LengthBetween(1, 1024),
				},
			},
			"api_password_wo_version": schema.Int64Attribute{
				Required:            true,
				Description:         "Bump to send `api_password_wo` again. Terraform stores this, never the secret.",
				MarkdownDescription: "Bump to send `api_password_wo` again. Terraform stores this, never the secret.",
			},
			"base_url": schema.StringAttribute{
				Optional:            true,
				Computed:            true,
				Description:         "URL of the Fivetran REST API. Leave it out for https://api.fivetran.com/v1/.",
				MarkdownDescription: "URL of the Fivetran REST API. Leave it out for https://api.fivetran.com/v1/.",
				Validators: []validator.String{
					stringvalidator.LengthBetween(1, 2048),
				},
			},
			"connection_type": schema.StringAttribute{
				Computed:            true,
				Description:         "The connection type the credentials are for, such as `snowflake`. Fixed once created.",
				MarkdownDescription: "The connection type the credentials are for, such as `snowflake`. Fixed once created.",
			},
			"created_time": schema.StringAttribute{
				Computed:            true,
				Description:         "When the credentials were created.",
				MarkdownDescription: "When the credentials were created.",
			},
			"id": schema.StringAttribute{
				Computed:            true,
				Description:         "Unique identifier of the credentials.",
				MarkdownDescription: "Unique identifier of the credentials.",
			},
			"storage_type": schema.StringAttribute{
				Computed:            true,
				Description:         "Where the secret lives. Fixed once created.",
				MarkdownDescription: "Where the secret lives. Fixed once created.",
			},
		},
	}
}

type FivetranCredentialsModel struct {
	ApiKeyWo             types.String `tfsdk:"api_key_wo"`
	ApiKeyWoVersion      types.Int64  `tfsdk:"api_key_wo_version"`
	ApiPasswordWo        types.String `tfsdk:"api_password_wo"`
	ApiPasswordWoVersion types.Int64  `tfsdk:"api_password_wo_version"`
	BaseUrl              types.String `tfsdk:"base_url"`
	ConnectionType       types.String `tfsdk:"connection_type"`
	CreatedTime          types.String `tfsdk:"created_time"`
	Id                   types.String `tfsdk:"id"`
	StorageType          types.String `tfsdk:"storage_type"`
}
