// Code generated by terraform-plugin-framework-generator DO NOT EDIT.

package resource_generic_collection_agent

import (
	"context"
	"github.com/hashicorp/terraform-plugin-framework-validators/stringvalidator"
	"github.com/hashicorp/terraform-plugin-framework/schema/validator"
	"github.com/hashicorp/terraform-plugin-framework/types"

	"github.com/hashicorp/terraform-plugin-framework/resource/schema"
)

func GenericCollectionAgentResourceSchema(ctx context.Context) schema.Schema {
	return schema.Schema{
		Attributes: map[string]schema.Attribute{
			"authentication_type": schema.StringAttribute{
				Computed:            true,
				Description:         "How Monte Carlo authenticates when it calls the collection agent. Null for an agent that connects out instead, such as a generic one.",
				MarkdownDescription: "How Monte Carlo authenticates when it calls the collection agent. Null for an agent that connects out instead, such as a generic one.",
			},
			"created_time": schema.StringAttribute{
				Computed:            true,
				Description:         "When the collection agent was created. That is when its deployment was provisioned, which is before you register the agent.",
				MarkdownDescription: "When the collection agent was created. That is when its deployment was provisioned, which is before you register the agent.",
			},
			"deployment_id": schema.StringAttribute{
				Required:            true,
				Description:         "Deployment whose generic collection agent to enable. It must have been provisioned for one, and the agent must be running with a credential created for this deployment.",
				MarkdownDescription: "Deployment whose generic collection agent to enable. It must have been provisioned for one, and the agent must be running with a credential created for this deployment.",
			},
			"enabled": schema.BoolAttribute{
				Computed:            true,
				Description:         "Whether Monte Carlo is using this collection agent. An agent Monte Carlo has not validated is not enabled, either because it has not been registered yet or because validation failed.",
				MarkdownDescription: "Whether Monte Carlo is using this collection agent. An agent Monte Carlo has not validated is not enabled, either because it has not been registered yet or because validation failed.",
			},
			"id": schema.StringAttribute{
				Computed:            true,
				Description:         "Unique identifier of the collection agent.",
				MarkdownDescription: "Unique identifier of the collection agent.",
			},
			"image_build": schema.StringAttribute{
				Computed:            true,
				Description:         "Build of the image the collection agent is running. Null until Monte Carlo has contacted the agent.",
				MarkdownDescription: "Build of the image the collection agent is running. Null until Monte Carlo has contacted the agent.",
			},
			"image_version": schema.StringAttribute{
				Computed:            true,
				Description:         "Version of the image the collection agent is running. Null until Monte Carlo has contacted the agent.",
				MarkdownDescription: "Version of the image the collection agent is running. Null until Monte Carlo has contacted the agent.",
			},
			"is_remote_upgradeable": schema.BoolAttribute{
				Computed:            true,
				Description:         "Whether Monte Carlo can update the collection agent's image for you.",
				MarkdownDescription: "Whether Monte Carlo can update the collection agent's image for you.",
			},
			"last_updated_time": schema.StringAttribute{
				Computed:            true,
				Description:         "When the collection agent was last changed. Registering it, renaming it, changing how Monte Carlo reaches it, and Monte Carlo picking up a new image version all update this. Null until any of those has happened.",
				MarkdownDescription: "When the collection agent was last changed. Registering it, renaming it, changing how Monte Carlo reaches it, and Monte Carlo picking up a new image version all update this. Null until any of those has happened.",
			},
			"name": schema.StringAttribute{
				Optional:            true,
				Computed:            true,
				Description:         "Display name for the collection agent. Replaces the name it currently has.",
				MarkdownDescription: "Display name for the collection agent. Replaces the name it currently has.",
				Validators: []validator.String{
					stringvalidator.LengthAtMost(200),
				},
			},
		},
		Description:         "A generic collection agent runs anywhere you choose and connects out to Monte Carlo with a token or an OAuth client. Registering it enables a deployment provisioned for a generic agent, once the agent has connected.",
		MarkdownDescription: "A generic collection agent runs anywhere you choose and connects out to Monte Carlo with a token or an OAuth client. Registering it enables a deployment provisioned for a generic agent, once the agent has connected.",
	}
}

type GenericCollectionAgentModel struct {
	AuthenticationType  types.String `tfsdk:"authentication_type"`
	CreatedTime         types.String `tfsdk:"created_time"`
	DeploymentId        types.String `tfsdk:"deployment_id"`
	Enabled             types.Bool   `tfsdk:"enabled"`
	Id                  types.String `tfsdk:"id"`
	ImageBuild          types.String `tfsdk:"image_build"`
	ImageVersion        types.String `tfsdk:"image_version"`
	IsRemoteUpgradeable types.Bool   `tfsdk:"is_remote_upgradeable"`
	LastUpdatedTime     types.String `tfsdk:"last_updated_time"`
	Name                types.String `tfsdk:"name"`
}
