// Code generated by terraform-plugin-framework-generator DO NOT EDIT.

package resource_snowflake_credentials

import (
	"context"
	"github.com/hashicorp/terraform-plugin-framework-validators/stringvalidator"
	"github.com/hashicorp/terraform-plugin-framework/schema/validator"
	"github.com/hashicorp/terraform-plugin-framework/types"

	"github.com/hashicorp/terraform-plugin-framework/resource/schema"
)

func SnowflakeCredentialsResourceSchema(ctx context.Context) schema.Schema {
	return schema.Schema{
		Attributes: map[string]schema.Attribute{
			"account": schema.StringAttribute{
				Required:            true,
				Description:         "Snowflake account identifier, such as `xy12345.us-east-1`. Without the `.snowflakecomputing.com` suffix.",
				MarkdownDescription: "Snowflake account identifier, such as `xy12345.us-east-1`. Without the `.snowflakecomputing.com` suffix.",
				Validators: []validator.String{
					stringvalidator.LengthBetween(1, 200),
				},
			},
			"connection_type": schema.StringAttribute{
				Computed:            true,
				Description:         "The connection type the credentials are for, such as `snowflake`. Fixed once created.",
				MarkdownDescription: "The connection type the credentials are for, such as `snowflake`. Fixed once created.",
			},
			"created_time": schema.StringAttribute{
				Computed:            true,
				Description:         "When the credentials were created.",
				MarkdownDescription: "When the credentials were created.",
			},
			"id": schema.StringAttribute{
				Computed:            true,
				Description:         "Unique identifier of the credentials.",
				MarkdownDescription: "Unique identifier of the credentials.",
			},
			"private_key": schema.StringAttribute{
				Required:            true,
				Sensitive:           true,
				Description:         "The private key of the pair, as PEM text including its BEGIN and END lines. Stored by Monte Carlo and never returned.",
				MarkdownDescription: "The private key of the pair, as PEM text including its BEGIN and END lines. Stored by Monte Carlo and never returned.",
				Validators: []validator.String{
					stringvalidator.LengthBetween(1, 32768),
				},
			},
			"private_key_passphrase": schema.StringAttribute{
				Optional:            true,
				Computed:            true,
				Description:         "Passphrase the private key is encrypted with. Omit it for an unencrypted key. Never returned.",
				MarkdownDescription: "Passphrase the private key is encrypted with. Omit it for an unencrypted key. Never returned.",
				Validators: []validator.String{
					stringvalidator.LengthBetween(1, 32768),
				},
			},
			"storage_type": schema.StringAttribute{
				Computed:            true,
				Description:         "Where the secret lives. Fixed once created.",
				MarkdownDescription: "Where the secret lives. Fixed once created.",
			},
			"user": schema.StringAttribute{
				Required:            true,
				Description:         "Snowflake user the key pair belongs to.",
				MarkdownDescription: "Snowflake user the key pair belongs to.",
				Validators: []validator.String{
					stringvalidator.LengthBetween(1, 200),
				},
			},
			"warehouse": schema.StringAttribute{
				Optional:            true,
				Computed:            true,
				Description:         "Snowflake virtual warehouse to run queries in. Omit it to use the user's default.",
				MarkdownDescription: "Snowflake virtual warehouse to run queries in. Omit it to use the user's default.",
				Validators: []validator.String{
					stringvalidator.LengthBetween(1, 200),
				},
			},
		},
	}
}

type SnowflakeCredentialsModel struct {
	Account              types.String `tfsdk:"account"`
	ConnectionType       types.String `tfsdk:"connection_type"`
	CreatedTime          types.String `tfsdk:"created_time"`
	Id                   types.String `tfsdk:"id"`
	PrivateKey           types.String `tfsdk:"private_key"`
	PrivateKeyPassphrase types.String `tfsdk:"private_key_passphrase"`
	StorageType          types.String `tfsdk:"storage_type"`
	User                 types.String `tfsdk:"user"`
	Warehouse            types.String `tfsdk:"warehouse"`
}
